import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const CORS={
  'Access-Control-Allow-Origin':'*',
  'Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods':'POST, OPTIONS',
  'Access-Control-Max-Age':'86400'
};
const json=(data:any,status=200)=>new Response(JSON.stringify(data),{status,headers:{...CORS,'content-type':'application/json','cache-control':'no-store'}});
const day=/^\d{4}-\d{2}-\d{2}$/;
const nowIso=()=>new Date().toISOString();
const safeText=(v:any)=>v===null||v===undefined?null:String(v);
const totalScore=(x:any)=>safeText(x?.total??x?.score??x?.points??x);
const statusOf=(short:any,long:any,startsAt:string,completed=false,state:any='')=>{
  const s=String(short||'').toUpperCase(),l=String(long||'').toLowerCase(),st=String(state||'').toLowerCase();
  if(completed||['FT','AET','PEN','FINAL','FINISHED','STATUS_FINAL'].includes(s)||/finished|final|after extra|penalt/.test(l))return'finished';
  if(st==='in'||['1H','2H','HT','ET','BT','LIVE','Q1','Q2','Q3','Q4','OT','P1','P2','P3','IN PLAY','STATUS_IN_PROGRESS','STATUS_FIRST_HALF','STATUS_SECOND_HALF','STATUS_HALFTIME','STATUS_EXTRA_TIME'].includes(s)||/live|progress|quarter|period|halftime|first half|second half|extra time|in progress/.test(l))return'live';
  if(['PST','POST','POSTPONED'].includes(s)||/postpon/.test(l))return'postponed';
  if(['CANC','CANCELLED'].includes(s)||/cancel/.test(l))return'cancelled';
  return new Date(startsAt).getTime()>Date.now()?'scheduled':'unknown';
};
const startFromTsd=(x:any)=>{
  if(x?.strTimestamp){const d=new Date(x.strTimestamp);if(!Number.isNaN(d.getTime()))return d.toISOString()}
  const date=String(x?.dateEvent||'').slice(0,10),time=String(x?.strTime||x?.strEventTime||'00:00:00').slice(0,8);
  const d=new Date(`${date}T${time.length===5?time+':00':time}Z`);
  return Number.isNaN(d.getTime())?`${date}T12:00:00.000Z`:d.toISOString();
};

type CanonicalEvent={
  sport_slug:string;provider:string;provider_event_id:string;title:string;starts_at:string;status:string;
  competition?:{id:string;name:string;logo?:string|null;country?:string|null};
  home?:{id:string;name:string;logo?:string|null;country?:string|null};
  away?:{id:string;name:string;logo?:string|null;country?:string|null};
  season?:string|null;round?:string|null;venue?:string|null;home_score?:string|null;away_score?:string|null;image_url?:string|null;participants?:any[];raw:any;
};

const ESPN_ROUTES:Record<string,Array<[string,string,string]>>={
  soccer:[
    ['soccer','bra.1','Brasileirão Série A'],['soccer','bra.2','Brasileirão Série B'],['soccer','bra.copa_do_brazil','Copa do Brasil'],
    ['soccer','arg.1','Argentina Primera'],['soccer','mex.1','Liga MX'],['soccer','mex.2','Liga de Expansión MX'],['soccer','usa.1','MLS'],['soccer','ksa.1','Saudi Pro League'],
    ['soccer','eng.1','Premier League'],['soccer','esp.1','LaLiga'],['soccer','ita.1','Serie A'],['soccer','ger.1','Bundesliga'],['soccer','fra.1','Ligue 1'],['soccer','por.1','Liga Portugal'],['soccer','ned.1','Eredivisie'],
    ['soccer','uefa.champions','Champions League'],['soccer','uefa.europa','Europa League'],['soccer','conmebol.libertadores','Libertadores'],['soccer','conmebol.sudamericana','Sul-Americana']
  ],
  basketball:[['basketball','nba','NBA'],['basketball','wnba','WNBA']],
  american_football:[['football','nfl','NFL']],
  ice_hockey:[['hockey','nhl','NHL']],
  baseball:[['baseball','mlb','MLB']]
};

Deno.serve(async(req:Request)=>{
  if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});
  if(req.method!=='POST')return json({error:'POST required'},405);
  try{
    const url=Deno.env.get('SUPABASE_URL')!,serviceKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,anonKey=Deno.env.get('SUPABASE_ANON_KEY')!;
    const auth=req.headers.get('authorization')||'';
    if(!auth.toLowerCase().startsWith('bearer '))return json({error:'authorization required'},401);
    const admin=createClient(url,serviceKey),userSb=createClient(url,anonKey,{global:{headers:{Authorization:auth}}});
    const {data:userData,error:userError}=await userSb.auth.getUser();if(userError||!userData?.user?.id)return json({error:'invalid session'},401);
    let body:any={};try{body=await req.json()}catch{}
    const action=String(body?.action||'sync'),apiKey=Deno.env.get('API_SPORTS_KEY')||'';
    if(action==='status')return json({ok:true,api_sports_configured:Boolean(apiKey),fallback:'espn+thesportsdb',espn_supported:Object.keys(ESPN_ROUTES),soccer_routes:ESPN_ROUTES.soccer.map(x=>x[1]),version:'sports-hub-v4'});
    const from=day.test(String(body?.date_from||''))?String(body.date_from):new Date().toISOString().slice(0,10);
    const maxTo=new Date(`${from}T12:00:00Z`);maxTo.setUTCDate(maxTo.getUTCDate()+2);
    const requestedTo=day.test(String(body?.date_to||''))?String(body.date_to):from,to=requestedTo>maxTo.toISOString().slice(0,10)?maxTo.toISOString().slice(0,10):requestedTo,force=body?.force===true;
    const {data:catalog,error:catalogError}=await admin.from('sports_catalog').select('slug,name_pt,provider_sport_name,metadata,enabled').eq('enabled',true).order('sort_order');if(catalogError)throw catalogError;
    const requested=Array.isArray(body?.sports)?new Set(body.sports.map(String)):null,selected=(catalog||[]).filter((s:any)=>!requested||requested.has(s.slug));if(!selected.length)return json({error:'no sports selected'},400);
    const tsdKey=Deno.env.get('THESPORTSDB_KEY')||'123',stats={sports:selected.length,days:0,provider_calls:0,events_received:0,events_upserted:0,entities_upserted:0,skipped_cached:0,errors:[] as any[]};
    const providersUsed=new Set<string>(),entityCache=new Map<string,number>(),dates:string[]=[];
    for(let d=new Date(`${from}T12:00:00Z`);d<=new Date(`${to}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+1))dates.push(d.toISOString().slice(0,10));stats.days=dates.length;
    async function fetchJson(target:string,headers:Record<string,string>={}){stats.provider_calls++;const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(target,{headers:{accept:'application/json','user-agent':'CineTracker/0.99.7',...headers},signal:c.signal});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`HTTP ${r.status}`);return d}finally{clearTimeout(t)}}
    async function apiGet(base:string,path:string){const d=await fetchJson(`${base}${path}`,{'x-apisports-key':apiKey});if(d?.errors&&(Array.isArray(d.errors)?d.errors.length:Object.keys(d.errors||{}).length))throw new Error(`API-Sports: ${JSON.stringify(d.errors).slice(0,180)}`);return Array.isArray(d?.response)?d.response:[]}
    async function tsdGet(date:string,sportName:string){const d=await fetchJson(`https://www.thesportsdb.com/api/v1/json/${encodeURIComponent(tsdKey)}/eventsday.php?d=${encodeURIComponent(date)}&s=${encodeURIComponent(sportName)}`);return Array.isArray(d?.events)?d.events:[]}
    async function espnRoute(sport:string,league:string,label:string,date:string){const ds=date.replaceAll('-',''),urls=[`https://site.web.api.espn.com/apis/site/v2/sports/${sport}/${league}/scoreboard?dates=${ds}&limit=500`,`https://site.api.espn.com/apis/site/v2/sports/${sport}/${league}/scoreboard?dates=${ds}&limit=500`];let last:any=null;for(const u of urls){try{const d=await fetchJson(u);return{events:Array.isArray(d?.events)?d.events:[],league:d?.leagues?.[0],label}}catch(e){last=e}}throw last||new Error('ESPN unavailable')}
    function fromFootball(x:any,slug:string):CanonicalEvent{const starts=String(x?.fixture?.date||new Date(Number(x?.fixture?.timestamp||0)*1000).toISOString());return{sport_slug:slug,provider:'api-sports:football',provider_event_id:String(x.fixture.id),title:`${x?.teams?.home?.name||''} x ${x?.teams?.away?.name||''}`.trim(),starts_at:starts,status:statusOf(x?.fixture?.status?.short,x?.fixture?.status?.long,starts),competition:{id:String(x?.league?.id),name:String(x?.league?.name||'Futebol'),logo:x?.league?.logo,country:x?.league?.country},home:x?.teams?.home?.id?{id:String(x.teams.home.id),name:String(x.teams.home.name),logo:x.teams.home.logo}:undefined,away:x?.teams?.away?.id?{id:String(x.teams.away.id),name:String(x.teams.away.name),logo:x.teams.away.logo}:undefined,season:safeText(x?.league?.season),round:safeText(x?.league?.round),venue:safeText(x?.fixture?.venue?.name),home_score:safeText(x?.goals?.home),away_score:safeText(x?.goals?.away),image_url:x?.league?.logo,raw:x}}
    function fromGenericGame(x:any,slug:string,product:string):CanonicalEvent{const g=x?.game||x,starts=g?.date?.date&&g?.date?.time?new Date(Number(g.date.timestamp||0)*1000).toISOString():String(g?.date||new Date(Number(g?.timestamp||0)*1000).toISOString()),home=x?.teams?.home,away=x?.teams?.away,league=x?.league;return{sport_slug:slug,provider:`api-sports:${product}`,provider_event_id:String(g?.id||x?.id),title:`${home?.name||''} x ${away?.name||''}`.trim(),starts_at:starts,status:statusOf(g?.status?.short||x?.status?.short,g?.status?.long||x?.status?.long,starts),competition:league?.id?{id:String(league.id),name:String(league.name||product),logo:league.logo,country:x?.country?.name||league.country}:undefined,home:home?.id?{id:String(home.id),name:String(home.name),logo:home.logo}:undefined,away:away?.id?{id:String(away.id),name:String(away.name),logo:away.logo}:undefined,season:safeText(league?.season),round:safeText(g?.week||g?.stage||x?.week),venue:safeText(g?.venue?.name||x?.venue),home_score:totalScore(x?.scores?.home),away_score:totalScore(x?.scores?.away),image_url:league?.logo,raw:x}}
    function fromFormula1(x:any,slug:string):CanonicalEvent{const starts=String(x?.date||x?.competition?.date||''),comp=x?.competition||{},circuit=x?.circuit||{};return{sport_slug:slug,provider:'api-sports:formula-1',provider_event_id:String(x?.id),title:String(comp?.name||x?.type||'Fórmula 1'),starts_at:starts,status:statusOf(x?.status?.short,x?.status?.long,starts),competition:{id:String(comp?.id||`season-${x?.season}`),name:String(comp?.name||'Formula 1'),logo:comp?.logo,country:comp?.location?.country||comp?.country?.name},season:safeText(x?.season),round:safeText(x?.type),venue:safeText(circuit?.name||comp?.location?.city),image_url:comp?.logo||circuit?.image,participants:Array.isArray(x?.participants)?x.participants:[],raw:x}}
    function fromTsd(x:any,slug:string):CanonicalEvent{const starts=startFromTsd(x),homeId=x?.idHomeTeam,awayId=x?.idAwayTeam,leagueId=x?.idLeague;return{sport_slug:slug,provider:'thesportsdb',provider_event_id:String(x?.idEvent),title:String(x?.strEvent||[x?.strHomeTeam,x?.strAwayTeam].filter(Boolean).join(' x ')||x?.strLeague||'Evento esportivo'),starts_at:starts,status:statusOf(x?.strStatus,x?.strProgress,starts),competition:leagueId?{id:String(leagueId),name:String(x?.strLeague||'Competição'),logo:x?.strLeagueBadge,country:x?.strCountry}:undefined,home:homeId?{id:String(homeId),name:String(x?.strHomeTeam||'Mandante'),logo:x?.strHomeTeamBadge}:undefined,away:awayId?{id:String(awayId),name:String(x?.strAwayTeam||'Visitante'),logo:x?.strAwayTeamBadge}:undefined,season:safeText(x?.strSeason),round:safeText(x?.intRound||x?.strRound),venue:safeText(x?.strVenue),home_score:safeText(x?.intHomeScore),away_score:safeText(x?.intAwayScore),image_url:x?.strThumb||x?.strPoster||x?.strBanner||x?.strLeagueBadge,participants:[],raw:x}}
    function fromEspn(x:any,slug:string,leagueCode:string,label:string,leagueMeta:any):CanonicalEvent{const comp=x?.competitions?.[0]||{},cs=Array.isArray(comp?.competitors)?comp.competitors:[],home=cs.find((c:any)=>c?.homeAway==='home')||cs[0],away=cs.find((c:any)=>c?.homeAway==='away')||cs[1],starts=String(x?.date||comp?.date||''),leagueName=String(leagueMeta?.name||leagueMeta?.abbreviation||label||leagueCode),logo=(leagueMeta?.logos||[])[0]?.href||null;const team=(c:any)=>c?.team?.id?{id:`${leagueCode}:${c.team.id}`,name:String(c.team.displayName||c.team.shortDisplayName||c.team.name||'Time'),logo:(c.team.logos||[])[0]?.href||c.team.logo||null}:undefined;return{sport_slug:slug,provider:`espn:${slug}`,provider_event_id:`${leagueCode}:${x?.id}`,title:String(x?.name||x?.shortName||[home?.team?.displayName,away?.team?.displayName].filter(Boolean).join(' x ')||label),starts_at:starts,status:statusOf(comp?.status?.type?.name,comp?.status?.type?.description,starts,Boolean(comp?.status?.type?.completed),comp?.status?.type?.state),competition:{id:leagueCode,name:leagueName,logo,country:null},home:team(home),away:team(away),season:safeText(x?.season?.year||x?.season?.slug),round:safeText(comp?.week?.text||comp?.round?.displayName||comp?.round||x?.season?.slug),venue:safeText(comp?.venue?.fullName),home_score:safeText(home?.score),away_score:safeText(away?.score),image_url:logo,participants:[],raw:x}}
    async function apiSportsEvents(s:any,date:string):Promise<CanonicalEvent[]|null>{if(!apiKey)return null;try{if(s.slug==='soccer')return(await apiGet('https://v3.football.api-sports.io',`/fixtures?date=${date}&timezone=UTC`)).map((x:any)=>fromFootball(x,s.slug));if(s.slug==='basketball')return(await apiGet('https://v1.basketball.api-sports.io',`/games?date=${date}`)).map((x:any)=>fromGenericGame(x,s.slug,'basketball'));if(s.slug==='ice_hockey')return(await apiGet('https://v1.hockey.api-sports.io',`/games?date=${date}`)).map((x:any)=>fromGenericGame(x,s.slug,'hockey'));if(s.slug==='american_football')return(await apiGet('https://v1.american-football.api-sports.io',`/games?date=${date}`)).map((x:any)=>fromGenericGame(x,s.slug,'nfl'));if(s.slug==='baseball')return(await apiGet('https://v1.baseball.api-sports.io',`/games?date=${date}`)).map((x:any)=>fromGenericGame(x,s.slug,'baseball'));if(s.slug==='formula_1'){const season=Number(date.slice(0,4)),all=await apiGet('https://v1.formula-1.api-sports.io',`/races?season=${season}`);return all.filter((x:any)=>String(x?.date||'').slice(0,10)===date).map((x:any)=>fromFormula1(x,s.slug))}}catch(e){stats.errors.push({sport:s.slug,date,provider:'api-sports',error:String(e).slice(0,220)});return null}return null}
    async function espnEvents(s:any,date:string):Promise<CanonicalEvent[]|null>{const routes=ESPN_ROUTES[s.slug];if(!routes?.length)return null;const settled=await Promise.all(routes.map(async([sport,league,label])=>{try{const d=await espnRoute(sport,league,label,date);return d.events.map((x:any)=>fromEspn(x,s.slug,league,label,d.league))}catch(e){stats.errors.push({sport:s.slug,date,provider:'espn',league,error:String(e).slice(0,180)});return[]}}));const all=settled.flat(),seen=new Set<string>();return all.filter(e=>{const k=e.provider_event_id;if(seen.has(k))return false;seen.add(k);return true})}
    function allowedByCatalog(s:any,e:any){const filters=Array.isArray(s?.metadata?.league_filters)?s.metadata.league_filters.map((v:any)=>String(v).toLowerCase()):[];if(!filters.length)return true;const hay=`${e?.strLeague||''} ${e?.strEvent||''}`.toLowerCase();return filters.some((f:string)=>hay.includes(f))}
    async function upsertEntity(sportSlug:string,type:string,provider:string,item:any){if(!item?.id||!item?.name)return null;const key=`${provider}|${type}|${item.id}`;if(entityCache.has(key))return entityCache.get(key)!;const row={sport_slug:sportSlug,entity_type:type,provider,provider_id:String(item.id),name:String(item.name),country:item.country||null,logo_url:item.logo||null,image_url:item.image||null,metadata:item.metadata||{},updated_at:nowIso()};const {data,error}=await admin.from('sport_entities').upsert(row,{onConflict:'provider,entity_type,provider_id'}).select('id').single();if(error)throw error;const id=Number(data.id);entityCache.set(key,id);stats.entities_upserted++;return id}
    async function persist(e:CanonicalEvent){if(!e.provider_event_id||!e.starts_at||Number.isNaN(new Date(e.starts_at).getTime()))return;const [compId,homeId,awayId]=await Promise.all([e.competition?upsertEntity(e.sport_slug,'competition',e.provider,e.competition):Promise.resolve(null),e.home?upsertEntity(e.sport_slug,'team',e.provider,e.home):Promise.resolve(null),e.away?upsertEntity(e.sport_slug,'team',e.provider,e.away):Promise.resolve(null)]);const row={sport_slug:e.sport_slug,provider:e.provider,provider_event_id:e.provider_event_id,competition_entity_id:compId,home_entity_id:homeId,away_entity_id:awayId,title:e.title||'Evento esportivo',starts_at:e.starts_at,status:e.status||'unknown',season:e.season||null,round:e.round||null,venue:e.venue||null,home_score:e.home_score||null,away_score:e.away_score||null,image_url:e.image_url||null,participants:e.participants||[],raw:e.raw||{},last_synced_at:nowIso(),updated_at:nowIso()};const {error}=await admin.from('sport_events').upsert(row,{onConflict:'provider,provider_event_id'});if(error)throw error;stats.events_upserted++;providersUsed.add(e.provider)}
    for(const s of selected){for(const date of dates){const expected=apiKey&&['soccer','basketball','ice_hockey','american_football','baseball','formula_1'].includes(s.slug)?'api-sports':(ESPN_ROUTES[s.slug]?.length?'espn':'thesportsdb');if(!force){const {data:state}=await admin.from('sport_sync_state').select('last_synced_at,status').eq('provider',expected).eq('sport_slug',s.slug).eq('sync_date',date).maybeSingle();if(state?.last_synced_at){const age=Date.now()-new Date(state.last_synced_at).getTime(),today=date===new Date().toISOString().slice(0,10),ttl=today?2*60*1000:6*60*60*1000;if(age<ttl&&state.status==='ok'){stats.skipped_cached++;continue}}}let canonical=await apiSportsEvents(s,date),provider='api-sports';if(canonical===null){canonical=await espnEvents(s,date);provider='espn'}if(canonical===null||canonical.length===0){provider='thesportsdb';try{const raw=await tsdGet(date,String(s.provider_sport_name));canonical=raw.filter((e:any)=>allowedByCatalog(s,e)).map((e:any)=>fromTsd(e,s.slug))}catch(e){canonical=[];stats.errors.push({sport:s.slug,date,provider,error:String(e).slice(0,220)})}}stats.events_received+=canonical.length;for(let i=0;i<canonical.length;i+=8)await Promise.all(canonical.slice(i,i+8).map(async e=>{try{await persist(e)}catch(err){stats.errors.push({sport:s.slug,date,provider,event:e.provider_event_id,error:String(err).slice(0,220)})}}));await admin.from('sport_sync_state').upsert({provider,sport_slug:s.slug,sync_date:date,status:'ok',event_count:canonical.length,last_error:null,metadata:{api_sports_configured:Boolean(apiKey),fallback:'espn+thesportsdb',version:'sports-hub-v4'},last_synced_at:nowIso()},{onConflict:'provider,sport_slug,sync_date'})}}
    await admin.from('profiles').update({updated_at:nowIso()}).eq('id',userData.user.id);
    return json({ok:true,...stats,providers:[...providersUsed],api_sports_configured:Boolean(apiKey),fallback:'espn+thesportsdb',date_from:from,date_to:to,version:'sports-hub-v4'});
  }catch(e){return json({error:String(e)},500)}
});
