import {readFile,writeFile,rm} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
await import('./build-r497.mjs');
const root=dirname(fileURLToPath(import.meta.url)),dist=resolve(root,'dist');
let [html,js,css,sw,releaseRaw]=await Promise.all([readFile(resolve(dist,'index.html'),'utf8'),readFile(resolve(dist,'app-v497.js'),'utf8'),readFile(resolve(dist,'app-v497.css'),'utf8'),readFile(resolve(dist,'service-worker.js'),'utf8'),readFile(resolve(dist,'release.json'),'utf8')]);
function bounds(source,anchor,label){const at=source.indexOf(anchor);if(at<0)throw new Error('r498 missing '+label+' anchor');const start=source.lastIndexOf('(()=>{',at),close=source.indexOf('\n})();',at);if(start<0||close<0)throw new Error('r498 invalid '+label+' bounds');return{start,end:close+6}}
function replaceNamed(source,anchor,name,replacement,label){const b=bounds(source,anchor,label),region=source.slice(b.start,b.end),m=new RegExp('(?:async\\s+)?function\\s+'+name+'\\s*\\(').exec(region);if(!m)throw new Error('r498 missing '+label+' '+name);const open=region.indexOf('{',m.index+m[0].length);let depth=0,mode='code',quote='',i=open;for(;i<region.length;i++){const c=region[i],n=region[i+1];if(mode==='line'){if(c==='\n')mode='code';continue}if(mode==='block'){if(c==='*'&&n==='/'){mode='code';i++}continue}if(mode==='string'){if(c==='\\'){i++;continue}if(c===quote)mode='code';continue}if(mode==='template'){if(c==='\\'){i++;continue}if(c.charCodeAt(0)===96)mode='code';continue}if(c==='/'&&n==='/'){mode='line';i++;continue}if(c==='/'&&n==='*'){mode='block';i++;continue}if(c==="'"||c==='"'){mode='string';quote=c;continue}if(c.charCodeAt(0)===96){mode='template';continue}if(c==='{')depth++;else if(c==='}'){depth--;if(depth===0){i++;break}}}if(depth!==0)throw new Error('r498 unbalanced '+label+' '+name);return source.slice(0,b.start)+region.slice(0,m.index)+replacement+region.slice(i)+source.slice(b.end)}
const A388="window.__ctR388Marker='r393-hidden-history-anchor+lightweight-movies+foryou-db-first-bounded';";
js=replaceNamed(js,A388,'normalizeBucket391',"function normalizeBucket391(x0){\n const x={...x0};\n if(x?.__ct391_authority&&['continue','dust','up_to_date','not_started','completed'].includes(String(x?.home_bucket||'')))return x;\n const watched=Number(x?.watched_episodes||0),hasNext=Number(x?.next_episode_number||0)>0,last=Date.parse(x?.last_watched_at||0)||0;\n if(watched===0&&String(x?.source_state||'')==='WatchLater')x.home_bucket='not_started';\n else if(watched>0&&hasNext)x.home_bucket=(last&&Date.now()-last>30*86400000)?'dust':'continue';\n else if(watched>0)x.home_bucket='up_to_date';\n else if(String(x?.source_state||'')==='UpToDate')x.home_bucket='up_to_date';\n else if(String(x?.source_state||'')==='InProgress'&&hasNext)x.home_bucket='continue';\n else if(String(x?.source_state||'')==='InProgress')x.home_bucket='up_to_date';\n return x\n}",'r388');
js=replaceNamed(js,A388,'mergeLogicalSeries',"function mergeLogicalSeries(list){\n const map=new Map();\n for(const x0 of rows(list)){\n  const tmdb=Number(x0?.tmdb_id||0),media=Number(x0?.media_id||x0?.id||0),id=tmdb!==0?'tmdb:'+String(tmdb):(media>0?'media:'+String(media):'');\n  if(!id)continue;\n  const x={...x0},prev=map.get(id);if(!prev){map.set(id,x);continue}\n  const pAuth=!!prev?.__ct391_authority,xAuth=!!x?.__ct391_authority;\n  const pWhen=Math.max(Date.parse(prev?.state_updated_at||0)||0,Date.parse(prev?.last_watched_at||0)||0),xWhen=Math.max(Date.parse(x?.state_updated_at||0)||0,Date.parse(x?.last_watched_at||0)||0);\n  const primary=xAuth!==pAuth?(xAuth?x:prev):(xWhen>pWhen?x:prev),secondary=primary===x?prev:x,out={...primary};\n  for(const k of ['poster_path','release_year','raw_tmdb'])if((out[k]===null||out[k]===undefined||out[k]==='')&&secondary?.[k]!=null)out[k]=secondary[k];\n  if((!out.title||/^Stuart Fails/i.test(out.title))&&secondary?.title)out.title=secondary.title;\n  map.set(id,out)\n }\n return [...map.values()].map(normalizeBucket391)\n}",'r388');
js=replaceNamed(js,A388,'renderSeries',"function renderSeries(){\n const view=q('[data-home-view=\"series\"]');if(!view)return false;\n qa(':scope > [data-ct399-series-section],:scope > [data-ct397-series-section],:scope > [data-ct388-series-section],:scope > [data-ct388-series-loading]',view).forEach(x=>x.remove());\n const s=rows(hSeries),counts=window.__ctR492SeriesCounts||{},limit=Math.max(24,Math.min(250,Number(document.documentElement.dataset.ct492SeriesLimit||24)||24)),defs=[\n  ['continue','Continuar assistindo',s.filter(x=>x.home_bucket==='continue')],\n  ['dust','Juntando poeira',s.filter(x=>x.home_bucket==='dust')],\n  ['up_to_date','Em dia',s.filter(x=>x.home_bucket==='up_to_date')],\n  ['not_started','Não iniciadas / Watchlist',s.filter(x=>x.home_bucket==='not_started')],\n  ['completed','Concluídas',s.filter(x=>x.home_bucket==='completed')]\n ];\n const html=defs.map(([bucket,title,list])=>{\n  let section=seriesSection(title,list),total=Math.max(list.length,Number(counts?.[bucket]||0));\n  if(total>list.length&&list.length>=limit){\n   const more='<div class=\"ct492-more-wrap\"><button type=\"button\" class=\"chip ct492-more\" data-ct492-series-more=\"'+bucket+'\">Carregar mais · '+list.length.toLocaleString('pt-BR')+' de '+total.toLocaleString('pt-BR')+'</button></div>';\n   section=section.replace(/<\\/section>\\s*$/,more+'</section>');\n  }\n  return section;\n }).join('');\n const history=q(':scope > [data-ct388-history=\"episodes\"]',view);\n if(history)history.insertAdjacentHTML('beforebegin',html);else view.insertAdjacentHTML('beforeend',html);\n document.documentElement.dataset.ct388Series=String(s.length);return true\n}",'r388');
js=replaceNamed(js,A388,'loadSeries',"async function loadSeries(force=false){\n if(hSeriesTask&&!force)return hSeriesTask;const run=++hRun,limit=Math.max(24,Math.min(250,Number(document.documentElement.dataset.ct492SeriesLimit||24)||24));\n document.documentElement.dataset.ct492SeriesLimit=String(limit);document.documentElement.dataset.ct392LoadStage='series:'+run;\n hSeriesTask=(async()=>{try{\n  const raw=await timeout(rpc('cinetracker_home_series_v492',{p_today:today(),p_limit_per_bucket:limit}),6000),data=raw?.data??raw??{},seen=new Set(),full=[];\n  for(const x of rows(data?.rows)){const media=Number(x?.media_id||x?.id||0),tmdb=Number(x?.tmdb_id||0),key=media>0?'media:'+media:(tmdb!==0?'tmdb:'+tmdb:'');if(!key||seen.has(key))continue;seen.add(key);full.push(x)}\n  if(run!==hRun)return hSeries;window.__ctR492SeriesCounts=data?.counts||{};document.documentElement.dataset.ct492SeriesTotal=String(Number(data?.total||full.length));\n  if(full.length){hSeries=full;cacheSet(HS,hSeries);if(routeNow()==='home')renderSeries()}\n  if(!force){const job=()=>{if(routeNow()==='home')void refreshTv391(false)};if(typeof requestIdleCallback==='function')requestIdleCallback(job,{timeout:5000});else setTimeout(job,2500)}\n  return hSeries\n }catch(e){document.documentElement.dataset.ct492SeriesError=String(e?.message||e);return hSeries}\n finally{if(run===hRun)hSeriesTask=null}})();return hSeriesTask\n}",'r388');
js=replaceNamed(js,A388,'refreshTv391',"async function refreshTv391(force=false){\n if(refreshTvTask391)return refreshTvTask391;const key='ct498:tv-refresh-at',now=Date.now();\n try{if(!force&&now-Number(sessionStorage.getItem(key)||0)<10*60*1000)return{skipped:true};sessionStorage.setItem(key,String(now))}catch{}\n refreshTvTask391=(async()=>{try{\n  const base=supabaseUrl391();if(!base)return{skipped:true};const r=await fetch(base+'/functions/v1/ct-refresh-tv-state-user',{method:'POST',headers:{...auth391(),'content-type':'application/json'},body:'{}'});if(!r.ok)throw new Error('TV refresh '+r.status);const out=await r.json();\n  if(Number(out?.episodes_cached||0)>0||Number(out?.refreshed||0)>0){const limit=Math.max(24,Math.min(250,Number(document.documentElement.dataset.ct492SeriesLimit||24)||24)),raw=await timeout(rpc('cinetracker_home_series_v492',{p_today:today(),p_limit_per_bucket:limit}),6000),data=raw?.data??raw??{},seen=new Set(),full=[];for(const x of rows(data?.rows)){const media=Number(x?.media_id||x?.id||0),tmdb=Number(x?.tmdb_id||0),k=media>0?'media:'+media:(tmdb!==0?'tmdb:'+tmdb:'');if(!k||seen.has(k))continue;seen.add(k);full.push(x)}if(full.length){window.__ctR492SeriesCounts=data?.counts||{};hSeries=full;cacheSet(HS,hSeries);if(routeNow()==='home')renderSeries()}}\n  return out||{}\n }catch(e){document.documentElement.dataset.ct498TvRefreshError=String(e?.message||e);return{failed:true}}finally{refreshTvTask391=null}})();return refreshTvTask391\n}",'r388');
const A464="window.__ctR464Marker='discover-foryou-visible-owner-v421';";
js=replaceNamed(js,A464,'load',"async function load(force=false){\n setForYouState();if(routeNow()!=='discover')return false;if(loadTask)return loadTask;\n if(force&&document.documentElement.dataset.ct498ForYouReady==='1'){render();return true}\n const token=++loadToken;if(!q('[data-ct464-foryou]',root464()))renderLoading();\n loadTask=(async()=>{try{\n  const raw=unwrap(await timeout(rpcCall('cinetracker_foryou_payload_v498',{p_watch_limit:30,p_fresh_limit:48}),9000))||{},next=emptyState(),kinds=['movie','series','anime'];\n  for(const k of kinds){next.watch[k]=rows(raw?.watch?.[k]);next.fresh[k]=rows(raw?.fresh?.[k])}\n  if(!kinds.every(k=>next.watch[k].length&&next.fresh[k].length))throw new Error('RECOMMENDATION_POOL_INCOMPLETE');\n  if(token!==loadToken||routeNow()!=='discover')return false;state=next;chooseDaily();\n  let cycle=1;try{cycle=(Number(sessionStorage.getItem('ct498:foryou-cycle')||0)+1)%100000;sessionStorage.setItem('ct498:foryou-cycle',String(cycle))}catch{cycle=Date.now()%100000}\n  kinds.forEach((k,i)=>{state.idx.watch[k]=(cycle+i*3)%state.watch[k].length;state.idx.fresh[k]=(cycle+i*5+1)%state.fresh[k].length});\n  render();document.documentElement.dataset.ct498ForYouReady='1';document.documentElement.dataset.ct498ForYou='alias-safe-v498';\n  document.documentElement.dataset.ct464PoolCounts=JSON.stringify({watch:Object.fromEntries(kinds.map(k=>[k,state.watch[k].length])),fresh:Object.fromEntries(kinds.map(k=>[k,state.fresh[k].length]))});return true\n }catch(e){if(token===loadToken){delete document.documentElement.dataset.ct498ForYouReady;document.documentElement.dataset.ct498ForYouError=String(e?.message||e);const root=root464();if(root)root.innerHTML='<div data-ct464-foryou><div class=\"panel\"><div class=\"empty\">Não foi possível carregar as indicações. <button type=\"button\" class=\"chip\" data-ct490-foryou-retry>Tentar novamente</button></div></div></div>'}return false}\n finally{if(token===loadToken)loadTask=null}})();return loadTask\n}",'r464');
js=replaceNamed(js,A464,'activate',"function activate(){\n setForYouState();\n const controls=qa('[data-ct319-tab],[data-ct315-tab],[data-ct263-discover-tab],[data-discover-tab]');\n controls.forEach(b=>{const on=isForYouControl(b);b.classList.toggle('active',on);b.setAttribute('aria-selected',on?'true':'false')});\n if(document.documentElement.dataset.ct498ForYouReady==='1'){render();return true}\n if(!q('[data-ct464-foryou]',root464()))renderLoading();void load(false);return true\n}",'r464');
const A321="window.__ctR321='discover-pre-render-exact-filter+profile-home-history-parity';";
js=replaceNamed(js,A321,'topRaw321',"async function topRaw321(provider,force=false){\n if(testBridge?.top)return testBridge.top(provider,force);\n const key=String(provider),hit=topCache.get(key);if(!force&&hit&&Date.now()-hit.at<STALE)return hit.rows;\n const storage='ct498:top10:'+String(typeof localDay==='function'?localDay():new Date().toISOString().slice(0,10))+':'+key;\n if(!force)try{const c=JSON.parse(sessionStorage.getItem(storage)||'null');if(c?.movies&&c?.series){topCache.set(key,{at:Date.now(),rows:c});return c}}catch{}\n const common={watch_region:'BR',with_watch_providers:Number(provider),with_watch_monetization_types:'flatrate',sort_by:'popularity.desc',include_adult:false};\n const [m1,t1,m2,t2]=await Promise.all([\n  tmdbPage321('/discover/movie',{...common,page:1},'movie'),tmdbPage321('/discover/tv',{...common,page:1},'tv'),\n  tmdbPage321('/discover/movie',{...common,page:2},'movie'),tmdbPage321('/discover/tv',{...common,page:2},'tv')\n ]);\n const data={movies:dedupe321([...m1,...m2]),series:dedupe321([...t1,...t2])};\n topCache.set(key,{at:Date.now(),rows:data});try{sessionStorage.setItem(storage,JSON.stringify(data))}catch{}return data\n}",'r321');
js=replaceNamed(js,A321,'paintTop321',"async function paintTop321(provider,token,force=false){\n const content=q('[data-ct321-top-content]');if(!content||token!==topToken||String(discover?.tab)!=='top10')return false;\n try{\n  const raw=await topRaw321(provider,force),a=await exact321([...raw.movies,...raw.series]);\n  if(token!==topToken||String(discover?.tab)!=='top10')return false;\n  const movies=raw.movies.filter(x=>!a.blocked.has(keyOf(x))).slice(0,10),series=raw.series.filter(x=>!a.blocked.has(keyOf(x))).slice(0,10);\n  let name='Streaming';try{name=(ct171ProviderList||[]).find(x=>Number(x.provider_id)===Number(provider))?.provider_name||name}catch{}\n  content.innerHTML='<div class=\"ct288-top-name\"><b>'+esc(name)+'</b></div><section class=\"panel ct288-top-section\"><div class=\"panel-head\"><h2>Top 10 Séries</h2><small>'+series.length+'</small></div><div class=\"ct319-top-row\">'+(series.map((x,i)=>card321(x,i+1)).join('')||'<div class=\"empty\">Sem séries elegíveis neste streaming.</div>')+'</div></section><section class=\"panel ct288-top-section\"><div class=\"panel-head\"><h2>Top 10 Filmes</h2><small>'+movies.length+'</small></div><div class=\"ct319-top-row\">'+(movies.map((x,i)=>card321(x,i+1)).join('')||'<div class=\"empty\">Sem filmes elegíveis neste streaming.</div>')+'</div></section>';\n  loaded321();document.documentElement.dataset.ct498Top10=String(series.length)+':'+String(movies.length);return true\n }catch(e){content.innerHTML='<div class=\"empty\">'+esc(e?.message||'Não foi possível carregar o Top 10 agora.')+'</div>';loaded321();return false}\n}",'r321');
js=js.replace(/const REVISION='[^']+';/,"const REVISION='r498-official-0.3.25';");
js=js.replace(/CineTracker • v[^•<]+ • \$\{REVISION\}/g,'CineTracker • v0.3.25 • ${REVISION}');
js+='\nwindow.__ctR498Marker="home-authority-id+movies-strict-2x3+foryou-alias-safe+top10-single-final-paint";\nwindow.__ctR498={version:"0.3.25",scope:"home+discover-foryou+discover-top10"};\n';
html=html.replaceAll('app-v497.js?ct=r497-official-0.3.24','app-v498.js?ct=r498-official-0.3.25').replaceAll('app-v497.css?ct=r497-official-0.3.24','app-v498.css?ct=r498-official-0.3.25').replaceAll('r497-official-0.3.24','r498-official-0.3.25');
css+='\n/* CineTracker Web 0.3.25 r498 — only Home + Pra Você + Top 10. */\n'+
'html body [data-home-view="movies"] .ct388-movie-stack.ct489-movie-grid,html body [data-home-view="movies"] .ct388-movie-stack.ct492-movie-grid{display:grid!important;grid-template-columns:repeat(auto-fill,minmax(132px,150px))!important;grid-auto-flow:row!important;gap:14px!important;align-items:start!important;width:100%!important;overflow:visible!important}\n'+
'html body [data-home-view="movies"] .ct489-movie-card{position:relative!important;display:block!important;width:150px!important;min-width:132px!important;max-width:150px!important;height:auto!important;min-height:0!important;aspect-ratio:2/3!important;padding:0!important;overflow:hidden!important;border-radius:12px!important}\n'+
'html body [data-home-view="movies"] .ct489-movie-card>.ct489-movie-open{position:absolute!important;inset:0!important;display:block!important;width:100%!important;height:100%!important;min-height:0!important;padding:0!important;border:0!important;background:transparent!important;color:inherit!important;text-align:left!important}\n'+
'html body [data-home-view="movies"] .ct489-movie-card .poster{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;min-height:0!important;aspect-ratio:auto!important;border-radius:0!important;background-size:cover!important;background-position:center!important;object-fit:cover!important}\n'+
'html body [data-home-view="movies"] .ct489-movie-card .card-body{position:absolute!important;z-index:2!important;left:0!important;right:0!important;bottom:0!important;width:auto!important;padding:34px 8px 8px!important;background:linear-gradient(180deg,transparent,rgba(3,10,15,.94))!important;box-sizing:border-box!important;pointer-events:none!important}\n'+
'html body [data-home-view="movies"] .ct489-movie-card .card-body b,html body [data-home-view="movies"] .ct489-movie-card .card-body small{display:block!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}\n'+
'html body [data-home-view="movies"] .ct489-movie-card>.ct279-watch-button,html body [data-home-view="movies"] .ct489-movie-card>[data-ct279-watch]{position:absolute!important;z-index:5!important;top:7px!important;right:7px!important;width:32px!important;min-width:32px!important;height:32px!important;min-height:32px!important;padding:0!important;border-radius:10px!important}.ct489-movie-card>.ct279-watch-button .ct279-watch-label{display:none!important}\n'+
'html body [data-ct321-providers]{display:flex!important;align-items:center!important;gap:8px!important;overflow-x:auto!important;overflow-y:hidden!important;padding:4px 2px 8px!important;scrollbar-width:thin!important}\n'+
'html body [data-ct321-provider]{display:flex!important;flex:0 0 auto!important;align-items:center!important;justify-content:center!important;gap:7px!important;height:42px!important;min-height:42px!important;max-height:42px!important;padding:6px 10px!important;overflow:hidden!important}\n'+
'html body [data-ct321-provider]>span,html body [data-ct321-provider]>span>img{display:block!important;width:70px!important;height:28px!important;max-width:70px!important;max-height:28px!important;object-fit:contain!important;overflow:hidden!important}\n'+
'html body [data-ct321-provider]>b{display:block!important;max-width:120px!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important;font-size:12px!important}\n'+
'html body [data-ct321-top-content] .ct319-top-row>.ct319-item .ct288-poster,html body [data-ct321-top-content] .ct319-top-row>.ct319-item .poster{aspect-ratio:2/3!important;height:auto!important;min-height:0!important;max-height:none!important;background-size:cover!important;background-position:center!important;overflow:hidden!important}\n'+
'@media(max-width:720px){html body [data-home-view="movies"] .ct388-movie-stack.ct489-movie-grid,html body [data-home-view="movies"] .ct388-movie-stack.ct492-movie-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:10px!important}html body [data-home-view="movies"] .ct489-movie-card{width:100%!important;min-width:0!important;max-width:none!important}}\n';
sw=sw.replaceAll('ct-media-r497','ct-media-r498').replaceAll('app-v497.js','app-v498.js').replaceAll('app-v497.css','app-v498.css');
const release=JSON.parse(releaseRaw);Object.assign(release,{version:'0.3.25',revision:'r498-official-0.3.25',base:'r497-stable-modern-blue',scope:'home-series-movies+discover-foryou+discover-top10-only',home_series:'retain authoritative negative/special IDs such as Formula 1; v492 buckets are not reclassified client-side; false load-more is suppressed',home_movies:'v405 pagination preserved; native ct489 cards receive complete strict 2:3 geometry without re-enabling retired r489 runtime',discover_foryou:'v498 excludes fresh candidates by normalized title/original-title aliases in addition to exact identity',top10:'TMDB pages 1 and 2 are fetched together and filtered before one final paint; provider logos are constrained',profile:'unchanged from r497',f1:'unchanged except correct Home visibility',sports:'unchanged',history:'unchanged',android:'unchanged-1.0.20/10062'});
new Function(js);
await Promise.all([writeFile(resolve(dist,'app-v498.js'),js),writeFile(resolve(dist,'app-v498.css'),css),writeFile(resolve(dist,'index.html'),html),writeFile(resolve(dist,'service-worker.js'),sw),writeFile(resolve(dist,'release.json'),JSON.stringify(release,null,2))]);
await Promise.all([rm(resolve(dist,'app-v497.js'),{force:true}),rm(resolve(dist,'app-v497.css'),{force:true})]);
for(const need of ['window.__ctR498Marker="home-authority-id+movies-strict-2x3+foryou-alias-safe+top10-single-final-paint"','cinetracker_foryou_payload_v498',"media>0?'media:'+media:(tmdb!==0?'tmdb:'+tmdb:'')","tmdbPage321('/discover/movie',{...common,page:2},'movie')"])if(!js.includes(need))throw new Error('r498 missing '+need);
console.log('WEB_R498_READY scoped fixes');
