import {readFile,writeFile,rm} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
await import('./build-r293-official.mjs');
const root=dirname(fileURLToPath(import.meta.url)),dist=resolve(root,'dist');
let [html,js,css,sw,releaseRaw,patch]=await Promise.all([readFile(resolve(dist,'index.html'),'utf8'),readFile(resolve(dist,'app-v293.js'),'utf8'),readFile(resolve(dist,'app-v293.css'),'utf8'),readFile(resolve(dist,'service-worker.js'),'utf8'),readFile(resolve(dist,'release.json'),'utf8'),readFile(resolve(root,'runtime-r294-discover-density-scroll-order.js'),'utf8')]);
const once=(s,a,b,l)=>{const i=s.indexOf(a);if(i<0)throw new Error('r294 missing '+l);if(s.indexOf(a,i+a.length)>=0)throw new Error('r294 ambiguous '+l);return s.slice(0,i)+b+s.slice(i+a.length)},must=(s,x)=>{if(!s.includes(x))throw new Error('r294 missing '+x)};
for(const x of["window.__ctR294='discover-density-scroll-order-top10-ten-up';","window.__ctR294Cards='158x237-desktop-154x231-mobile';","window.__ctR294Top10='ten-up-at-1920-reference';","window.__ctR294Actions='content-then-actions-then-scrollbar';","--ct-media-card-w:158px!important","--ct-media-poster-h:237px!important","--ct-media-copy-h:52px!important","--ct-discover-gap:8px","--ct-discover-scroll-pad:6px","overflow:hidden!important"])must(patch,x);
for(const x of["window.__ctR291='discover-actions-favorites-horizontal-scroll'","window.__ctR292='related-actions-foryou-authority-compact-cards'","window.__ctR293='discover-navigation-foryou-actions-authority'"])must(js,x);
js=once(js,"window.__ctWebBuild='1.0.84';window.__ctOfficialVersion='1.0.84';","window.__ctWebBuild='1.0.85';window.__ctOfficialVersion='1.0.85';",'version');
js=once(js,"const REVISION='r293-official-1.0.84';","const REVISION='r294-official-1.0.85';",'revision');
js=once(js,'\nboot();','\n'+patch+'\nboot();','runtime insertion');
css+=String.raw`\n/* CineTracker Web 1.0.85 r294 — compact Discover density, ten-up Top 10 and action-before-scrollbar ordering. */\nhtml,body,#app{max-width:100%;overflow-x:hidden}\n`;
html=html.replaceAll('app-v293.js','app-v294.js').replaceAll('app-v293.css','app-v294.css').replaceAll('CineTracker • v1.0.84','CineTracker • v1.0.85');
sw=sw.replaceAll('ct-web-1.0.84-r293','ct-web-1.0.85-r294').replaceAll('app-v293.js','app-v294.js').replaceAll('app-v293.css','app-v294.css');
const prev=JSON.parse(releaseRaw),release={...prev,version:'1.0.85',revision:'r294-official-1.0.85',base:'r293-production',scope:'discover-compact-density-top10-ten-up-scroll-order-web-only',discover_card_geometry:'158x237-desktop-154x231-mobile',discover_top10:'ten-up-at-1920-reference',discover_vertical_density:'compact-copy-footer-scrollbar',discover_action_order:'content-actions-scrollbar',discover_gap:'8px',discover_scroll_padding:'6px',android:'1.0.20/10062'};
await Promise.all([writeFile(resolve(dist,'app-v294.js'),js,'utf8'),writeFile(resolve(dist,'app-v294.css'),css,'utf8'),writeFile(resolve(dist,'index.html'),html,'utf8'),writeFile(resolve(dist,'service-worker.js'),sw,'utf8'),writeFile(resolve(dist,'release.json'),JSON.stringify(release,null,2),'utf8')]);
await Promise.all([rm(resolve(dist,'app-v293.js'),{force:true}),rm(resolve(dist,'app-v293.css'),{force:true})]);
console.log('WEB_R294_READY compact Discover density + ten-up Top 10 + actions above scrollbar; Android preserved');
