import {readFile,writeFile,rm} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
await import('./build-r294-official.mjs');
const root=dirname(fileURLToPath(import.meta.url)),dist=resolve(root,'dist');
let [html,js,css,sw,releaseRaw,patch]=await Promise.all([readFile(resolve(dist,'index.html'),'utf8'),readFile(resolve(dist,'app-v294.js'),'utf8'),readFile(resolve(dist,'app-v294.css'),'utf8'),readFile(resolve(dist,'service-worker.js'),'utf8'),readFile(resolve(dist,'release.json'),'utf8'),readFile(resolve(root,'runtime-r295-discover-personal-calendar-daily.js'),'utf8')]);
const once=(s,a,b,l)=>{const i=s.indexOf(a);if(i<0)throw new Error('r295 missing '+l);if(s.indexOf(a,i+a.length)>=0)throw new Error('r295 ambiguous '+l);return s.slice(0,i)+b+s.slice(i+a.length)},must=(s,x)=>{if(!s.includes(x))throw new Error('r295 missing '+x)};
for(const x of["window.__ctR295='discover-personal-authority-calendar-daily-actions';","window.__ctR295Personal='recommendation+profile+list-snapshot-union';","window.__ctR295Browse='seen-watchlist-excluded+playlist-seen-actions';","window.__ctR295Calendar='all-movie-tv-axis+independent-watchlist-toggle';","window.__ctR295ForYou='canonical-unwatched-unwatchlisted+daily-fresh-pick-no-blur';","cinetracker_profile_media_dashboard_v0997_fast","cinetracker_list_snapshot_v247","data-ct295-calendar-type","data-ct295-calendar-watch","data-ct295-seen","markSeen(type,id)","addWatchlist(type,id)"])must(patch,x);
for(const x of["window.__ctR293='discover-navigation-foryou-actions-authority'","window.__ctR294='discover-density-scroll-order-top10-ten-up'"])must(js,x);
js=once(js,"window.__ctWebBuild='1.0.85';window.__ctOfficialVersion='1.0.85';","window.__ctWebBuild='1.0.86';window.__ctOfficialVersion='1.0.86';",'version');
js=once(js,"const REVISION='r294-official-1.0.85';","const REVISION='r295-official-1.0.86';",'revision');
js=once(js,'\nboot();','\n'+patch+'\nboot();','runtime insertion');
css+=String.raw`\n/* CineTracker Web 1.0.86 r295 — canonical Discover exclusions, combinable calendar filters and crisp daily recommendation. */\nhtml,body,#app{max-width:100%;overflow-x:hidden}\n`;
html=html.replaceAll('app-v294.js','app-v295.js').replaceAll('app-v294.css','app-v295.css').replaceAll('CineTracker • v1.0.85','CineTracker • v1.0.86');
sw=sw.replaceAll('ct-web-1.0.85-r294','ct-web-1.0.86-r295').replaceAll('app-v294.js','app-v295.js').replaceAll('app-v294.css','app-v295.css');
const prev=JSON.parse(releaseRaw),release={...prev,version:'1.0.86',revision:'r295-official-1.0.86',base:'r294-production',scope:'discover-personal-exclusions-calendar-combinable-daily-recommendation-web-only',discover_personal_authority:'recommendation+profile+list-snapshot-union',discover_browse_exclusions:'seen+watchlist',discover_browse_actions:'playlist+seen',discover_calendar_filters:'all-movie-tv-axis+independent-watchlist-toggle',discover_calendar_combination:'series+watchlist-supported',discover_foryou_fresh:'canonical-never-seen-never-watchlisted',discover_daily_pick:'fresh-pool-only+no-blur',android:'1.0.20/10062'};
await Promise.all([writeFile(resolve(dist,'app-v295.js'),js,'utf8'),writeFile(resolve(dist,'app-v295.css'),css,'utf8'),writeFile(resolve(dist,'index.html'),html,'utf8'),writeFile(resolve(dist,'service-worker.js'),sw,'utf8'),writeFile(resolve(dist,'release.json'),JSON.stringify(release,null,2),'utf8')]);
await Promise.all([rm(resolve(dist,'app-v294.js'),{force:true}),rm(resolve(dist,'app-v294.css'),{force:true})]);
console.log('WEB_R295_READY canonical Discover exclusions + combinable calendar + crisp daily recommendation; Android preserved');
