import {readFile,writeFile,rm} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=dirname(fileURLToPath(import.meta.url));
await import('./build-r162.mjs');
const dist=resolve(root,'dist');
let js=await readFile(resolve(dist,'app-v162.js'),'utf8');
let css=await readFile(resolve(dist,'app-v162.css'),'utf8');
let html=await readFile(resolve(dist,'index.html'),'utf8');
let sw=await readFile(resolve(dist,'service-worker.js'),'utf8');

const patch=String.raw`
/* r163: instant preloading + stable async UI + discover carousels + sports historical search */
window.__ctR163='instant-preload-stable-ui';
window.__ct163Preload='home+discover+profile+sports';
window.__ct163SportsHistory='extended-date-range';
window.__ct163Watchlist='foryou-watchlist3';

const CT163_CACHE='cinetracker:preload:r163:';
function ct163Read(k){try{const v=JSON.parse(localStorage.getItem(CT163_CACHE+k)||'null');if(v&&Date.now()-Number(v.at||0)<1000*60*60*24*7)return v.data}catch{}return null}
function ct163Write(k,v){try{localStorage.setItem(CT163_CACHE+k,JSON.stringify({at:Date.now(),data:v}))}catch{}}
function ct163PaintCached(routeName){try{if(routeName==='home'){const v=ct163Read('home');if(v){homeCache=v;paintHome();return true}}if(routeName==='profile'){const v=ct163Read('profile');if(v){profileCache=v;paintProfile163(v);return true}}if(routeName==='discover'){const v=ct163Read('discover:'+discoverState.tab+':'+discoverState.type);if(v){paintDiscover(v);return true}}if(routeName==='sports'){const v=ct163Read('sports');if(v){sportsCache=v;paintSports(v);return true}}}catch{}return false}

function paintProfile163(d){const h=$('[data-profile]');if(!h)return;const r=profileRows(d||{}),s=d?.stats||{},ss=d?.series_stats||{},rem=d?.remaining||{},days=d?.activity||[],max=Math.max(1,...days.map(x=>Number(x.count||0)));h.innerHTML='<section class="panel"><div class="panel-head"><h2>Estatísticas</h2><small>pré-carregado</small></div><div class="stats">'+[['Tempo total',fmtMinutes(s.total_minutes)],['Episódios vistos',Number(s.episodes_watched||0).toLocaleString('pt-BR')],['Filmes vistos',Number(s.movies_watched||0).toLocaleString('pt-BR')],['Séries concluídas',Number(ss.completed_series||0).toLocaleString('pt-BR')],['Em andamento',Number(ss.in_progress_series||0).toLocaleString('pt-BR')]].map(([a,b])=>'<div class="stat"><small>'+a+'</small><b>'+b+'</b></div>').join('')+'</div></section>'+profileSection('Séries',r.series)+profileSection('Filmes',r.movies)+profileSection('Séries Favoritas',r.seriesFav)+profileSection('Filmes Favoritos',r.movieFav)+'<section class="panel"><div class="panel-head"><h2>Atores Favoritos</h2><small>'+((d.favorite_actors||[]).length)+'</small></div><div class="row">'+((d.favorite_actors||[]).slice(0,10).map(a=>'<article class="card"><button type="button" data-person="'+Number(a.tmdb_person_id||0)+'"><div class="poster"'+(a.profile_path?' style="background-image:url(\''+img(a.profile_path,'w185')+'\')"':'')+'></div><div class="card-body"><b>'+esc(a.actor_name||'Ator')+'</b><small>Ator favorito</small></div></button></article>').join('')||'<div class="empty">Nenhum ator favorito.</div>')+'</div></section><section class="panel"><div class="panel-head"><h2>Episódios por dia</h2><small>'+tz()+'</small></div><div class="timeline">'+days.map(x=>{const n=Number(x.count||0),today=String(x.day).slice(0,10)===localDay();return '<div class="day '+(today?'today':'')+'"><b>'+n+'</b><div class="barwrap"><div class="bar" style="height:'+Math.max(4,Math.round(n/max*96))+'px"></div></div><small>'+(today?'Hoje':new Date(String(x.day).slice(0,10)+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit'}))+'</small></div>'}).join('')+'</div></section><section class="panel"><div class="panel-head"><h2>Biblioteca</h2><small>pré-carregada</small></div><div class="stats">'+[['Séries Watchlist',rem.watchlist_series??ss.not_started_series],['Filmes Watchlist',rem.watchlist_movies??ss.watchlist_movies],['Em dia',ss.up_to_date_series],['Tempo séries',fmtMinutes(s.series_minutes)],['Tempo filmes',fmtMinutes(s.movie_minutes)]].map(([a,b])=>'<div class="stat"><small>'+a+'</small><b>'+(typeof b==='string'?b:Number(b||0).toLocaleString('pt-BR'))+'</b></div>').join('')+'</div></section>'}

const ct163HomeRender=renderHome;renderHome=async function(seq){const has=ct163Read('home');const p=ct163HomeRender(seq);if(has&&seq===navSeq&&route()==='home'){homeCache=has;paintHome()}try{await p;if(homeCache)ct163Write('home',homeCache)}catch{}};
const ct163ProfileRender=renderProfile;renderProfile=async function(seq){const has=ct163Read('profile');const p=ct163ProfileRender(seq);if(has&&seq===navSeq&&route()==='profile'){profileCache=has;paintProfile163(has)}try{await p;if(profileCache)ct163Write('profile',profileCache);ct163Decorate()}catch{}};
const ct163DiscoverRender=renderDiscover;renderDiscover=async function(seq){const has=ct163Read('discover:'+discoverState.tab+':'+discoverState.type);const p=ct163DiscoverRender(seq);if(has&&seq===navSeq&&route()==='discover')paintDiscover(has);try{await p;const rows=discoverCache.get(discoverState.tab+':'+localDay());if(rows)ct163Write('discover:'+discoverState.tab+':all',rows)}catch{}};
const ct163SportsRender=renderSports;renderSports=async function(seq){const has=ct163Read('sports');const p=ct163SportsRender(seq);if(has&&seq===navSeq&&route()==='sports'){sportsCache=has;paintSports(has)}try{await p;if(sportsCache)ct163Write('sports',sportsCache)}catch{}};

const ct163DiscoverRows=discoverRows;discoverRows=async function(tab){const v=await ct163DiscoverRows(tab);ct163Write('discover:'+tab+':all',v);return v};
const ct163SportsPayloadWide=async function(force=false){if(!force&&sportsCache)return sportsCache;const from=new Date(shiftDays(-30)+'T00:00:00'),to=new Date(shiftDays(14)+'T23:59:59');sportsCache=await rpc('cinetracker_sports_payload_v1',{p_from:from.toISOString(),p_to:to.toISOString()});if(sportsCache)ct163Write('sports',sportsCache);return sportsCache||{sports:[],events:[],favorites:[],preferences:{}}};
sportsPayload=ct163SportsPayloadWide;

let ct163PreloadStarted=false;async function ct163PreloadAll(){if(ct163PreloadStarted||!session)return;ct163PreloadStarted=true;const jobs=[rpc('cinetracker_home_live_v0997_r3',{p_today:localDay()}).then(v=>ct163Write('home',v)).catch(()=>{}),rpc('cinetracker_profile_payload_v0997',{p_tz:tz()}).then(v=>ct163Write('profile',v)).catch(()=>{}),discoverRows('foryou').then(v=>ct163Write('discover:foryou:all',v)).catch(()=>{}),sportsPayload(false).then(v=>ct163Write('sports',v)).catch(()=>{})];for(const t of ['trending','popular','new','anticipated','top','calendar'])jobs.push(discoverRows(t).then(v=>ct163Write('discover:'+t+':all',v)).catch(()=>{}));void Promise.allSettled(jobs)}
function ct163WarmOnIdle(){if(!session)return;const run=()=>void ct163PreloadAll();if('requestIdleCallback'in window)requestIdleCallback(run,{timeout:900});else setTimeout(run,350)}
const ct163Boot=boot;boot=async function(){await ct163Boot();ct163WarmOnIdle()};
let ct163FocusTimer=0;document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&session){clearTimeout(ct163FocusTimer);ct163FocusTimer=setTimeout(()=>{ct163PreloadStarted=false;ct163WarmOnIdle();void render()},250)}});window.addEventListener('pageshow',()=>{if(session)ct163WarmOnIdle()});

const ct163Style=document.createElement('style');ct163Style.textContent=String.raw`
[data-page="configs"] .panel{min-width:0;overflow:hidden}[data-page="configs"] .panel-head{min-width:0;flex-wrap:wrap}[data-page="configs"] .panel-head h2,[data-page="configs"] .panel-head small{min-width:0;overflow-wrap:anywhere}[data-page="configs"] .form-grid,[data-page="configs"] .settings-grid{min-width:0}[data-page="configs"] .field{min-width:0}[data-page="configs"] .field input,[data-page="configs"] .field select{max-width:100%;min-width:0}
[data-page="discover"] .tabs,[data-page="discover"] .filters,[data-page="sports"] .tabs,[data-page="sports"] .filters{display:flex;flex-wrap:nowrap;overflow-x:auto;overflow-y:hidden;white-space:nowrap;scroll-snap-type:x proximity;-webkit-overflow-scrolling:touch;scrollbar-width:thin;padding-bottom:7px;max-width:100%}[data-page="discover"] .tabs>* ,[data-page="discover"] .filters>* ,[data-page="sports"] .tabs>* ,[data-page="sports"] .filters>*{flex:0 0 auto;scroll-snap-align:start}
[data-page="discover"] [data-discover-content]>.page>.panel-head,[data-page="discover"] [data-discover-content]>.panel-head{min-width:0}[data-page="discover"] .row,[data-page="discover"] .foryou-grid,[data-page="profile"] .panel .row{display:flex;flex-wrap:nowrap;overflow-x:auto;gap:10px;padding-bottom:8px;-webkit-overflow-scrolling:touch}[data-page="discover"] .row>.card,[data-page="discover"] .foryou-grid>*,[data-page="profile"] .panel .row>.card{flex:0 0 150px}
.section-more{display:inline-flex!important;margin-left:auto}
`;document.head.appendChild(ct163Style);
function ct163MoreButton(label,action){return '<button type="button" class="btn btn-secondary section-more" data-ct-more="'+esc(action)+'">Ver mais '+esc(label)+'</button>'}
document.addEventListener('click',e=>{const b=e.target.closest('[data-ct-more]');if(!b)return;const action=b.dataset.ctMore;if(action.startsWith('discover:')){discoverState.tab=action.slice(9);discoverState.type='all';void render();return}});
function ct163Decorate(){if(route()==='discover'){document.querySelectorAll('[data-discover-content] .panel-head').forEach(h=>{if(h.querySelector('.section-more'))return;const txt=h.querySelector('h2')?.textContent||'';const map={'Indicação do dia':'foryou','Da sua Watchlist':'foryou','100% novos':'new','Em alta':'trending','Populares':'popular','Novidades':'new','Mais Aguardados':'anticipated','Mais bem avaliados':'top','Calendário':'calendar'};if(map[txt])h.appendChild(ct163MoreButton(txt,'discover:'+map[txt]))})}if(route()==='profile'){document.querySelectorAll('[data-profile] .panel-head').forEach(h=>{if(h.querySelector('.section-more'))return;const txt=h.querySelector('h2')?.textContent||'';if(['Séries','Filmes','Séries Favoritas','Filmes Favoritos','Atores Favoritos'].includes(txt))h.appendChild(ct163MoreButton(txt,'profile:'+norm(txt)))})}}
const ct163PaintDiscover=paintDiscover;paintDiscover=function(rows){ct163PaintDiscover(rows);ct163Decorate()};

sportsState.date=localDay();sportsState.query='';
function ct163SportSearch(q,p){const n=norm(q);if(!n)return [];return (p.events||[]).filter(e=>[e.title,e.home_name,e.away_name,e.competition_name].some(v=>norm(v).includes(n)))}
const ct163PaintSportsBase=paintSports;paintSports=function(p=sportsCache||{}){ct163PaintSportsBase(p);const root=$('[data-sports]');if(!root)return;let tools=root.querySelector('[data-sports-tools]');if(!tools){tools=document.createElement('div');tools.dataset.sportsTools='1';tools.className='panel sports-tools';tools.innerHTML='<div class="search"><span>⌕</span><input type="search" data-sports-search placeholder="Buscar time, jogo ou competição..." autocomplete="off"><input type="date" data-sports-date title="Escolher data"></div>';const first=root.firstElementChild;root.insertBefore(tools,first||null)}const date=tools.querySelector('[data-sports-date]');if(date)date.value=sportsState.date||localDay();const q=tools.querySelector('[data-sports-search]');if(q&&sportsState.query&&q.value!==sportsState.query)q.value=sportsState.query;const grid=root.querySelector('.event-grid');if(grid&&sportsState.query){const rows=ct163SportSearch(sportsState.query,p);grid.innerHTML=rows.map(e=>sportsEvent(e,p)).join('')||'<div class="empty">Nenhum jogo encontrado no período sincronizado.</div>';const head=grid.parentElement?.querySelector('.panel-head h2');if(head)head.textContent='Resultados esportivos'}};
document.addEventListener('input',e=>{if(e.target.matches('[data-sports-search]')){sportsState.query=e.target.value.trim();paintSports()}});document.addEventListener('change',e=>{if(e.target.matches('[data-sports-date]')){sportsState.date=e.target.value||localDay();sportsState.tab='calendar';sportsState.query='';paintSports()}});
const ct163SportsFiltered= sportsFiltered;sportsFiltered=function(p){if(sportsState.tab==='calendar'){let a=(p.events||[]).filter(x=>new Date(x.starts_at).toLocaleDateString('sv-SE')===(sportsState.date||localDay()));if(sportsState.sport!=='all')a=a.filter(x=>x.sport_slug===sportsState.sport);return a}return ct163SportsFiltered(p)};
const ct163OldSportsSync=syncSports;syncSports=async function(force){await ct163OldSportsSync(force);if(route()==='sports'){ct163Write('sports',sportsCache);void ct163EnsureSportsHistory163()}};
function ct163EnsureSportsHistory163(){return edge('ct-sports-sync',{action:'sync',date_from:shiftDays(-30),date_to:localDay(),sports:['soccer','basketball','american_football','ice_hockey','baseball','tennis','volleyball','handball','rugby','motogp','formula_1','mma'],force:false},90000).then(()=>sportsPayload(true)).catch(()=>sportsCache)}

const ct163Go=go;go=function(path,replace=false){const dest=path.startsWith('/')?path:pathFor(path);if(location.pathname!==dest)history[replace?'replaceState':'pushState']({},'',dest);ct163PaintCached(route());return void render()};
`;
js=js.replace('boot();',patch+'\nboot();').replaceAll('r162-home-discover-sports','r163-instant-preload-stable-ui').replaceAll('app-v162.js','app-v163.js').replaceAll('app-v162.css','app-v163.css');
css += '\n/* r163 overflow-safe settings and horizontal carousels */\n.settings-grid,.form-grid{min-width:0}.panel,.field{min-width:0}.field input,.field select{max-width:100%;min-width:0}\n';
html=html.replaceAll('r162-home-discover-sports','r163-instant-preload-stable-ui').replaceAll('app-v162.js','app-v163.js').replaceAll('app-v162.css','app-v163.css');
sw=sw.replaceAll('r162-home-discover-sports','r163-instant-preload-stable-ui').replaceAll('app-v162.js','app-v163.js').replaceAll('app-v162.css','app-v163.css');
await writeFile(resolve(dist,'app-v163.js'),js,'utf8');
await writeFile(resolve(dist,'app-v163.css'),css,'utf8');
await writeFile(resolve(dist,'index.html'),html,'utf8');
await writeFile(resolve(dist,'service-worker.js'),sw,'utf8');
await rm(resolve(dist,'app-v162.js'),{force:true});await rm(resolve(dist,'app-v162.css'),{force:true});
await writeFile(resolve(dist,'release.json'),JSON.stringify({version:'0.99.7',revision:'r163-instant-preload-stable-ui',runtime:'single-clean-runtime',generated_at:new Date().toISOString()}),'utf8');
console.log('WEB_R163_READY preload=all-main-tabs discover=horizontal+more sports=history-search configs=overflow-safe');
