import {readFile,writeFile,rm} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
await import('./build-r298-official.mjs');
const root=dirname(fileURLToPath(import.meta.url)),dist=resolve(root,'dist');
let [html,js,css,sw,releaseRaw,runtime]=await Promise.all([
 readFile(resolve(dist,'index.html'),'utf8'),readFile(resolve(dist,'app-v298.js'),'utf8'),readFile(resolve(dist,'app-v298.css'),'utf8'),readFile(resolve(dist,'service-worker.js'),'utf8'),readFile(resolve(dist,'release.json'),'utf8'),readFile(resolve(root,'runtime-r299-profile-sports-history.js'),'utf8')
]);
const must=(s,x)=>{if(!s.includes(x))throw new Error('r299 missing '+x)};
for(const x of["window.__ctWebBuild='1.0.89';window.__ctOfficialVersion='1.0.89';","const REVISION='r298-official-1.0.89';","window.__ctR298='stadium-real-controls+exact-foryou-live-pipeline'",'buildForYou298'])must(js,x);
for(const x of["window.__ctR299='profile-sports-history-clickable+stadium-presence-only'","window.__ctR299Profile='eventos-assistidos+jogos-no-estadio-clickable-history'","window.__ctR299Sports='tv-or-stadium-no-stadium-name'",'data-ct299-choice="stadium"','data-ct299-history','cinetracker_sports_watch_history_v296','p_stadium_name:null'])must(runtime,x);
const marker='/* CineTracker Web 1.0.89 r298 — stadium flow + exact Pra Você completion. WEB ONLY. */';
if(!js.includes(marker))throw new Error('r299 cannot register before r298 sports capture');
js=js.replace(marker,runtime+'\n'+marker)
 .replace("window.__ctWebBuild='1.0.89';window.__ctOfficialVersion='1.0.89';","window.__ctWebBuild='1.0.90';window.__ctOfficialVersion='1.0.90';")
 .replace("const REVISION='r298-official-1.0.89';","const REVISION='r299-official-1.0.90';");
css+=String.raw`
/* CineTracker Web 1.0.90 r299 — clickable sports history + stadium presence only. */
.ct299-clickable-stat{cursor:pointer;transition:border-color .15s ease,background .15s ease,transform .15s ease}.ct299-clickable-stat:hover,.ct299-clickable-stat:focus-visible{border-color:rgba(92,190,226,.58)!important;background:rgba(34,112,143,.16)!important;outline:none}.ct299-clickable-stat:active{transform:translateY(1px)}
.ct299-watch-popover{position:relative;display:grid;gap:7px;margin-top:8px;padding:10px;border:1px solid rgba(225,173,63,.55);border-radius:12px;background:rgba(16,27,32,.97);box-shadow:0 12px 30px rgba(0,0,0,.32);z-index:13}.ct299-watch-popover>button{border:1px solid #3a677e;background:#0b2b3d;color:#eaf7fd;border-radius:9px;padding:9px 10px;cursor:pointer;text-align:left}.ct299-pop-close{position:absolute;right:7px;top:7px;width:28px!important;height:28px!important;padding:0!important;text-align:center!important}.ct298-stadium-form,input[data-ct298-stadium]{display:none!important}
.ct299-history-backdrop{position:fixed;inset:0;z-index:10020;display:grid;place-items:center;padding:18px;background:rgba(0,0,0,.72);backdrop-filter:blur(5px)}.ct299-history-modal{width:min(720px,100%);max-height:min(78vh,760px);display:grid;grid-template-rows:auto minmax(0,1fr);overflow:hidden;border:1px solid rgba(111,190,222,.34);border-radius:18px;background:#0a1720;color:#edf8fc;box-shadow:0 24px 70px rgba(0,0,0,.5)}.ct299-history-modal>header{display:flex;justify-content:space-between;gap:16px;padding:18px 18px 14px;border-bottom:1px solid rgba(255,255,255,.08)}.ct299-history-modal>header small{color:#78b5cf;font-size:11px;font-weight:800;text-transform:uppercase;letter-spacing:.08em}.ct299-history-modal h2{margin:3px 0 4px;font-size:20px}.ct299-history-modal p{margin:0;color:#9fbbc7;font-size:12px}.ct299-history-modal [data-ct299-history-close]{flex:0 0 36px;width:36px;height:36px;border:1px solid rgba(255,255,255,.15);border-radius:10px;background:#102733;color:#fff;font-size:22px;cursor:pointer}.ct299-history-list{overflow-y:auto;padding:10px 12px 14px}.ct299-history-row{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:12px 10px;border-bottom:1px solid rgba(255,255,255,.07)}.ct299-history-row:last-child{border-bottom:0}.ct299-history-row>div{min-width:0;display:grid;gap:4px}.ct299-history-row b{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:13px}.ct299-history-row span{color:#94b2bf;font-size:11px}.ct299-history-row>small{flex:0 0 auto;padding:4px 8px;border:1px solid rgba(222,172,52,.42);border-radius:999px;background:rgba(120,84,12,.18);color:#efca61;font-size:10px;font-weight:800}.ct299-history-loading,.ct299-history-empty{padding:28px 14px;text-align:center;color:#9fbbc7;font-size:12px}
@media(max-width:640px){.ct299-history-backdrop{padding:10px}.ct299-history-modal{max-height:84vh;border-radius:15px}.ct299-history-modal>header{padding:15px 14px 12px}.ct299-history-row{align-items:flex-start;flex-direction:column;gap:7px}.ct299-history-row b{white-space:normal}}
`;
html=html.replaceAll('app-v298.js','app-v299.js').replaceAll('app-v298.css','app-v299.css').replaceAll('CineTracker • v1.0.89','CineTracker • v1.0.90');
sw=sw.replaceAll('ct-web-1.0.89-r298','ct-web-1.0.90-r299').replaceAll('app-v298.js','app-v299.js').replaceAll('app-v298.css','app-v299.css');
const prev=JSON.parse(releaseRaw),release={...prev,version:'1.0.90',revision:'r299-official-1.0.90',base:'r298-production',scope:'profile-sports-history-clickable-stadium-presence-only-web',sports_stadium_ui:'tv-or-stadium-no-name-input',sports_stadium_name_capture:false,profile_sports_history:'eventos-assistidos+jogos-no-estadio-clickable',profile_stadium_metric:'inside-esportes-assistidos-clickable',android:'1.0.20/10062'};
await Promise.all([writeFile(resolve(dist,'app-v299.js'),js),writeFile(resolve(dist,'app-v299.css'),css),writeFile(resolve(dist,'index.html'),html),writeFile(resolve(dist,'service-worker.js'),sw),writeFile(resolve(dist,'release.json'),JSON.stringify(release,null,2))]);
await Promise.all([rm(resolve(dist,'app-v298.js'),{force:true}),rm(resolve(dist,'app-v298.css'),{force:true})]);
console.log('WEB_R299_READY clickable Sports profile history + stadium presence only; Android preserved');
