import fs from 'node:fs';
import { execFileSync } from 'node:child_process';
execFileSync(process.execPath,['apps/web/build-r205.mjs'],{stdio:'inherit'});
const dist='apps/web/dist';
let html=fs.readFileSync(`${dist}/index.html`,'utf8');
let js=fs.readFileSync(`${dist}/app-v205.js`,'utf8');
let sw=fs.readFileSync(`${dist}/service-worker.js`,'utf8');
const patch=fs.readFileSync('apps/web/runtime-r206-f1-rewatch-fix.js','utf8');
js += `\n;${patch}\n;window.__ctOfficialVersion='1.0.2';window.__ctOfficialRevision='r206-official-1.0.2';window.__ctRelease102='functional-rewatch-plus-f1-sports-hub-web-android';\n`;
html=html.replaceAll('app-v205.js','app-v206.js').replaceAll('r205-official-1.0.1','r206-official-1.0.2');
sw=sw.replaceAll('app-v205.js','app-v206.js').replaceAll('r205-official-1.0.1','r206-official-1.0.2');
fs.writeFileSync(`${dist}/app-v206.js`,js);
fs.writeFileSync(`${dist}/index.html`,html);
fs.writeFileSync(`${dist}/service-worker.js`,sw);
fs.writeFileSync(`${dist}/release.json`,JSON.stringify({version:'1.0.2',revision:'r206-official-1.0.2',scope:'functional-rewatch-plus-f1-sports-hub-web-android',generatedAt:new Date().toISOString()},null,2));
console.log('WEB_1_0_2_READY revision=r206-official-1.0.2');