import {readFile,writeFile,rm} from 'node:fs/promises';import {resolve,dirname} from 'node:path';import {fileURLToPath} from 'node:url';
await import('./build-r368.mjs');
const root=dirname(fileURLToPath(import.meta.url)),dist=resolve(root,'dist');
let [html,js,css,sw,releaseRaw,runtime]=await Promise.all([readFile(resolve(dist,'index.html'),'utf8'),readFile(resolve(dist,'app-v368.js'),'utf8'),readFile(resolve(dist,'app-v368.css'),'utf8'),readFile(resolve(dist,'service-worker.js'),'utf8'),readFile(resolve(dist,'release.json'),'utf8'),readFile(resolve(root,'runtime-r369-hard-no-refresh-bounded-swap.js'),'utf8')]);
const once=(s,a,b,l)=>{const n=s.split(a).length-1;if(n!==1)throw new Error('r369 expected one '+l+', found '+n);return s.replace(a,b)};
const maybe=(s,a,b)=>s.includes(a)?s.replace(a,b):s;

/* Core TMDB helper: externally cancellable, default behavior preserved. */
const oldTmdb="async function tmdb(path,params={}){const u=new URL(`${SUPABASE_URL}/functions/v1/tmdb-proxy`);u.searchParams.set('path',path);u.searchParams.set('language',localStorage.getItem('cinetracker_locale')==='en-US'?'en-US':'pt-BR');for(const[k,v]of Object.entries(params))if(v!==null&&v!==undefined&&v!=='')u.searchParams.set(k,String(v));const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(u,{headers:headers(),signal:c.signal});if(!r.ok)throw new Error(`TMDB ${r.status}`);return r.json()}finally{clearTimeout(t)}}";
const newTmdb="async function tmdb(path,params={},options={}){const u=new URL(`${SUPABASE_URL}/functions/v1/tmdb-proxy`);u.searchParams.set('path',path);u.searchParams.set('language',localStorage.getItem('cinetracker_locale')==='en-US'?'en-US':'pt-BR');for(const[k,v]of Object.entries(params))if(v!==null&&v!==undefined&&v!=='')u.searchParams.set(k,String(v));const c=new AbortController(),external=options?.signal,abort=()=>c.abort();if(external){if(external.aborted)c.abort();else external.addEventListener('abort',abort,{once:true})}const t=setTimeout(()=>c.abort(),Math.max(1,Number(options?.timeout||12000)));try{const r=await fetch(u,{headers:headers(),signal:c.signal});if(!r.ok)throw new Error(`TMDB ${r.status}`);return r.json()}finally{clearTimeout(t);try{external?.removeEventListener?.('abort',abort)}catch{}}}";
js=once(js,oldTmdb,newTmdb,'cancellable tmdb');

/* Retire the two Pra Voce observer storms. */
js=once(js,"setTimeout(()=>{armAll();bind();warmAll()},0);","setTimeout(()=>{armAll();warmAll()},0);",'r363 observer boot');
const r367Observer="const mo=new MutationObserver(()=>queueMicrotask(ensureAll));\nmo.observe(document.documentElement,{subtree:true,childList:true});\nfor(const ms of [0,50,200,800,1600])setTimeout(ensureAll,ms);";
js=once(js,r367Observer,"for(const ms of [0,50,200,800])setTimeout(ensureAll,ms);",'r367 global observer');

/* Remove the only blocking while loop from r368 random page selection. */
js=once(js,"function randomPages(count=4,max=40){const out=new Set();while(out.size<count)out.add(2+Math.floor(Math.random()*Math.max(1,max-1)));return[...out]}","function randomPages(count=4,max=40){const a=[];for(let p=2;p<=max;p++)a.push(p);for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1)),v=a[i];a[i]=a[j];a[j]=v}return a.slice(0,Math.max(0,Math.min(count,a.length)))}",'r368 blocking while');

/* r296: keep stadium UX, but never reload/repaint globally after watched persistence. */
const old296="async function saveSport296(e,inPerson=false,stadiumName=null,watched=true){\n await rpc('cinetracker_sports_watch_set_v296',{\n  p_provider:String(e?.provider||'unknown'),p_provider_event_id:String(e?.provider_event_id||e?.event_id||e?.id||''),\n  p_sport_slug:e?.sport_slug||null,p_competition_name:e?.competition_name||null,p_title:e?.title||[e?.home_name,e?.away_name].filter(Boolean).join(' × ')||'Evento',\n  p_starts_at:e?.starts_at||e?.start_time||e?.date||null,p_attended_in_person:!!inPerson,p_stadium_name:stadiumName||null,p_watched:!!watched,\n  p_metadata:{venue:e?.venue||null,home_name:e?.home_name||null,away_name:e?.away_name||null}\n });\n try{sport255.payload=null;sport255.at=0;await loadSports255(true);if(String(route())==='sports')paintSports255()}catch{}\n document.dispatchEvent(new CustomEvent('cinetracker:data-changed',{detail:{source:'r296-sports-watch'}}));\n}";
const new296="async function saveSport296(e,inPerson=false,stadiumName=null,watched=true){const provider=String(e?.provider||'unknown'),id=String(e?.provider_event_id||e?.event_id||e?.id||''),btn=[...document.querySelectorAll('[data-ct296-watch]')].find(b=>String(b.dataset.provider||'')===provider&&String(b.dataset.ct296Watch||'')===id)||null,old=btn?.dataset.watched==='1',next=!!watched;if(btn){btn.type='button';btn.dataset.watched=next?'1':'0';btn.classList.toggle('on',next);btn.textContent=next?'↶ Desmarcar assistido':'✓ Marcar como assistido'}try{await rpc('cinetracker_sports_watch_set_v296',{p_provider:provider,p_provider_event_id:id,p_sport_slug:e?.sport_slug||null,p_competition_name:e?.competition_name||null,p_title:e?.title||[e?.home_name,e?.away_name].filter(Boolean).join(' × ')||'Evento',p_starts_at:e?.starts_at||e?.start_time||e?.date||null,p_attended_in_person:!!inPerson,p_stadium_name:stadiumName||null,p_watched:next,p_metadata:{venue:e?.venue||null,home_name:e?.home_name||null,away_name:e?.away_name||null}});window.dispatchEvent(new CustomEvent('cinetracker:sports-watched-changed',{detail:{source:'r296',provider,id,watched:next,delta:next===old?0:(next?1:-1)}}));return true}catch(err){if(btn){btn.dataset.watched=old?'1':'0';btn.classList.toggle('on',old);btn.textContent=old?'↶ Desmarcar assistido':'✓ Marcar como assistido'}throw err}}";
js=once(js,old296,new296,'r296 safe watched');
js=maybe(js,"if(watch){e.preventDefault();e.stopPropagation();","if(watch){e.preventDefault();e.stopImmediatePropagation();e.stopPropagation();");
js=maybe(js,"if(choice){e.preventDefault();const box=choice.closest('.ct296-watch-popover')","if(choice){e.preventDefault();e.stopImmediatePropagation();e.stopPropagation();const box=choice.closest('.ct296-watch-popover')");
js=maybe(js,"if(save){e.preventDefault();const box=save.closest('.ct296-watch-popover')","if(save){e.preventDefault();e.stopImmediatePropagation();e.stopPropagation();const box=save.closest('.ct296-watch-popover')");

/* r299: remove render() and global data-changed from stadium choice. */
const old299="async function saveSport299(btn,inPerson){const d=cardData299(btn);if(!d.id)throw new Error('Evento esportivo sem identificador');btn.disabled=true;try{await rpc('cinetracker_sports_watch_set_v296',{p_provider:d.provider,p_provider_event_id:d.id,p_sport_slug:null,p_competition_name:null,p_title:d.title,p_starts_at:null,p_attended_in_person:!!inPerson,p_stadium_name:null,p_watched:true,p_metadata:{venue:d.venue}});btn.dataset.watched='1';btn.classList.add('on');btn.textContent='↶ Desmarcar assistido';if(inPerson)addGenericStadiumBadge(d.card);document.dispatchEvent(new CustomEvent('cinetracker:data-changed',{detail:{source:'r299-stadium-simple'}}));if(typeof render==='function')await render();return true}finally{btn.disabled=false;setTimeout(scrubStadiumNames,50)}}";
const new299="async function saveSport299(btn,inPerson){const d=cardData299(btn);if(!d.id)throw new Error('Evento esportivo sem identificador');const old=btn.dataset.watched==='1';btn.type='button';btn.disabled=true;btn.dataset.watched='1';btn.classList.add('on');btn.textContent='↶ Desmarcar assistido';if(inPerson)addGenericStadiumBadge(d.card);try{await rpc('cinetracker_sports_watch_set_v296',{p_provider:d.provider,p_provider_event_id:d.id,p_sport_slug:null,p_competition_name:null,p_title:d.title,p_starts_at:null,p_attended_in_person:!!inPerson,p_stadium_name:null,p_watched:true,p_metadata:{venue:d.venue}});window.dispatchEvent(new CustomEvent('cinetracker:sports-watched-changed',{detail:{source:'r299',provider:d.provider,id:d.id,watched:true,delta:old?0:1}}));return true}catch(err){btn.dataset.watched=old?'1':'0';btn.classList.toggle('on',old);btn.textContent=old?'↶ Desmarcar assistido':'✓ Marcar como assistido';throw err}finally{btn.disabled=false;setTimeout(scrubStadiumNames,50)}}";
js=once(js,old299,new299,'r299 safe watched');

/* r301 F1 calendar: optimistic local button/card only, no history reload, modal repaint or global event. */
const old301="async function toggleF1CalendarWatch301(btn){\n if(!btn||btn.disabled)return;const watched=btn.dataset.watched==='1',provider=String(btn.dataset.provider||'jolpica'),id=String(btn.dataset.eventId||'');if(!id)return;btn.disabled=true;\n try{await rpc('cinetracker_sports_watch_set_v296',{p_provider:provider,p_provider_event_id:id,p_sport_slug:'formula_1',p_competition_name:'Fórmula 1',p_title:btn.dataset.title||'Fórmula 1',p_starts_at:btn.dataset.startsAt||null,p_attended_in_person:false,p_stadium_name:null,p_watched:!watched,p_metadata:{venue:btn.dataset.venue||null,season:btn.dataset.season||null}});f1History301.at=0;try{sport255.payload=null;sport255.at=0}catch{}try{profileCache=null}catch{}await loadF1History301(true);closeF1Modal301();await decorateF1Calendar301(false);const ev=new CustomEvent('cinetracker:data-changed',{detail:{source:'r301-f1-calendar',provider,id,watched:!watched}});document.dispatchEvent(ev);try{window.dispatchEvent(new CustomEvent('cinetracker:data-changed',{detail:ev.detail}))}catch{}try{toast(!watched?'Evento marcado como assistido':'Evento desmarcado')}catch{}}\n catch(e){try{toast(e?.message||String(e))}catch{}}\n finally{btn.disabled=false}\n}";
const new301="async function toggleF1CalendarWatch301(btn){if(!btn||btn.disabled)return false;const watched=btn.dataset.watched==='1',next=!watched,provider=String(btn.dataset.provider||'jolpica'),id=String(btn.dataset.eventId||'');if(!id)return false;btn.type='button';btn.disabled=true;btn.dataset.watched=next?'1':'0';btn.classList.toggle('on',next);btn.textContent=next?'↶ Desmarcar assistido':'✓ Marcar como assistido';const card=[...document.querySelectorAll('[data-ct301-f1-event]')].find(x=>String(x.dataset.provider||'')===provider&&String(x.dataset.eventId||'')===id)||null;if(card){card.dataset.watched=next?'1':'0';card.classList.toggle('watched',next);const state=card.querySelector('[data-ct301-f1-state]');if(state)state.textContent=next?'✓ Assistido':'Abrir detalhes'}try{await rpc('cinetracker_sports_watch_set_v296',{p_provider:provider,p_provider_event_id:id,p_sport_slug:'formula_1',p_competition_name:'Fórmula 1',p_title:btn.dataset.title||'Fórmula 1',p_starts_at:btn.dataset.startsAt||null,p_attended_in_person:false,p_stadium_name:null,p_watched:next,p_metadata:{venue:btn.dataset.venue||null,season:btn.dataset.season||null}});window.dispatchEvent(new CustomEvent('cinetracker:sports-watched-changed',{detail:{source:'r301',provider,id,watched:next,delta:next?1:-1}}));return true}catch(e){btn.dataset.watched=watched?'1':'0';btn.classList.toggle('on',watched);btn.textContent=watched?'↶ Desmarcar assistido':'✓ Marcar como assistido';if(card){card.dataset.watched=watched?'1':'0';card.classList.toggle('watched',watched);const state=card.querySelector('[data-ct301-f1-state]');if(state)state.textContent=watched?'✓ Assistido':'Abrir detalhes'}try{toast(e?.message||String(e))}catch{}return false}finally{btn.disabled=false}}";
js=once(js,old301,new301,'r301 safe watched');
js=maybe(js,"if(toggle){e.preventDefault();e.stopImmediatePropagation();void toggleF1CalendarWatch301(toggle);return}","if(toggle){e.preventDefault();e.stopImmediatePropagation();e.stopPropagation();toggle.type='button';void toggleF1CalendarWatch301(toggle);return}");

js=once(js,"window.__ctWebBuild='1.0.159';window.__ctOfficialVersion='1.0.159';","window.__ctWebBuild='1.0.160';window.__ctOfficialVersion='1.0.160';",'version');
js=once(js,"const REVISION='r368-official-1.0.159';","const REVISION='r369-official-1.0.160';",'revision');
js=once(js,"const version='1.0.159',revision='r368-official-1.0.159';","const version='1.0.160',revision='r369-official-1.0.160';",'footer');
js=once(js,'boot();',runtime+'\nboot();','r369 runtime');
html=html.replaceAll('app-v368.js','app-v369.js').replaceAll('app-v368.css','app-v369.css').replaceAll('v1.0.159','v1.0.160').replaceAll('r368-official-1.0.159','r369-official-1.0.160');
sw=sw.replaceAll('ct-web-1.0.159-r368','ct-web-1.0.160-r369').replaceAll('app-v368.js','app-v369.js').replaceAll('app-v368.css','app-v369.css');
css+='\n/* CineTracker Web 1.0.160 r369 — no observer swap owner, hard sports no-refresh. */\n';
const prev=JSON.parse(releaseRaw),release={...prev,version:'1.0.160',revision:'r369-official-1.0.160',base:'r368-production',scope:'hard-sports-zero-refresh+bounded-abortable-swap',discover_swap_owner:'r369-no-observers',discover_swap_loop:'no-while+max-240-scan+100ms-budget',discover_swap_request:'AbortController+3s-timeout',discover_swap_fallback:'bounded-existing-pool-immediate',sports_watch_owners:'r255+r263+r296+r299+r301 patched local-only',sports_form_safety:'type=button+preventDefault+stopPropagation',sports_global_refresh:'removed-load-paint-render-data-changed',android:'1.0.20/10062'};
await Promise.all([writeFile(resolve(dist,'app-v369.js'),js),writeFile(resolve(dist,'app-v369.css'),css),writeFile(resolve(dist,'index.html'),html),writeFile(resolve(dist,'service-worker.js'),sw),writeFile(resolve(dist,'release.json'),JSON.stringify(release,null,2))]);
await Promise.all([rm(resolve(dist,'app-v368.js'),{force:true}),rm(resolve(dist,'app-v368.css'),{force:true})]);
console.log('WEB_R369_READY hard sports zero-refresh + bounded abortable swap');