import {readFile,writeFile,rm} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
await import('./build-r488.mjs');
const root=dirname(fileURLToPath(import.meta.url)),dist=resolve(root,'dist');
let [html,js,css,sw,releaseRaw,runtime]=await Promise.all([
 readFile(resolve(dist,'index.html'),'utf8'),readFile(resolve(dist,'app-v488.js'),'utf8'),readFile(resolve(dist,'app-v488.css'),'utf8'),
 readFile(resolve(dist,'service-worker.js'),'utf8'),readFile(resolve(dist,'release.json'),'utf8'),readFile(resolve(root,'runtime-r489-video-fix.js'),'utf8')
]);
function bounds(source,anchor,label){const at=source.indexOf(anchor);if(at<0)throw new Error('r489 missing '+label+' anchor');const start=source.lastIndexOf('(()=>{',at),close=source.indexOf('\n})();',at);if(start<0||close<0)throw new Error('r489 invalid '+label+' bounds');return{start,end:close+6}}
function replaceNamedFunction(source,anchor,name,replacement,label){const b=bounds(source,anchor,label),region=source.slice(b.start,b.end),m=new RegExp('(?:async\\s+)?function\\s+'+name+'\\s*\\(').exec(region);if(!m)throw new Error('r489 missing '+label+' '+name);const open=region.indexOf('{',m.index+m[0].length);let depth=0,mode='code',quote='',i=open;for(;i<region.length;i++){const c=region[i],n=region[i+1];if(mode==='line'){if(c==='\n')mode='code';continue}if(mode==='block'){if(c==='*'&&n==='/'){mode='code';i++}continue}if(mode==='string'){if(c==='\\'){i++;continue}if(c===quote)mode='code';continue}if(mode==='template'){if(c==='\\'){i++;continue}if(c.charCodeAt(0)===96)mode='code';continue}if(c==='/'&&n==='/'){mode='line';i++;continue}if(c==='/'&&n==='*'){mode='block';i++;continue}if(c==="'"||c==='"'){mode='string';quote=c;continue}if(c.charCodeAt(0)===96){mode='template';continue}if(c==='{')depth++;else if(c==='}'){depth--;if(depth===0){i++;break}}}if(depth!==0)throw new Error('r489 unbalanced '+label+' '+name);return source.slice(0,b.start)+region.slice(0,m.index)+replacement+region.slice(i)+source.slice(b.end)}
const A388="window.__ctR388Marker='r393-hidden-history-anchor+lightweight-movies+foryou-db-first-bounded';";
js=replaceNamedFunction(js,A388,'scheduleHome393',"function scheduleHome393(kind=activeKind(),fresh=false){\n const k=kind==='movies'?'movies':'series',prev=document.documentElement.dataset.ct489HomeKind||'';\n document.documentElement.dataset.ct489HomeKind=k;\n if(fresh||prev!==k){\n  homeAnchorToken393++;homeUserMoved393=false;const token=homeAnchorToken393;\n  requestAnimationFrame(()=>{if(token!==homeAnchorToken393||routeNow()!=='home'||homeUserMoved393)return;try{window.scrollTo({top:0,left:0,behavior:'auto'})}catch{window.scrollTo?.(0,0)}});\n }\n return homeAnchorToken393;\n}",'r388');
js=replaceNamedFunction(js,A388,'renderSeries',"function renderSeries(){\n const view=q('[data-home-view=\"series\"]');if(!view)return false;\n qa(':scope > [data-ct399-series-section],:scope > [data-ct397-series-section],:scope > [data-ct388-series-section],:scope > [data-ct388-series-loading]',view).forEach(x=>x.remove());\n const s=rows(hSeries),parts=[['Continuar assistindo',s.filter(x=>x.home_bucket==='continue')],['Juntando poeira',s.filter(x=>x.home_bucket==='dust')],['Em dia',s.filter(x=>x.home_bucket==='up_to_date')],['Não iniciadas / Watchlist',s.filter(x=>x.home_bucket==='not_started')],['Concluídas',s.filter(x=>x.home_bucket==='completed')]];\n const html=parts.map(([t,a])=>seriesSection(t,a)).join(''),history=q(':scope > [data-ct388-history=\"episodes\"]',view);\n if(history)history.insertAdjacentHTML('beforebegin',html);else view.insertAdjacentHTML('beforeend',html);\n document.documentElement.dataset.ct388Series=String(s.length);return true;\n}",'r388');
js=replaceNamedFunction(js,A388,'movieRow',"function movieRow(x){\n const y={...x,media_type:'movie',release_date:x?.release_date||x?.raw_tmdb?.release_date||null,runtime_minutes:Number(x?.runtime_minutes||x?.raw_tmdb?.runtime||0)||0,genres:rows(x?.genres).length?x.genres:rows(x?.raw_tmdb?.genres),vote_average:Number(x?.vote_average??x?.raw_tmdb?.vote_average??0)||0};\n const tmdb=Number(y?.tmdb_id||y?.raw_tmdb?.id||0)||0,p=String(y?.poster_path||y?.raw_tmdb?.poster_path||''),src=p?(p.startsWith('http')?p:(typeof img==='function'?img(p,'w342'):p)):'';\n const meta=[y?.release_year||String(y?.release_date||'').slice(0,4),y.runtime_minutes?y.runtime_minutes+' min':'',y.vote_average?'★ '+Number(y.vote_average).toFixed(1):''].filter(Boolean).join(' · ');\n let action='';try{action=ct274MovieWatchAction(y)||''}catch{}\n return '<article class=\"card ct489-movie-card\" data-ct388-movie-id=\"'+mediaId(y)+'\" data-media=\"movie:'+tmdb+'\"><button type=\"button\" class=\"ct489-movie-open\" data-media=\"movie:'+tmdb+'\"><div class=\"poster\"'+(src?' style=\"background-image:url(\\''+esc(src)+'\\')\"':'')+'></div><div class=\"card-body\"><b>'+esc(titleOf(y))+'</b><small>'+esc(meta)+'</small></div></button>'+action+'</article>';\n}",'r388');
js=replaceNamedFunction(js,A388,'renderMoviesAll',"function renderMoviesAll(){\n const sec=q('[data-ct388-movie-watch]'),stack=q('.ct388-movie-stack',sec);if(!sec||!stack)return false;\n const count=q('[data-ct388-movie-count]',sec);if(count)count.textContent=hMovies.length.toLocaleString('pt-BR');\n stack.replaceChildren();stack.classList.add('ct489-movie-grid');stack.style.removeProperty('display');stack.style.removeProperty('flex-direction');\n const frag=document.createDocumentFragment(),ranks=new Map();movieNodes=new Map();sortedMovies().forEach((x,i)=>ranks.set(mediaId(x),i));\n for(const x of hMovies){const t=document.createElement('template');t.innerHTML=movieRow(x).trim();const node=t.content.firstElementChild;if(!node)continue;const id=mediaId(x);node.style.order=String(ranks.get(id)??999999);movieNodes.set(id,node);frag.appendChild(node)}\n stack.appendChild(frag);sec.dataset.ct388Rendered=String(movieNodes.size);document.documentElement.dataset.ct388Movies=String(movieNodes.size);return true;\n}",'r388');
js=replaceNamedFunction(js,A388,'frame',"function frame(){\n const sk=Array.from({length:6},()=>'<div class=\"ct489-sk-row\"><div class=\"ct489-sk-poster\"></div><div class=\"ct489-sk-copy\"><span></span><span></span></div></div>').join('');\n const loading='<section class=\"home-section\" data-ct388-series-loading><div class=\"panel-head\"><h3>Continuar assistindo</h3><small>…</small></div><div class=\"ct489-home-skeleton animate-pulse\">'+sk+'</div></section>';\n return '<div class=\"home-tabs\"><button type=\"button\" class=\"chip active\" data-home-tab=\"series\">Séries</button><button type=\"button\" class=\"chip\" data-home-tab=\"movies\">Filmes</button></div>'+\n '<div data-home-view=\"series\" class=\"home-list\">'+(hSeries.length?'':loading)+historySection('episodes')+'</div>'+\n '<div data-home-view=\"movies\" class=\"home-list hidden\">'+movieSection()+historySection('movies')+'</div>';\n}",'r388');
js=replaceNamedFunction(js,A388,'refreshTv391',"async function refreshTv391(force=false){\n if(refreshTvTask391)return refreshTvTask391;const key='ct489:tv-refresh-at',now=Date.now();\n try{if(!force&&now-Number(sessionStorage.getItem(key)||0)<10*60*1000)return{skipped:true};sessionStorage.setItem(key,String(now))}catch{}\n refreshTvTask391=(async()=>{try{\n  const base=supabaseUrl391();if(!base)return{skipped:true};\n  const r=await fetch(base+'/functions/v1/ct-refresh-tv-state-user',{method:'POST',headers:{...auth391(),'content-type':'application/json'},body:'{}'});\n  if(!r.ok)throw new Error('TV refresh '+r.status);const out=await r.json();\n  if(Number(out?.episodes_cached||0)>0||Number(out?.refreshed||0)>0){\n   const full=mergeLogicalSeries(rows(await timeout(rpc('cinetracker_home_series_v452',{p_today:today()}),5200)));\n   if(full.length){hSeries=mergeSeries(full,[]);cacheSet(HS,hSeries);if(routeNow()==='home')renderSeries()}\n  }\n  return out||{};\n }catch{return{failed:true}}finally{refreshTvTask391=null}})();return refreshTvTask391;\n}",'r388');
js=replaceNamedFunction(js,A388,'loadSeries',"async function loadSeries(force=false){\n if(hSeriesTask&&!force)return hSeriesTask;const run=++hRun;document.documentElement.dataset.ct392LoadStage='series:'+run;\n hSeriesTask=(async()=>{try{\n  const full=mergeLogicalSeries(rows(await timeout(rpc('cinetracker_home_series_v452',{p_today:today()}),5200)));\n  if(run!==hRun)return hSeries;if(full.length){hSeries=full;cacheSet(HS,hSeries);if(routeNow()==='home')renderSeries()}\n  setTimeout(()=>void refreshTv391(false),120);return hSeries;\n }catch(e){document.documentElement.dataset.ct489SeriesError=String(e?.message||e);return hSeries}\n finally{if(run===hRun)hSeriesTask=null}})();return hSeriesTask;\n}",'r388');
js=replaceNamedFunction(js,A388,'loadHistory',"async function loadHistory(force=false){\n if(hHistoryTask&&!force)return hHistoryTask;const run=++hHistoryRun;\n hHistoryTask=(async()=>{try{\n  const v=await timeout(rpc('cinetracker_home_history_v391',{p_limit:100}),4200);\n  if(run!==hHistoryRun)return hHistory;if(v&&typeof v==='object'){hHistory=v;cacheSet(HH,v);if(routeNow()==='home'){renderHistory('episodes');renderHistory('movies')}}return hHistory;\n }catch(e){document.documentElement.dataset.ct489HistoryError=String(e?.message||e);return hHistory}\n finally{if(run===hHistoryRun)hHistoryTask=null}})();return hHistoryTask;\n}",'r388');
js=replaceNamedFunction(js,A388,'loadMovies',"async function loadMovies(force=false){\n if(hMoviesTask&&!force)return hMoviesTask;const run=++hMoviesRun;\n hMoviesTask=(async()=>{try{\n  const page=async offset=>{const v=await timeout(rpc('cinetracker_home_movies_v405',{p_limit:120,p_offset:offset}),6500),raw=v?.data??v??{};return{rows:rows(raw?.rows),count:Number(raw?.count||0)||0}};\n  const first=await page(0);if(run!==hMoviesRun)return hMovies;\n  hMovies=first.rows.filter(x=>String(x?.media_type||'movie')==='movie'&&mediaId(x)>0);\n  if(routeNow()==='home'&&activeKind()==='movies')renderMoviesAll();\n  const total=Math.max(first.count,hMovies.length),seen=new Set(hMovies.map(x=>String(mediaId(x))));\n  for(let offset=120;offset<total;offset+=360){\n   const batch=await Promise.allSettled([offset,offset+120,offset+240].filter(v=>v<total).map(page));\n   if(run!==hMoviesRun)return hMovies;\n   for(const b of batch)if(b.status==='fulfilled')for(const x of b.value.rows){const id=String(mediaId(x));if(id&&id!=='0'&&!seen.has(id)){seen.add(id);hMovies.push(x)}}\n   if(routeNow()==='home'&&activeKind()==='movies')renderMoviesAll();\n   await new Promise(r=>setTimeout(r,0));\n  }\n  cacheSet(HM,hMovies);document.documentElement.dataset.ct489MoviesReady=String(hMovies.length)+'/'+String(total);return hMovies;\n }catch(primary){\n  try{const v=await timeout(rpc('cinetracker_watchlist_full_v376',{}),9000);if(run!==hMoviesRun)return hMovies;hMovies=rows(v?.rows).filter(x=>String(x?.media_type||'')==='movie'&&mediaId(x)>0);if(routeNow()==='home'&&activeKind()==='movies')renderMoviesAll();return hMovies}\n  catch(e){document.documentElement.dataset.ct489MoviesError=String(e?.message||e);return hMovies}\n }finally{if(run===hMoviesRun)hMoviesTask=null}})();return hMoviesTask;\n}",'r388');
js=replaceNamedFunction(js,A388,'renderHome388',"async function renderHome388(){\n const kind=activeKind();try{if(!q('[data-home]'))setApp(shell('Home','Sua biblioteca sincronizada e organizada pelo seu progresso.','home','<div class=\"page\" data-home></div>'))}catch{}\n paintFrame(kind);scheduleHome393(kind,true);\n const critical=[loadSeries(false),loadHistory(false)];if(kind==='movies')critical.push(loadMovies(false));\n await Promise.allSettled(critical);if(routeNow()!=='home')return false;\n if(hSeries.length)renderSeries();if(hHistory){renderHistory('episodes');renderHistory('movies')}if(kind==='movies'&&hMovies.length)renderMoviesAll();\n if(kind!=='movies'&&!hMovies.length)setTimeout(()=>{if(!hMovies.length)void loadMovies(false)},250);\n document.documentElement.dataset.ct489Home='ready';return true;\n}",'r388');
const A399="window.__ctR399Marker='startup-auth-current-rpc+home+direct-foryou';";
js=replaceNamedFunction(js,A399,'enterHome399',"function enterHome399(kind=activeHome()){\n if(routeNow()!=='home')return false;const k=kind==='movies'?'movies':'series';\n try{if(!q('[data-home-view=\"series\"]')||!q('[data-home-view=\"movies\"]')){void window.__ctR388?.renderHome?.();return true}}catch{}\n try{if(k==='movies')void window.__ctR388?.loadMovies?.(false);else void window.__ctR388?.loadSeries?.(false)}catch{}\n return true;\n}",'r399');
js=replaceNamedFunction(js,A399,'refreshSeries399',"async function refreshSeries399(force=false){try{return await window.__ctR388?.loadSeries?.(!!force)||[]}catch{return[]}}",'r399');
js=replaceNamedFunction(js,A399,'ensureMovies399',"async function ensureMovies399(force=false){try{return await window.__ctR388?.loadMovies?.(!!force)||[]}catch{return[]}}",'r399');
const A476="if(window.__ctR476?.version==='1.0.266')return;";
js=replaceNamedFunction(js,A476,'primeHome',"function primeHome(kind='series'){\n if(routeNow()!=='home')return false;const k=kind==='movies'?'movies':'series';\n try{if(!q('[data-home]'))core.ensureHomeShell?.()}catch{}\n try{if(!q('[data-home-view=\"series\"]')||!q('[data-home-view=\"movies\"]'))void window.__ctR388?.renderHome?.();else if(k==='movies')void window.__ctR388?.loadMovies?.(false);else void window.__ctR388?.loadSeries?.(false)}catch{}\n return true;\n}",'r476');
js=replaceNamedFunction(js,A476,'renderPanel',"function renderPanel(key){\n const panel=panelFor(key);if(!panel)return false;\n const row=q(':scope > .row,:scope > .ct424-profile-list,:scope > [class*=\"rail\"],:scope > [class*=\"row\"]',panel);if(!row)return false;\n const data=listFor(key),countKey=key==='series'?'series':key==='movies'?'movies':key==='seriesFav'?'series_favorites':key==='movieFav'?'movie_favorites':'actors',total=Number(profile?.counts?.[countKey]??data.length);\n removeLargeMore(panel);row.innerHTML=data.slice(0,LIMIT).map(x=>renderCard(key,x)).join('')||'<div class=\"empty\">Nenhum item nesta seção.</div>';row.dataset.ct476ProfileRow=key;\n const count=q('.panel-head small',panel);if(count)count.textContent=total.toLocaleString('pt-BR');ensureHeaderMore(panel,key,total);return true;\n}",'r476');
js=replaceNamedFunction(js,A476,'loadProfile',"async function loadProfile(force=false){\n if(profileTask)return profileTask;if(profile&&!force){paintProfile();return profile}\n profileTask=(async()=>{try{\n  const raw=await core.rpc('cinetracker_profile_summary_v489',{});if(raw&&typeof raw==='object'&&!Array.isArray(raw))profile=raw;\n  paintProfile();document.documentElement.dataset.ct489Profile='summary-v489';return profile;\n }catch(e){document.documentElement.dataset.ct489ProfileError=String(e?.message||e);return profile}\n finally{profileTask=null}})();return profileTask;\n}",'r476');
js=replaceNamedFunction(js,A476,'scheduleProfile',"function scheduleProfile(force=false){\n const seq=++profileSeq;\n const run=attempt=>{if(seq!==profileSeq||routeNow()!=='profile')return;if(!profileRoot()){if(attempt<12)setTimeout(()=>run(attempt+1),40);return}\n  if(profile&&!force)paintProfile();else void loadProfile(force);\n };\n queueMicrotask(()=>run(0));return true;\n}",'r476');
js=replaceNamedFunction(js,A476,'openAll',"async function openAll(key){\n closeAll();const back=document.createElement('div');back.className='ct476-all-screen';back.dataset.ct476AllScreen=key;\n const tabs=key==='movies'?'<div class=\"ct478-movie-tabs\" role=\"tablist\" aria-label=\"Filmes\"><button type=\"button\" class=\"chip active\" role=\"tab\" aria-selected=\"true\" data-ct478-movie-mode=\"history\">Histórico</button><button type=\"button\" class=\"chip\" role=\"tab\" aria-selected=\"false\" data-ct478-movie-mode=\"watchlist\">Watchlist</button></div>':'';\n back.innerHTML='<section class=\"ct476-all-panel\" role=\"dialog\" aria-modal=\"true\"><header><div><small>PERFIL</small><h2>'+esc(labels[key])+'</h2><p data-ct478-all-count>Carregando…</p>'+tabs+'</div><button type=\"button\" class=\"btn\" data-ct476-all-close>✕ Fechar</button></header><div class=\"ct476-all-grid\" data-ct476-all-grid><div class=\"empty\">Carregando lista completa…</div></div></section>';\n document.body.appendChild(back);q('[data-ct476-all-close]',back)?.focus();\n try{const raw=await core.rpc('cinetracker_profile_lists_v485',{});if(!back.isConnected)return false;if(raw&&typeof raw==='object'&&!Array.isArray(raw))profile=raw;paintAllGrid(back,key,'history');if(key==='movies')void loadMovieWatchlist(false);return true}\n catch(e){const grid=q('[data-ct476-all-grid]',back);if(grid)grid.innerHTML='<div class=\"empty\">Não foi possível carregar a lista completa.</div>';return false}\n}",'r476');
const A477="if(window.__ctR477?.version==='1.0.267')return;";
js=replaceNamedFunction(js,A477,'bootHome',"function bootHome(kind='series'){\n if(!(routeNow()==='home'||homeLocation()))return false;const k=kind==='movies'?'movies':'series';\n delete document.documentElement.dataset.ct413HomeEntering;delete document.documentElement.dataset.ct415HomeEntering;\n try{if(!q('[data-home]'))core.ensureHomeShell?.()}catch{}\n try{if(!q('[data-home-view=\"series\"]')||!q('[data-home-view=\"movies\"]'))void window.__ctR388?.renderHome?.();else if(k==='movies')void window.__ctR388?.loadMovies?.(false);else void window.__ctR388?.loadSeries?.(false)}catch{}\n return true;\n}",'r477');
js=replaceNamedFunction(js,A477,'loadSports',"async function loadSports(force=false){\n if(sportsTask)return sportsTask;const seq=++sportsSeq;if(sportsCache)paintSports(sportsCache);else hideSports();\n sportsTask=(async()=>{try{\n  const raw=await core.rpc('cinetracker_sports_stadium_summary_v296',{}),d=Array.isArray(raw)?raw[0]:raw,next={watched_events:num(d?.watched_events),stadium_events:num(d?.stadium_events)};\n  if(seq!==sportsSeq||routeNow()!=='profile')return sportsCache;sportsCache=next;try{localStorage.setItem('ct489:sports-cache',JSON.stringify({at:Date.now(),data:next}))}catch{};paintSports(next);return next;\n }catch(e){if(seq===sportsSeq&&routeNow()==='profile'){if(sportsCache)paintSports(sportsCache);else sportsPanel()?.style.removeProperty('visibility');document.documentElement.dataset.ct489SportsError=String(e?.message||e)}return sportsCache}\n finally{sportsTask=null}})();return sportsTask;\n}",'r477');
js=replaceNamedFunction(js,A477,'settleProfile',"function settleProfile(force=false){\n const seq=++profileSettleSeq;\n const probe=attempt=>{if(seq!==profileSettleSeq||routeNow()!=='profile')return;const panel=sportsPanel();if(!panel){if(attempt<14)setTimeout(()=>probe(attempt+1),35);return}\n  try{window.__ctR476?.paintProfile?.()}catch{}\n  if(!sportsCache)try{const c=JSON.parse(localStorage.getItem('ct489:sports-cache')||'null');if(c?.data&&Date.now()-Number(c.at||0)<3600000)sportsCache=c.data}catch{}\n  if(sportsCache)paintSports(sportsCache);else hideSports();void loadSports(force);\n };\n probe(0);return true;\n}",'r477');
const A481="if(window.__ctR481?.version==='0.3.8')return;";
js=replaceNamedFunction(js,A481,'prime',"function prime(kind='series'){\n const k=kind==='movies'?'movies':'series';if(!(routeNow()==='home'||homeLocation()))return false;\n try{core.ensureHomeShell?.()}catch{}\n try{if(!q('[data-home-view=\"series\"]')||!q('[data-home-view=\"movies\"]'))void window.__ctR388?.renderHome?.();else if(k==='movies')void window.__ctR388?.loadMovies?.(false);else void window.__ctR388?.loadSeries?.(false)}catch{}\n return true;\n}",'r481');
const A464="window.__ctR464Marker='discover-foryou-visible-owner-v421';";
js=replaceNamedFunction(js,A464,'load',"async function load(force=false){\n setForYouState();if(routeNow()!=='discover')return false;if(loadTask)return loadTask;\n const token=++loadToken;if(!q('[data-ct464-foryou]',root464()))renderLoading();\n loadTask=(async()=>{try{\n  const raw=unwrap(await timeout(rpcCall('cinetracker_foryou_payload_v489',{p_watch_limit:30,p_fresh_limit:48}),4500))||{},next=emptyState(),kinds=['movie','series','anime'];\n  for(const k of kinds){next.watch[k]=rows(raw?.watch?.[k]);next.fresh[k]=rows(raw?.fresh?.[k])}\n  if(!kinds.every(k=>next.watch[k].length&&next.fresh[k].length))throw new Error('v489 incomplete pools');\n  if(token!==loadToken||routeNow()!=='discover')return false;state=next;chooseDaily();\n  let cycle=1;try{cycle=(Number(sessionStorage.getItem('ct489:foryou-cycle')||0)+1)%100000;sessionStorage.setItem('ct489:foryou-cycle',String(cycle))}catch{cycle=Date.now()%100000}\n  kinds.forEach((k,i)=>{state.idx.watch[k]=(cycle+i*3)%state.watch[k].length;state.idx.fresh[k]=(cycle+i*5+1)%state.fresh[k].length});\n  render();try{void recordShown479?.()}catch{}\n  document.documentElement.dataset.ct464PoolCounts=JSON.stringify({watch:Object.fromEntries(kinds.map(k=>[k,state.watch[k].length])),fresh:Object.fromEntries(kinds.map(k=>[k,state.fresh[k].length]))});\n  document.documentElement.dataset.ct489ForYou='v489-single-payload';return true;\n }catch(primary){\n  const kinds=['movie','series','anime'],specs=[...kinds.map(k=>['watch',k]),...kinds.map(k=>['fresh',k])],settled=await Promise.allSettled(specs.map(([g,k])=>fetchPool(g,k))),next=emptyState();\n  settled.forEach((r,i)=>{if(r.status==='fulfilled')next[specs[i][0]][specs[i][1]]=rows(r.value)});\n  if(token!==loadToken||routeNow()!=='discover')return false;\n  if(!kinds.some(k=>next.watch[k].length||next.fresh[k].length))throw primary;\n  state=next;chooseDaily();render();document.documentElement.dataset.ct489ForYou='fallback';return true;\n }})().catch(e=>{if(token===loadToken){document.documentElement.dataset.ct489ForYouError=String(e?.message||e);const root=root464();if(root)root.innerHTML='<div data-ct464-foryou><div class=\"panel\"><div class=\"empty\">Não foi possível carregar as indicações. <button type=\"button\" class=\"chip\" data-ct489-foryou-retry>Tentar novamente</button></div></div></div>'}return false}).finally(()=>{if(token===loadToken)loadTask=null});\n return loadTask;\n}",'r464');
js=replaceNamedFunction(js,A464,'activate',"function activate(){\n setForYouState();qa('[data-ct319-tab],[data-ct315-tab],[data-ct263-discover-tab],[data-discover-tab]').forEach(b=>{if(isForYouControl(b))b.classList.add('active')});\n if(!q('[data-ct464-foryou]',root464()))renderLoading();void load(false);return true;\n}",'r464');
const A296="window.__ctR296='strict-foryou-four-sports-stadium-web-polish';";
js=replaceNamedFunction(js,A296,'injectStadiumMetric296',"function injectStadiumMetric296(count){return false}",'r296');
const A298="window.__ctR298='stadium-real-controls+exact-foryou-live-pipeline';";
js=replaceNamedFunction(js,A298,'repairProfile298',"async function repairProfile298(){return false}",'r298');
js=replaceNamedFunction(js,A298,'reconcile298',"function reconcile298(){clearTimeout(reconcileTimer);if(routeNow()==='sports'){let n=0;const tick=()=>{n++;if(routeNow()==='sports')void decorateSports298(n===1);if(n<4)reconcileTimer=setTimeout(tick,350)};tick()}}",'r298');
new Function(runtime);js+='\n'+runtime+'\n';
html=html.replaceAll('app-v488.js','app-v489.js').replaceAll('app-v488.css','app-v489.css').replaceAll('v0.3.15','v0.3.16').replaceAll('r488-official-0.3.15','r489-official-0.3.16');
css+='\n/* CineTracker Web 0.3.16 r489 — video-ground-truth authority. */\n';
sw=sw.replaceAll('app-v488.js','app-v489.js').replaceAll('app-v488.css','app-v489.css').replaceAll('ct-web-0.3.15-r488','ct-web-0.3.16-r489');
const release=JSON.parse(releaseRaw);Object.assign(release,{
 version:'0.3.16',revision:'r489-official-0.3.16',base:'r488+r489-video-ground-truth',
 scope:'home-single-owner+movies-real-card-grid+foryou-v489-single-payload+profile-v489-summary+sports-single-paint',
 home_series:'r388 is the single data painter; v452 measured around 1.5s; Continue is structurally before History and no delayed semantic scroll loop remains',
 home_movies:'v405 pages through r388 and renders native poster cards rather than CSS-transforming media rows',
 discover_foryou:'one cinetracker_foryou_payload_v489 request returns all six pools; validated non-empty for every kind',
 profile_lists:'cinetracker_profile_summary_v489 returns exactly 12 cards for each summary plus complete counts; v485 full payload is deferred until Ver mais',
 profile_sports:'legacy r296/r298 Profile writers are neutralized; r477 hides until one v296 authoritative response, then reveals once',
 top10:'r321 preserved with final strict 2:3/object-cover geometry',f1:'preserved',sports:'sports route preserved',android:'unchanged-1.0.20/10062'
});
await Promise.all([
 writeFile(resolve(dist,'app-v489.js'),js),writeFile(resolve(dist,'app-v489.css'),css),writeFile(resolve(dist,'index.html'),html),
 writeFile(resolve(dist,'service-worker.js'),sw),writeFile(resolve(dist,'release.json'),JSON.stringify(release,null,2))
]);
await Promise.all([rm(resolve(dist,'app-v488.js'),{force:true}),rm(resolve(dist,'app-v488.css'),{force:true})]);
for(const need of ["window.__ctR489Marker='video-truth+single-home-owner+movies-real-2x3+foryou-one-rpc+profile-fast-12+sports-no-flicker'",'cinetracker_home_series_v452','cinetracker_home_movies_v405','ct489-movie-card','cinetracker_foryou_payload_v489','cinetracker_profile_summary_v489','cinetracker_profile_lists_v485'])if(!js.includes(need))throw new Error('r489 missing '+need);
console.log('WEB_R489_READY video-ground-truth');
