(() => {
'use strict';
if(window.__ct52WebLoaded)return;window.__ct52WebLoaded=true;
const VERSION='0.5.2',$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const detailCache=new Map(),searchCache=new Map(),episodeCache=new Map();
let runQueued=false,navLock=false;
const css=document.createElement('style');css.id='ct52w-style';css.textContent=`
.ct49w-series-progress,.ct50w-series-progress,.ct51w-series-progress,.ct52w-progress{display:none!important}
.ct52w-progress{display:block!important;font-size:11px;line-height:1.45;color:#92a4b2;margin-top:6px}
.ct52w-score{display:inline-flex;align-items:center;gap:4px;color:#f0c75e;font-size:11px;font-weight:800;margin-right:8px}
.ct52w-ep-actions{display:flex;align-items:center;gap:8px}.ct52w-seen{border:1px solid #35536b;background:#0b131b;color:#dce8f0;border-radius:10px;padding:7px 10px}.ct52w-seen.on{background:#153a25;border-color:#39754d;color:#a7dfb5}
.ct52w-modal{position:fixed;inset:0;z-index:100000;background:#000c;display:flex;align-items:flex-end;justify-content:center}.ct52w-sheet{width:min(760px,100%);max-height:88vh;overflow:auto;background:#0b1117;border:1px solid #263847;border-radius:20px 20px 0 0;padding:16px}.ct52w-shot{aspect-ratio:16/9;background:#0b1720 center/cover no-repeat;border-radius:14px;margin:10px 0}.ct52w-close{float:right;border:1px solid #345066;background:#101820;color:#fff;border-radius:9px;padding:7px 10px}.ct52w-sheet h2{margin:4px 0 8px}.ct52w-sheet p{color:#aab5be;line-height:1.5}.ct52w-cover-loading{background-image:linear-gradient(120deg,#10202c,#172b39,#10202c)!important;background-size:200% 100%!important}
`;document.head.appendChild(css);
function mediaInfo(c){const raw=c?.dataset?.mediaId||'',m=raw.match(/^tmdb-(movie|tv)-(\d+)$/);let id=Number(c?.dataset?.tmdbId||c?.dataset?.id||c?.dataset?.ct29Id||c?.dataset?.ct30Id||0),type=String(c?.dataset?.apiType||c?.dataset?.type||'').toLowerCase();if(m){type=m[1];id=Number(m[2])}if(!type)type=/\bfilme\b/i.test(c?.textContent||'')?'movie':'tv';const title=(c?.querySelector?.('h1,h2,h3,.ct47-title,.ct48-home-title,.card-title,strong')?.textContent||c?.dataset?.title||'').trim();return{id,type:type.includes('movie')?'movie':'tv',title}}
async function api(path,params={}){const u=new URL(`${SUPABASE_URL}/functions/v1/tmdb-proxy`);u.searchParams.set('path',path);u.searchParams.set('language','pt-BR');for(const[k,v]of Object.entries(params))if(v!=null)u.searchParams.set(k,String(v));const r=await fetch(u,{headers:typeof authHeaders==='function'?authHeaders():{}});if(!r.ok)throw new Error('TMDB '+r.status);return r.json()}
function posterUrl(p,size='w500'){return p?`${SUPABASE_URL}/functions/v1/tmdb-image?path=${encodeURIComponent(p)}&size=${size}`:''}
async function detail(type,id){const k=`${type}:${id}`;if(!detailCache.has(k))detailCache.set(k,api(`/${type}/${id}`).catch(()=>null));return detailCache.get(k)}
async function searchTitle(title,type){const k=`${type}:${norm(title)}`;if(!searchCache.has(k))searchCache.set(k,api(`/search/${type}`,{query:title,page:1}).then(d=>d?.results?.[0]||null).catch(()=>null));return searchCache.get(k)}
async function resolveCover(card){if(!card||card.dataset.ct52Cover==='1')return;const cover=$('.poster,.tmdb-poster,.ct47-poster,.ct47-hero-poster,.ct48-home-poster,.ct46w-poster,.ct49w-thumb',card);if(!cover)return;const bg=getComputedStyle(cover).backgroundImage;if(bg&&bg!=='none'&&!/gradient/i.test(bg)){card.dataset.ct52Cover='1';return}card.dataset.ct52Cover='loading';cover.classList.add('ct52w-cover-loading');const i=mediaInfo(card);let d=null;if(i.id)d=await detail(i.type,i.id);if(!d&&i.title)d=await searchTitle(i.title,i.type);const p=d?.poster_path||d?.backdrop_path;if(p){cover.style.backgroundImage=`url('${posterUrl(p,'w500')}')`;card.dataset.ct52Cover='1'}else delete card.dataset.ct52Cover;cover.classList.remove('ct52w-cover-loading')}
function rebootCovers(){const cards=$$('.card,.feature,.ct47-card,.ct48-home-card,.ct46w-card,.list-item,[data-media-id],[data-tmdb-id]');let n=0;for(const c of cards){if(n>=24)break;const cover=$('.poster,.tmdb-poster,.ct47-poster,.ct47-hero-poster,.ct48-home-poster,.ct46w-poster,.ct49w-thumb',c);if(cover&&(!cover.style.backgroundImage||cover.style.backgroundImage==='none')){n++;void resolveCover(c)}}}
function cleanNav(){const navs=$$('.nav,.mobile-nav');for(const n of navs){const cfg=$$('button',n).filter(b=>/configura/i.test(norm(b.textContent)));cfg.slice(1).forEach(x=>x.remove());if(cfg[0])cfg[0].dataset.view='settings';for(const b of $$('button',n)){if(norm(b.textContent)==='importar')b.remove();if(b.dataset.view)b.disabled=false}}}
function navigate(target){if(navLock)return;navLock=true;try{if(target==='import')target='settings';window.view=target;if(typeof render==='function')render();window.scrollTo(0,0)}finally{setTimeout(()=>{navLock=false;schedule()},60)}}
document.addEventListener('click',e=>{const b=e.target.closest('.nav button[data-view],.mobile-nav button[data-view]');if(b){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();navigate(b.dataset.view)}},true);
async function progressRows(){try{return await sbRpc('cinetracker_continue_items_v2',{})||[]}catch{return[]}}
let rowMap=new Map(),rowAt=0;async function ensureRows(force=false){if(!force&&Date.now()-rowAt<30000&&rowMap.size)return;const rs=await progressRows();rowMap=new Map(rs.filter(x=>x.tmdb_id).map(x=>[Number(x.tmdb_id),x]));rowAt=Date.now()}
async function canonicalProgress(){if(typeof view!=='undefined'&&view==='history'){$$('.ct52w-progress,.ct49w-series-progress,.ct50w-series-progress').forEach(x=>x.remove());return}await ensureRows();for(const c of $$('.card,.feature,.ct47-card,.ct48-home-card,[data-media-id],[data-tmdb-id]')){const i=mediaInfo(c);if(i.type!=='tv'||!i.id)continue;$$('.ct52w-progress,.ct49w-series-progress,.ct50w-series-progress',c).forEach(x=>x.remove());const r=rowMap.get(i.id);if(!r)continue;const watched=Number(r.watched_episodes||0),total=Number(r.total_episodes||0),season=Number(r.season_number||r.current_season||r.last_season||1),episode=Number(r.episode_number||r.current_episode||r.last_episode||watched||0);const el=document.createElement('div');el.className='ct52w-progress';el.textContent=`Temporada ${season} • Episódio ${episode} • ${watched}/${total||'?'} • Faltam ${total?Math.max(0,total-watched):'?'} episódios`;const host=$('.ct48-home-meta,.ct47-meta,.media-meta,.ct46w-meta,.card-body',c)||c;host.insertAdjacentElement(host.matches('.card-body')?'afterbegin':'afterend',el)}}
async function seasonData(tv,season){const k=`${tv}:${season}`;if(!episodeCache.has(k))episodeCache.set(k,api(`/tv/${tv}/season/${season}`).catch(()=>null));return episodeCache.get(k)}
async function watchedMap(tv){try{const rs=await sbRpc('cinetracker_episode_state',{p_tmdb_id:tv})||[];return new Map(rs.map(x=>[`${Number(x.season_number)}:${Number(x.episode_number)}`,!!x.watched]))}catch{return new Map()}}
async function markSeen(tv,s,e,seen,title){await sbRpc('cinetracker_set_episode_watched',{p_tmdb_id:tv,p_season:s,p_episode:e,p_watched:seen,p_title:title||null});rowAt=0;await ensureRows(true);schedule()}
function episodeModal(tv,season,ep,seen){const old=$('.ct52w-modal');if(old)old.remove();const m=document.createElement('div');m.className='ct52w-modal';m.innerHTML=`<div class="ct52w-sheet"><button class="ct52w-close">Fechar</button><div class="ct52w-shot"${ep.still_path?` style="background-image:url('${posterUrl(ep.still_path,'w780')}')"`:''}></div><h2>T${season} E${ep.episode_number} · ${ep.name||'Episódio'}</h2><div class="ct52w-score">★ ${Number(ep.vote_average||0).toFixed(1)}</div><p>${ep.overview||'Sem sinopse disponível.'}</p><button class="ct52w-seen${seen?' on':''}">${seen?'✓ Assistido':'Marcar como assistido'}</button></div>`;document.body.appendChild(m);$('.ct52w-close',m).onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()};$('.ct52w-seen',m).onclick=async b=>{const next=!b.currentTarget.classList.contains('on');await markSeen(tv,season,Number(ep.episode_number),next,ep.name);b.currentTarget.classList.toggle('on',next);b.currentTarget.textContent=next?'✓ Assistido':'Marcar como assistido'}}
async function enhanceEpisodes(){const hero=$('.ct47-hero');let tv=Number(hero?.closest?.('[data-id]')?.dataset?.id||window.currentSeriesId||0);if(!tv){const c=$('.ct47-card[data-type="tv"][data-id]');tv=Number(c?.dataset.id||0)}if(!tv)return;const map=await watchedMap(tv);for(const row of $$('.ct47-ep[data-season][data-episode]')){if(row.dataset.ct52==='1')continue;row.dataset.ct52='1';const s=Number(row.dataset.season),e=Number(row.dataset.episode),sd=await seasonData(tv,s),ep=(sd?.episodes||[]).find(x=>Number(x.episode_number)===e);if(!ep)continue;const seen=!!map.get(`${s}:${e}`);const actions=document.createElement('div');actions.className='ct52w-ep-actions';actions.innerHTML=`<span class="ct52w-score">★ ${Number(ep.vote_average||0).toFixed(1)}</span><button class="ct52w-seen${seen?' on':''}">${seen?'✓ Assistido':'Assistido'}</button>`;const old=row.querySelector('.ct47-seen');if(old)old.remove();row.appendChild(actions);actions.querySelector('button').onclick=async ev=>{ev.stopPropagation();const b=ev.currentTarget,next=!b.classList.contains('on');await markSeen(tv,s,e,next,ep.name);b.classList.toggle('on',next);b.textContent=next?'✓ Assistido':'Assistido'};row.addEventListener('click',ev=>{if(!ev.target.closest('button'))episodeModal(tv,s,ep,actions.querySelector('button').classList.contains('on'))})}}
function versionFooter(){if(typeof view==='undefined'||view!=='settings')return;const host=$('.content')||$('#app');if(!host)return;$$('[id*=version],.ct-version-footer').forEach(x=>{if(/CineTracker Web/i.test(x.textContent||''))x.remove()});const f=document.createElement('div');f.id='ct52w-version';f.style.cssText='margin:28px 0 8px;text-align:center;color:#71808b;font-size:11px';f.textContent=`CineTracker Web • versão ${VERSION}`;host.appendChild(f)}
function run(){cleanNav();versionFooter();void canonicalProgress();rebootCovers();void enhanceEpisodes()}
function schedule(){if(runQueued)return;runQueued=true;setTimeout(()=>{runQueued=false;run()},120)}
new MutationObserver(schedule).observe($('#app')||document.documentElement,{childList:true,subtree:true});setTimeout(run,50);setTimeout(run,600);window.ct52WebRefresh=async()=>{rowAt=0;await ensureRows(true);schedule()};window.ct52RebootCovers=()=>{for(const c of $$('[data-ct52-cover]'))delete c.dataset.ct52Cover;rebootCovers()};
})();