(() => {
'use strict';
if(window.__ct45WebLoaded)return;window.__ct45WebLoaded=true;
const cache=new Map(),queue=[];let active=0;
const cards='.card,.feature,.ct38-card,.ct30-fav,.ct30-history-card,.ct30-follow-card,.ct43-history-card,[data-media-id],[data-tmdb-id]';
const titles='h1,h2,h3,.ct38-title,.ct30-fav-body strong,.ct30-history-body strong,.ct43-history-card strong';
const posters='.poster,.tmdb-poster,.ct38-poster,.ct30-fav-poster,.ct30-history-poster,.ct30-follow-poster,.ct43-history-poster,img';
function loggedOut(){try{return (typeof currentUser==='undefined'||!currentUser)||!!document.querySelector('.auth-page,#auth-form,#auth-email,#auth-password')}catch{return true}}
function registry(mid){try{return typeof mediaRegistry!=='undefined'?mediaRegistry.get(mid):null}catch{return null}}
function info(card){const titleEl=card.querySelector(titles),text=(titleEl?.textContent||'').trim(),mid=card.dataset.mediaId||'',item=registry(mid);let id=Number(card.dataset.tmdbId||card.dataset.ct29Id||card.dataset.ct30Id||item?.tmdbId||item?.tmdb_id||0);const mm=mid.match(/^tmdb-(movie|tv)-(\d+)$/);if(!id&&mm)id=Number(mm[2]);const mt=text.match(/^TMDB\s*#\s*(\d+)/i);if(!id&&mt)id=Number(mt[1]);let raw=String(card.dataset.apiType||card.dataset.tmdbType||item?.apiType||item?.media_type||item?.type||'').toLowerCase();if(!raw)raw=(card.textContent||'').toLowerCase().includes('filme')?'movie':'tv';const type=raw.includes('movie')||raw.includes('filme')?'movie':'tv';return{id,type,titleEl,item}}
function paint(el,path){if(!el||!path)return false;const url=path.startsWith('http')?path:`https://image.tmdb.org/t/p/w342${path}`;if(el.tagName==='IMG'){el.src=url;el.loading='lazy';el.decoding='async'}else{el.style.backgroundImage=`url("${url}")`;el.style.backgroundSize='cover';el.style.backgroundPosition='center 18%'}return true}
async function detail(type,id){const key=type+':'+id;if(cache.has(key))return cache.get(key);try{const raw=localStorage.getItem('ct45w:'+key);if(raw){const o=JSON.parse(raw);if(Date.now()-o.t<604800000){cache.set(key,o.d);return o.d}}}catch{}const u=new URL(`${SUPABASE_URL}/functions/v1/tmdb-proxy`);u.searchParams.set('path',`/${type}/${id}`);u.searchParams.set('language','pt-BR');const r=await fetch(u,{headers:typeof authHeaders==='function'?authHeaders():{}});if(!r.ok)throw new Error('TMDB '+r.status);const d=await r.json();cache.set(key,d);try{localStorage.setItem('ct45w:'+key,JSON.stringify({t:Date.now(),d}))}catch{}return d}
function pump(){while(active<4&&queue.length){const fn=queue.shift();active++;Promise.resolve().then(fn).catch(()=>{}).finally(()=>{active--;pump()})}}
function hydrate(card){if(loggedOut()||card.dataset.ct45w==='loading')return;const p=card.querySelector(posters),i=info(card);if(!i.id)return;const title=(i.titleEl?.textContent||'').trim();if(i.item?.poster_path)paint(p,i.item.poster_path);if(i.item?.title&&i.titleEl&&(!title||/^TMDB\s*#/i.test(title)))i.titleEl.textContent=i.item.title;card.dataset.ct45w='loading';queue.push(async()=>{try{const d=await detail(i.type,i.id);if(i.titleEl&&(d.title||d.name))i.titleEl.textContent=d.title||d.name;if(d.poster_path)paint(p,d.poster_path);card.dataset.ct45w='done'}catch{delete card.dataset.ct45w}});pump()}
function scan(){if(loggedOut())return;document.querySelectorAll(cards).forEach(hydrate)}
let q=false;new MutationObserver(()=>{if(q)return;q=true;requestAnimationFrame(()=>{q=false;scan()})}).observe(document.getElementById('app')||document.documentElement,{childList:true,subtree:true});
window.ct45WebResolve=scan;setTimeout(scan,200);setTimeout(scan,1000);setInterval(scan,3000);
})();