(() => {
'use strict';
if(window.__ct50WebLoaded)return;window.__ct50WebLoaded=true;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];const providersCache=new Map();let seriesId=0;
const css=document.createElement('style');css.textContent=`.ct50-provider{margin-top:7px;font-size:10px;color:#8ea1b0}.ct50-provider b{color:#c8d5df}.ct50-provider-chip{display:inline-block;margin:3px 4px 0 0;padding:3px 6px;border:1px solid #294052;border-radius:999px;background:#0b141b;color:#b9cbd9;font-size:9px}body.ct50-discover .content .grid,body.ct50-discover .content .discover-grid,body.ct50-discover .content .cards,body.ct50-discover .content div:has(> .card),body.ct50-discover .content section:has(> .card),body.ct50-discover .content .ct50-grid3{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:10px!important}body.ct50-discover .content .ct50-grid3>*{min-width:0!important;width:auto!important;max-width:none!important;margin:0!important}body.ct50-discover .content .poster,body.ct50-discover .content .tmdb-poster{width:100%!important;height:auto!important;aspect-ratio:2/3!important;min-height:0!important}.ct50-toast{position:fixed;left:16px;right:16px;bottom:20px;z-index:999999;padding:11px 13px;border:1px solid #2e4a5d;border-radius:12px;background:#101820;color:#edf5fa;font-size:12px}`;document.head.appendChild(css);
function toast(t){let n=$('.ct50-toast');if(!n){n=document.createElement('div');n.className='ct50-toast';document.body.appendChild(n)}n.textContent=t;clearTimeout(n._t);n._t=setTimeout(()=>n.remove(),2200)}
function ah(){return typeof authHeaders==='function'?authHeaders():{}}async function tmdb(type,id,extra=''){const u=new URL(`${SUPABASE_URL}/functions/v1/tmdb-proxy`);u.searchParams.set('path',`/${type}/${id}${extra}`);u.searchParams.set('language','pt-BR');const r=await fetch(u,{headers:ah()});if(!r.ok)throw new Error('TMDB');return r.json()}
function activityTime(r){const v=r?.last_watched_at||r?.last_activity_at||r?.last_seen_at||r?.watched_at||r?.updated_at;const t=v?Date.parse(v):0;return Number.isFinite(t)?t:0}async function rows(){let x=[];try{x=await sbRpc('cinetracker_continue_items_v2',{})||[]}catch{try{x=await sbRpc('cinetracker_continue_items',{})||[]}catch{}}return x.filter(r=>r.status==='following'||(!['up_to_date','dusty','not_started','watched'].includes(r.status)&&Number(r.watched_episodes||0)>0)).sort((a,b)=>activityTime(b)-activityTime(a))}
async function reorder(){const rr=await rows();if(typeof view!=='undefined'&&view==='home'){const l=$('.ct47w-home-list,.ct49-home-list');if(l){const m=new Map($$('[data-id]',l).map(n=>[Number(n.dataset.id),n]));rr.forEach(r=>{const n=m.get(Number(r.tmdb_id));if(n)l.appendChild(n)})}}if(typeof view!=='undefined'&&view==='assist'){const l=$('[data-section="following"] .ct47-list,[data-section="following"] .ct46w-list');if(l){const m=new Map($$('[data-id]',l).map(n=>[Number(n.dataset.id),n]));rr.forEach(r=>{const n=m.get(Number(r.tmdb_id));if(n)l.appendChild(n)})}}}
async function smart(id,s,e,watched,title){if(!watched)return sbRpc('cinetracker_set_episode_watched',{p_tmdb_id:id,p_season:s,p_episode:e,p_watched:false,p_title:title||null});let state=[];try{state=await sbRpc('cinetracker_episode_state',{p_tmdb_id:id})||[]}catch{}const seen=new Set(state.filter(x=>x.watched).map(x=>`${Number(x.season_number)}:${Number(x.episode_number)}`)),missing=[];for(let i=1;i<e;i++)if(!seen.has(`${s}:${i}`))missing.push(i);if(missing.length&&confirm(`Você marcou o episódio ${e}. Já viu também os ${missing.length} anteriores desta temporada?`)){try{return await sbRpc('cinetracker_mark_episode_through',{p_tmdb_id:id,p_season:s,p_episode:e})}catch{for(const i of missing)await sbRpc('cinetracker_set_episode_watched',{p_tmdb_id:id,p_season:s,p_episode:i,p_watched:true,p_title:null})}}return sbRpc('cinetracker_set_episode_watched',{p_tmdb_id:id,p_season:s,p_episode:e,p_watched:true,p_title:title||null})}
document.addEventListener('click',async ev=>{const c=ev.target.closest?.('.ct47-card[data-type="tv"],[data-id]');if(c?.dataset.id)seriesId=Number(c.dataset.id)||seriesId;const b=ev.target.closest?.('.ct47-seen');if(!b)return;const row=b.closest('.ct47-ep');if(!row||!seriesId)return;ev.preventDefault();ev.stopPropagation();ev.stopImmediatePropagation();const w=b.dataset.seen!=='1';b.disabled=true;try{await smart(seriesId,Number(row.dataset.season),Number(row.dataset.episode),w,row.dataset.name);b.dataset.seen=w?'1':'0';b.classList.toggle('on',w);b.textContent=w?'✓':'○';toast('Progresso atualizado');setTimeout(()=>{try{render()}catch{}},120)}finally{b.disabled=false}},true);
function force3(){const on=typeof view!=='undefined'&&view==='discover';document.body.classList.toggle('ct50-discover',on);if(!on)return;const root=$('.content')||document;for(const p of $$('div,section',root)){const k=[...p.children];if(k.length<2)continue;let score=0;for(const x of k.slice(0,6))if(x.matches?.('.card,[class*="card"]')||x.querySelector?.('.poster,.tmdb-poster,[class*="poster"]'))score++;if(score>=2){p.classList.add('ct50-grid3');p.style.setProperty('display','grid','important');p.style.setProperty('grid-template-columns','repeat(3,minmax(0,1fr))','important')}}}
async function providers(type,id){const key=type+':'+id;if(providersCache.has(key))return providersCache.get(key);let out=[];try{const d=await tmdb(type,id,'/watch/providers'),br=d.results?.BR||{},arr=[...(br.flatrate||[]),...(br.free||[]),...(br.ads||[]),...(br.rent||[]),...(br.buy||[])];for(const p of arr)if(p.provider_name&&!out.includes(p.provider_name))out.push(p.provider_name);out=out.slice(0,5)}catch{}providersCache.set(key,out);return out}
async function hydrate(){for(const el of $$('.ct47-card[data-id],.ct47w-home-card[data-id],.ct49-home-card[data-id]').slice(0,18)){if(el.dataset.ct50p)return;const id=Number(el.dataset.id||0);if(!id)continue;el.dataset.ct50p='1';const type=el.dataset.type==='movie'||(el.textContent||'').includes('FILME')?'movie':'tv',ps=await providers(type,id);if(!ps.length)continue;const body=$('.ct47-body,.ct47w-home-body,.ct49-home-body',el)||el,d=document.createElement('div');d.className='ct50-provider';d.innerHTML='<b>Onde assistir:</b> '+ps.map(x=>`<span class="ct50-provider-chip">${x.replace(/[<>]/g,'')}</span>`).join('');body.appendChild(d)}}
async function refresh(){force3();await reorder();hydrate()}let q=false;new MutationObserver(()=>{if(q)return;q=true;requestAnimationFrame(()=>{q=false;refresh()})}).observe($('#app')||document.documentElement,{childList:true,subtree:true});setTimeout(refresh,100);setTimeout(refresh,600);window.ct50WebRefresh=refresh;
})();