(() => {
'use strict';
if(window.__ct44Loaded)return;window.__ct44Loaded=true;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>typeof escapeHtml==='function'?escapeHtml(String(v??'')):String(v??'');
const css=document.createElement('style');css.id='ct44-style';css.textContent=`
.ct44-settings{max-width:760px;margin:auto}.ct44-settings h1{margin:0 0 6px}.ct44-group{border:1px solid #202b35;background:#0b0f13;border-radius:16px;padding:14px;margin:12px 0}.ct44-group h2{font-size:15px;margin:0 0 12px}.ct44-field{display:grid;gap:6px;margin:10px 0}.ct44-field label{font-size:11px;color:#91a0ad}.ct44-field input{width:100%;border:1px solid #344453;background:#080c10;color:#fff;border-radius:11px;padding:11px}.ct44-actions{display:flex;gap:8px;flex-wrap:wrap}.ct44-btn{border:1px solid #34495c;background:#121b23;color:#fff;border-radius:11px;padding:10px 13px}.ct44-btn.primary{background:#173a5a;border-color:#3c7daf}.ct44-msg{font-size:11px;color:#aebbc6;margin-top:8px;min-height:16px}.ct44-version{text-align:center;color:#71808c;font-size:11px;padding:18px 0 6px}.ct44-analytics{margin-top:10px}.ct44-insights{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-bottom:12px}.ct44-insight{border:1px solid #203040;border-radius:13px;background:#0b1117;padding:10px;min-width:0}.ct44-insight span{display:block;color:#81909d;font-size:9px;text-transform:uppercase}.ct44-insight strong{display:block;margin-top:5px;font-size:16px;white-space:nowrap}.ct44-chart-wrap{border:1px solid #1d2b37;border-radius:14px;background:#090e12;padding:12px}.ct44-chart-title{display:flex;justify-content:space-between;align-items:center;font-size:11px;color:#91a0ad;margin-bottom:9px}.ct44-chart{height:118px;display:grid;grid-template-columns:repeat(24,minmax(0,1fr));align-items:end;gap:2px}.ct44-bar{min-height:3px;border-radius:3px 3px 0 0;background:currentColor;color:#5d8fb5;opacity:.8}.ct44-bar.peak{color:#d6b55b;opacity:1}.ct44-hours{display:flex;justify-content:space-between;color:#65727d;font-size:8px;margin-top:5px}.ct44-loading{padding:14px;color:#8796a2}.ct44-danger{border-color:#52313a}.ct44-note{color:#8796a2;font-size:10px;line-height:1.45}
@media(max-width:560px){.ct44-insights{grid-template-columns:repeat(3,minmax(0,1fr));gap:6px}.ct44-insight{padding:8px}.ct44-insight strong{font-size:13px}.ct44-chart{height:105px}}
`;document.head.appendChild(css);

async function authUpdate(body){if(!ctSession?.access_token)throw new Error('Sessão inválida');const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{method:'PUT',headers:{...authHeaders(),'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.msg||d.message||d.error_description||d.error||'Não foi possível atualizar a conta');if(d.access_token)saveSession(d);if(d.email&&currentUser)currentUser={...currentUser,...d};return d}
async function paged(path,pageSize=1000){const out=[];for(let offset=0;;offset+=pageSize){const sep=path.includes('?')?'&':'?';const rows=await sbApi(`${path}${sep}limit=${pageSize}&offset=${offset}`);if(Array.isArray(rows))out.push(...rows);if(!Array.isArray(rows)||rows.length<pageSize)break}return out}
async function exportAll(){const [profiles,media,overrides,history,progress,imports]=await Promise.all([paged('profiles?select=*'),paged('media?select=*'),paged('media_overrides?select=*'),paged('watch_history?select=*'),paged('episode_progress?select=*'),paged('import_batches?select=*')]);const payload={format:'CineTracker Backup',version:1,exported_at:new Date().toISOString(),profile_email:currentUser?.email||null,profiles,media,media_overrides:overrides,watch_history:history,episode_progress:progress,import_batches:imports};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`cinetracker-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
function settingsView(){const email=esc(currentUser?.email||'');const app=document.getElementById('app');app.innerHTML=`<div class="app"><main class="content"><div class="ct44-settings"><h1>Configurações</h1><p class="subtitle">Conta, segurança e seus dados.</p><section class="ct44-group"><h2>Conta</h2><div class="ct44-field"><label>E-mail atual</label><input value="${email}" disabled></div><div class="ct44-field"><label>Novo e-mail</label><input id="ct44-email" type="email" autocomplete="email" placeholder="novo@email.com"></div><div class="ct44-actions"><button class="ct44-btn primary" id="ct44-email-save">Alterar e-mail</button></div><div class="ct44-msg" id="ct44-email-msg"></div><p class="ct44-note">Dependendo da política da conta, o Supabase poderá pedir confirmação no e-mail novo antes da troca ser concluída.</p></section><section class="ct44-group"><h2>Senha</h2><div class="ct44-field"><label>Nova senha</label><input id="ct44-pass" type="password" autocomplete="new-password" placeholder="Nova senha"></div><div class="ct44-field"><label>Confirmar nova senha</label><input id="ct44-pass2" type="password" autocomplete="new-password" placeholder="Repita a nova senha"></div><div class="ct44-actions"><button class="ct44-btn primary" id="ct44-pass-save">Alterar senha</button></div><div class="ct44-msg" id="ct44-pass-msg"></div></section><section class="ct44-group"><h2>Dados</h2><div class="ct44-actions"><button class="ct44-btn" id="ct44-import">Importar dados</button><button class="ct44-btn" id="ct44-export">Exportar backup completo</button></div><div class="ct44-msg" id="ct44-data-msg"></div></section><div class="ct44-version">CineTracker Web 0.4.6 • Android build 0.0.33</div></div></main></div>`;
 $('#ct44-email-save').onclick=async()=>{const m=$('#ct44-email-msg'),email=$('#ct44-email').value.trim();m.textContent='Atualizando…';try{if(!email)throw new Error('Digite o novo e-mail.');await authUpdate({email});m.textContent='Solicitação de alteração enviada. Verifique o e-mail se houver confirmação pendente.'}catch(e){m.textContent=e.message||String(e)}};
 $('#ct44-pass-save').onclick=async()=>{const m=$('#ct44-pass-msg'),a=$('#ct44-pass').value,b=$('#ct44-pass2').value;m.textContent='Atualizando…';try{if(a.length<8)throw new Error('Use uma senha com pelo menos 8 caracteres.');if(a!==b)throw new Error('As senhas não coincidem.');await authUpdate({password:a});$('#ct44-pass').value=$('#ct44-pass2').value='';m.textContent='Senha alterada com sucesso.'}catch(e){m.textContent=e.message||String(e)}};
 $('#ct44-import').onclick=()=>{view='import';render();window.scrollTo(0,0)};
 $('#ct44-export').onclick=async()=>{const m=$('#ct44-data-msg');m.textContent='Preparando backup completo…';try{await exportAll();m.textContent='Backup exportado.'}catch(e){m.textContent='Falha ao exportar: '+(e.message||e)}};
}
window.ct44OpenSettings=()=>{view='settings';render();window.scrollTo(0,0);return true};
const priorRender=typeof render==='function'?render:null;if(priorRender&&!window.__ct44Render){window.__ct44Render=priorRender;render=function(){if(['settings','account','stats'].includes(view)){view='settings';settingsView();return}return window.__ct44Render()}}

function hourLabel(h){const n=Number(h||0);return `${String(n).padStart(2,'0')}:00–${String((n+1)%24).padStart(2,'0')}:00`}
function chartHtml(a){const by=Array(24).fill(0);for(const x of a.hourly||[])by[Number(x.hour)||0]=Number(x.count)||0;const mx=Math.max(1,...by),peak=Number(a.peak_hour)||0;return `<div class="ct44-analytics"><div class="ct44-insights"><div class="ct44-insight"><span>Horário de pico</span><strong>${hourLabel(peak)}</strong></div><div class="ct44-insight"><span>Dias ativos</span><strong>${Number(a.active_days||0).toLocaleString('pt-BR')}</strong></div><div class="ct44-insight"><span>Média / dia ativo</span><strong>${Number(a.avg_per_active_day||0).toLocaleString('pt-BR')}</strong></div></div><div class="ct44-chart-wrap"><div class="ct44-chart-title"><span>Atividade por horário</span><span>${Number(a.total_events||0).toLocaleString('pt-BR')} reproduções</span></div><div class="ct44-chart">${by.map((v,h)=>`<div class="ct44-bar${h===peak?' peak':''}" title="${String(h).padStart(2,'0')}h · ${v}" style="height:${Math.max(3,Math.round(v/mx*100))}%"></div>`).join('')}</div><div class="ct44-hours"><span>00h</span><span>06h</span><span>12h</span><span>18h</span><span>23h</span></div></div></div>`}
async function analytics(){try{return await sbRpc('cinetracker_watch_analytics',{})}catch{return null}}
async function enhanceProfile(){if(typeof view==='undefined'||view!=='profile')return;let body=$('#ct43-screen-body');if(!body||body.dataset.ct44)return;body.dataset.ct44='1';body.innerHTML='<div class="ct44-loading">Calculando seu padrão de exibição…</div>';const a=await analytics();if(typeof view==='undefined'||view!=='profile')return;body=$('#ct43-screen-body');if(!body)return;body.innerHTML=a?chartHtml(a):'<div class="ct44-loading">Não foi possível carregar o gráfico agora.</div>';const full=$('#ct43-screen-full');if(full)full.onclick=async()=>{const host=$('.content')||$('#app'),x=a||await analytics();host.innerHTML=`<div class="ct43-full"><button class="ct43-back" id="ct44-back">← Perfil</button><h1>Tempo de Tela</h1>${x?chartHtml(x):'<div class="ct44-loading">Sem dados analíticos.</div>'}<div class="ct43-full-grid"><div class="ct43-metric"><span>Tempo total</span><strong>${esc(metricVal('tempo total'))}</strong></div><div class="ct43-metric"><span>Tempo em séries</span><strong>${esc(metricVal('tempo em séries'))}</strong></div><div class="ct43-metric"><span>Tempo em filmes</span><strong>${esc(metricVal('tempo em filmes'))}</strong></div><div class="ct43-metric"><span>Episódios vistos</span><strong>${Number(x?.episodes||0).toLocaleString('pt-BR')}</strong></div><div class="ct43-metric"><span>Filmes vistos</span><strong>${Number(x?.movies||0).toLocaleString('pt-BR')}</strong></div></div></div>`;$('#ct44-back').onclick=()=>{view='profile';render();window.scrollTo(0,0)}}}
function metricVal(label){const cards=$$('.ct41-stat,.ct30-stat');const c=cards.find(x=>(x.querySelector('span')?.textContent||'').toLowerCase().includes(label));return c?.querySelector('strong')?.textContent?.trim()||'—'}
function run(){if(!currentUser)return;enhanceProfile();$$('[data-view="stats"]').forEach(x=>x.remove());$$('[data-view="account"]').forEach(x=>{x.dataset.view='settings';x.textContent=x.closest('.mobile-nav')?'Config.':'⚙ Configurações'})}
let q=false;new MutationObserver(()=>{if(q)return;q=true;requestAnimationFrame(()=>{q=false;run()})}).observe($('#app')||document.documentElement,{childList:true,subtree:true});setTimeout(run,0);setTimeout(run,500);
})();