(() => {
'use strict';
const esc=v=>typeof escapeHtml==='function'?escapeHtml(String(v??'')):String(v??'');
const poster=p=>p?`https://image.tmdb.org/t/p/w342${p}`:'';
const css=document.createElement('style');css.id='ct43-style';css.textContent=`
.ct43-block{margin:22px 0;border-top:1px solid #202933;padding-top:16px}.ct43-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.ct43-title{display:flex;align-items:center;gap:8px;font-size:19px;font-weight:800}.ct43-open,.ct43-toggle{border:0;background:transparent;color:#dfe8f1;font-size:24px;padding:4px 6px}.ct43-body{margin-top:12px}.ct43-body.collapsed{display:none}.ct43-strip{display:grid;grid-auto-flow:column;grid-auto-columns:minmax(145px,175px);gap:9px;overflow-x:auto;padding:0 0 8px;scroll-snap-type:x proximity}.ct43-metric{min-height:120px;border:1px solid #172b3d;background:#0b0d10;border-radius:14px;padding:12px;scroll-snap-align:start;display:flex;flex-direction:column;justify-content:space-between}.ct43-metric span{color:#8f98a3;font-size:11px}.ct43-metric strong{font-size:20px;white-space:nowrap}.ct43-history-card{width:150px;scroll-snap-align:start}.ct43-history-poster{aspect-ratio:16/10;border-radius:12px;background:#101820 center/cover no-repeat}.ct43-history-card strong{display:block;font-size:11px;margin-top:6px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ct43-history-card span{font-size:9px;color:#8f98a3}.ct43-full{min-height:70vh}.ct43-back{border:1px solid #273746;background:#0d1218;color:white;border-radius:11px;padding:9px 12px}.ct43-full-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:18px}.ct43-full .ct43-metric{min-height:130px}.ct43-settings-fix .eyebrow{display:none!important}
@media(max-width:560px){.ct43-title{font-size:18px}.ct43-strip{grid-auto-columns:150px}.ct43-metric strong{font-size:18px}}
`;
document.head.appendChild(css);

/* Remove a antiga rota Stats: account passa a ser Configurações. */
if(typeof render==='function'&&!window.__ct43Render){window.__ct43Render=render;render=function(){if(typeof view!=='undefined'&&view==='account')view='settings';return window.__ct43Render()}}

/* Cache curto das leituras para troca rápida entre abas. */
if(typeof sbApi==='function'&&!window.__ct43SbApi){window.__ct43SbApi=sbApi;const cache=new Map();sbApi=async function(path,opts={}){const method=String(opts.method||'GET').toUpperCase();if(method!=='GET')return window.__ct43SbApi(path,opts);const key=path;const hit=cache.get(key);if(hit&&Date.now()-hit.t<30000)return hit.v;const v=await window.__ct43SbApi(path,opts);cache.set(key,{t:Date.now(),v});return v}}

const tcache=new Map();let active=0;const queue=[];function pump(){while(active<4&&queue.length){const fn=queue.shift();active++;Promise.resolve().then(fn).finally(()=>{active--;pump()})}}function enqueue(fn){queue.push(fn);pump()}
async function tmdb(path,params={}){const key=path+JSON.stringify(params);if(tcache.has(key))return tcache.get(key);const u=new URL(`${SUPABASE_URL}/functions/v1/tmdb-proxy`);u.searchParams.set('path',path);for(const[k,v]of Object.entries(params))u.searchParams.set(k,String(v));const r=await fetch(u,{headers:authHeaders()});if(!r.ok)throw new Error('TMDB '+r.status);const d=await r.json();tcache.set(key,d);return d}
function cardInfo(card){const mid=card.dataset.mediaId||'';let item=null;try{item=mediaRegistry?.get?.(mid)}catch{};let id=Number(item?.tmdbId||card.dataset.tmdbId||card.dataset.ct29Id||card.dataset.ct30Id||0),type=String(item?.apiType||card.dataset.apiType||card.dataset.ct29Type||card.dataset.ct30Type||'').toLowerCase();const m=mid.match(/^tmdb-(movie|tv)-(\d+)$/);if(!id&&m){type=m[1];id=Number(m[2])}type=(type.includes('movie')||type.includes('filme'))?'movie':'tv';const titleEl=card.querySelector('h3,h2,.ct38-title,.ct30-fav-body strong,.ct30-history-body strong,strong');const title=(item?.title||titleEl?.textContent||'').trim();return{id,type,title,titleEl,item}}
function hydrateAll(){if(!currentUser)return;document.querySelectorAll('.card,.feature,.ct38-card,.ct30-fav,.ct30-history-card,.ct30-follow-card').forEach(card=>{if(card.dataset.ct43)return;const p=card.querySelector('.poster,.tmdb-poster,.ct38-poster,.ct30-fav-poster,.ct30-history-poster,.ct30-follow-poster');if(!p)return;const rect=card.getBoundingClientRect();if(rect.bottom<-500||rect.top>innerHeight+800)return;const info=cardInfo(card);const existing=info.item?.posterUrl||info.item?.poster_path;if(existing){p.style.backgroundImage=existing.startsWith('/')?`url('${poster(existing)}')`:`url('${existing}')`;p.style.backgroundSize='cover';p.style.backgroundPosition='center 18%';if(info.titleEl&&info.item?.title)info.titleEl.textContent=info.item.title;card.dataset.ct43='1';return}card.dataset.ct43='1';enqueue(async()=>{try{let d=null;if(info.id)d=await tmdb(`/${info.type}/${info.id}`,{language:'pt-BR'});else if(info.title){const s=await tmdb(`/search/${info.type}`,{query:info.title,language:'pt-BR',include_adult:false,page:1});d=(s.results||[])[0]||null}if(!d)return;const name=d.title||d.name;if(name&&info.titleEl)info.titleEl.textContent=name;if(d.poster_path){p.style.backgroundImage=`url('${poster(d.poster_path)}')`;p.style.backgroundSize='cover';p.style.backgroundPosition='center 18%'}}catch{card.dataset.ct43=''}})})}

function metricValue(label){const cards=[...document.querySelectorAll('.ct41-stat,.ct30-stat')];const c=cards.find(x=>(x.querySelector('span')?.textContent||'').toLowerCase().includes(label));return c?.querySelector('strong')?.textContent?.trim()||'—'}
async function recentHistory(){try{return await sbApi('watch_history?select=item_type,watched_at,title,media:media(tmdb_id,media_type,title,poster_path)&order=watched_at.desc&limit=12')}catch{return[]}}
function insertProfileBlocks(){if(typeof view!=='undefined'&&view!=='profile')return;if(document.getElementById('ct43-profile'))return;const fav=[...document.querySelectorAll('section,.ct29-section')].find(s=>/séries favoritas/i.test(s.querySelector('h2')?.textContent||''));if(!fav)return;const root=document.createElement('div');root.id='ct43-profile';root.innerHTML=`<section class="ct43-block"><div class="ct43-head"><button class="ct43-open" id="ct43-screen-full">Tempo de Tela ›</button><button class="ct43-toggle" data-target="ct43-screen-body">⌃</button></div><div class="ct43-body" id="ct43-screen-body"><div class="ct43-strip"><div class="ct43-metric"><span>Tempo total</span><strong>${esc(metricValue('tempo total'))}</strong></div><div class="ct43-metric"><span>Tempo em séries</span><strong>${esc(metricValue('tempo em séries'))}</strong></div><div class="ct43-metric"><span>Tempo em filmes</span><strong>${esc(metricValue('tempo em filmes'))}</strong></div><div class="ct43-metric"><span>Episódios vistos</span><strong>${esc(metricValue('episódios'))}</strong></div><div class="ct43-metric"><span>Filmes vistos</span><strong>${esc(metricValue('filmes'))}</strong></div></div></div></section><section class="ct43-block"><div class="ct43-head"><button class="ct43-open" id="ct43-history-full">Histórico ›</button><button class="ct43-toggle" data-target="ct43-history-body">⌃</button></div><div class="ct43-body" id="ct43-history-body"><div class="ct43-strip"><div class="ct43-metric"><span>Carregando histórico…</span></div></div></div></section>`;fav.before(root);root.querySelectorAll('.ct43-toggle').forEach(b=>b.onclick=()=>{const el=document.getElementById(b.dataset.target);el?.classList.toggle('collapsed');b.textContent=el?.classList.contains('collapsed')?'⌄':'⌃'});document.getElementById('ct43-history-full').onclick=()=>{view='history';render()};document.getElementById('ct43-screen-full').onclick=()=>openScreenFull();recentHistory().then(rows=>{const body=document.querySelector('#ct43-history-body .ct43-strip');if(!body)return;body.innerHTML=rows.length?rows.map(r=>{const m=r.media||{};return`<article class="ct43-history-card"><div class="ct43-history-poster"${m.poster_path?` style="background-image:url('${poster(m.poster_path)}')"`:''}></div><strong>${esc(r.title||m.title||'Sem título')}</strong><span>${new Date(r.watched_at).toLocaleDateString('pt-BR')}</span></article>`}).join(''):'<div class="ct43-metric"><span>Nenhum histórico recente</span></div>';hydrateAll()})}
function openScreenFull(){const c=document.querySelector('.content')||document.getElementById('app');if(!c)return;c.innerHTML=`<div class="ct43-full"><button class="ct43-back" id="ct43-back">← Perfil</button><h1>Tempo de Tela</h1><div class="ct43-full-grid"><div class="ct43-metric"><span>Tempo total</span><strong>${esc(metricValue('tempo total'))}</strong></div><div class="ct43-metric"><span>Tempo em séries</span><strong>${esc(metricValue('tempo em séries'))}</strong></div><div class="ct43-metric"><span>Tempo em filmes</span><strong>${esc(metricValue('tempo em filmes'))}</strong></div><div class="ct43-metric"><span>Episódios vistos</span><strong>${esc(metricValue('episódios'))}</strong></div><div class="ct43-metric"><span>Filmes vistos</span><strong>${esc(metricValue('filmes'))}</strong></div><div class="ct43-metric"><span>Séries acompanhadas</span><strong>${esc(metricValue('séries'))}</strong></div></div></div>`;document.getElementById('ct43-back').onclick=()=>{view='profile';render()}}
function run(){if(!currentUser)return;insertProfileBlocks();hydrateAll();if(typeof view!=='undefined'&&view==='settings')document.body.classList.add('ct43-settings-fix');else document.body.classList.remove('ct43-settings-fix')}
let q=false;new MutationObserver(()=>{if(q)return;q=true;requestAnimationFrame(()=>{q=false;run()})}).observe(document.getElementById('app')||document.documentElement,{childList:true,subtree:true});setTimeout(run,0);setTimeout(run,400);
})();
