(() => {
'use strict';
if(window.__ct49WebLoaded)return;window.__ct49WebLoaded=true;
const VERSION='0.4.9',$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const esc=v=>typeof escapeHtml==='function'?escapeHtml(String(v??'')):String(v??'');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));

/* Dedupe/cache de leituras para pré-carregar sem tempestade de requests. */
const rawFetch=window.fetch.bind(window),mem=new Map(),inflight=new Map(),TTL=120000;
function fkey(input,init={}){const u=typeof input==='string'?input:input?.url||'',m=String(init.method||(typeof input!=='string'&&input?.method)||'GET').toUpperCase(),b=typeof init.body==='string'?init.body:'';return `${m}|${u}|${b}`}
function cacheable(input,init={}){const u=typeof input==='string'?input:input?.url||'',m=String(init.method||(typeof input!=='string'&&input?.method)||'GET').toUpperCase();if(m==='GET'&&(/\/rest\/v1\//.test(u)||/\/functions\/v1\/tmdb-(proxy|image)/.test(u)))return true;if(m==='POST'&&/\/rpc\/(cinetracker_continue_items_v2|cinetracker_episode_state|cinetracker_watch_daily_timeline)/.test(u))return true;return false}
window.fetch=async function(input,init={}){if(!cacheable(input,init))return rawFetch(input,init);const k=fkey(input,init),h=mem.get(k);if(h&&Date.now()-h.t<TTL)return h.r.clone();if(inflight.has(k))return (await inflight.get(k)).clone();const p=rawFetch(input,init).then(r=>{if(r.ok)mem.set(k,{t:Date.now(),r:r.clone()});return r}).finally(()=>inflight.delete(k));inflight.set(k,p);return (await p).clone()};

const style=document.createElement('style');style.id='ct49w-style';style.textContent=`
.ct49w-series-progress{font-size:11px!important;line-height:1.45!important;color:#92a4b2!important;margin-top:6px!important}.ct49w-thumb{width:54px;height:78px;flex:0 0 54px;border-radius:8px;background:#101820 center/cover no-repeat}.ct49w-library-row{display:flex!important;align-items:center!important;gap:10px!important}.ct49w-hidden{display:none!important}.ct49w-preloaded img{content-visibility:auto}.ct49w-profile-graph{order:50}.ct43-block:has(#ct43-history-body){order:60}
`;
document.head.appendChild(style);

let continueRows=null,knownIds=new Set(),knownTitles=new Set(),progressMap=new Map(),warmStarted=false;
function mid(type,id){return `tmdb-${type}-${Number(id)}`}
async function loadUniverse(force=false){if(continueRows&&!force)return continueRows;const [cont,over]=await Promise.all([
  sbRpc('cinetracker_continue_items_v2',{}).catch(()=>[]),
  sbApi('media_overrides?select=state,media:media(tmdb_id,media_type,title)&limit=5000').catch(()=>[])
]);continueRows=cont||[];knownIds=new Set();knownTitles=new Set();progressMap=new Map();for(const r of continueRows){if(r.tmdb_id){knownIds.add(mid('tv',r.tmdb_id));progressMap.set(Number(r.tmdb_id),r)}if(r.title)knownTitles.add(norm(r.title))}for(const r of over||[]){const m=r?.media;if(!m)continue;if(m.tmdb_id&&m.media_type)knownIds.add(mid(m.media_type,m.tmdb_id));if(m.title)knownTitles.add(norm(m.title))}return continueRows}
function cardInfo(card){const raw=card.dataset.mediaId||'',mm=raw.match(/^tmdb-(movie|tv)-(\d+)$/);let id=Number(card.dataset.tmdbId||card.dataset.id||card.dataset.ct29Id||card.dataset.ct30Id||0),type=String(card.dataset.apiType||card.dataset.type||'').toLowerCase();if(mm){type=mm[1];id=Number(mm[2])}const txt=(card.textContent||'').toLowerCase();if(!type)type=/\bfilme\b/.test(txt)?'movie':'tv';type=type.includes('movie')?'movie':'tv';const title=(card.querySelector('h1,h2,h3,.ct46w-title,.ct48-home-title,.ct47-title,strong')?.textContent||'').trim();return{id,type,title,raw}}
async function epState(id){try{return await sbRpc('cinetracker_episode_state',{p_tmdb_id:id})||[]}catch{return[]}}
async function tmdbDetail(id){const u=new URL(`${SUPABASE_URL}/functions/v1/tmdb-proxy`);u.searchParams.set('path',`/tv/${id}`);u.searchParams.set('language','pt-BR');const r=await fetch(u,{headers:typeof authHeaders==='function'?authHeaders():{}});if(!r.ok)return null;return r.json()}
async function progressText(id){const row=progressMap.get(Number(id));let watched=Number(row?.watched_episodes||0),total=Number(row?.total_episodes||0),season=Number(row?.season_number||row?.current_season||row?.last_season||0),episode=Number(row?.episode_number||row?.current_episode||row?.last_episode||0);if(!season||!episode||!total){const [states,d]=await Promise.all([epState(id),tmdbDetail(id).catch(()=>null)]);const ws=(states||[]).filter(x=>x.watched).sort((a,b)=>Number(a.season_number)-Number(b.season_number)||Number(a.episode_number)-Number(b.episode_number));const last=ws[ws.length-1];if(last){season=Number(last.season_number)||season;episode=Number(last.episode_number)||episode;watched=Math.max(watched,ws.length)}total=total||Number(d?.number_of_episodes||0)}if(!season)season=1;if(!episode)episode=watched?1:0;const left=Math.max(0,total-watched);return `Temporada ${season} • Episódio ${episode} • ${watched}/${total||'?'} • Faltam ${total?left:'?'} episódios`}
const progPending=new WeakSet();function decorateSeries(){const cards=$$('.card,.feature,.ct46w-card,.ct48-home-card,.ct47-card,.ct30-follow-card,.ct30-history-card,[data-media-id],[data-tmdb-id]');for(const c of cards){const i=cardInfo(c);if(i.type!=='tv'||!i.id||progPending.has(c))continue;progPending.add(c);let el=$('.ct49w-series-progress',c);if(!el){el=document.createElement('div');el.className='ct49w-series-progress';const host=$('.media-meta,.ct46w-meta,.ct48-home-meta,.ct47-meta,.ct30-follow-body,.card-body',c)||c;host.insertAdjacentElement(host.matches('.card-body,.ct30-follow-body')?'afterbegin':'afterend',el)}progressText(i.id).then(t=>el.textContent=t).catch(()=>{el.textContent='Progresso indisponível'}).finally(()=>progPending.delete(c))}}

function ensureWatchlistHome(){if(typeof view==='undefined'||view!=='home')return;if($$('h2').some(h=>/da sua watchlist/i.test(h.textContent||'')))return;if(typeof currentWatchlistPicks!=='function'||typeof mediaCard!=='function')return;const picks=currentWatchlistPicks();if(!picks.length)return;const host=$('.content');if(!host)return;const s=document.createElement('section');s.className='section';s.innerHTML=`<div class="section-title"><div><h2>Da sua Watchlist</h2><p class="subtitle">Um filme, uma série e um anime quando disponíveis.</p></div></div><div class="grid">${picks.slice(0,3).map(x=>mediaCard(x)).join('')}</div>`;const first=$('.section',host);first?.after(s);try{bindMediaActions?.();hydrateMediaDetails?.()}catch{}}
function libraryImages(){if(typeof view==='undefined'||view!=='library')return;try{window.ct45WebResolve?.()}catch{}for(const row of $$('.list-item')){if(row.querySelector('.ct49w-thumb'))continue;const title=(row.querySelector('strong')?.textContent||'').trim();let item=null;try{for(const x of mediaRegistry.values())if(norm(x.title)===norm(title)){item=x;break}}catch{}const p=item?.posterUrl||item?.poster_path;if(!p)continue;const url=/^https?:/.test(p)?p:`${SUPABASE_URL}/functions/v1/tmdb-image?path=${encodeURIComponent(p)}&size=w342`;const th=document.createElement('div');th.className='ct49w-thumb';th.style.backgroundImage=`url('${url}')`;row.classList.add('ct49w-library-row');row.prepend(th)}}
function filterDiscover(){if(typeof view==='undefined'||view!=='discover')return;for(const c of $$('.card,.feature,[data-media-id]')){const i=cardInfo(c),key=i.id?mid(i.type,i.id):i.raw,blocked=(key&&knownIds.has(key))||(i.title&&knownTitles.has(norm(i.title)));c.classList.toggle('ct49w-hidden',!!blocked)}}
function cleanNav(){for(const b of $$('[data-view="import"]'))b.remove();for(const b of $$('.nav button,.mobile-nav button'))if(/^\s*(⇧\s*)?importar\s*$/i.test(b.textContent||''))b.remove()}
function profileParity(){if(typeof view==='undefined'||view!=='profile')return;for(const el of $$('section,div,h2,h3,strong,span'))if(/hor[aá]rio de pico/i.test(el.textContent||'')&&el.children.length<8)(el.closest('section')||el).remove();const graph=$('.ct46w-timeline,#ct43-screen-body'),hist=$('#ct43-history-body')?.closest('.ct43-block');if(graph&&hist){const g=graph.closest('.ct43-block')||graph;g.classList.add('ct49w-profile-graph');hist.parentElement?.insertBefore(g,hist)}}
async function preloadImages(){const urls=[];try{for(const x of mediaRegistry.values()){const p=x.posterUrl||x.poster_path;if(!p)continue;urls.push(/^https?:/.test(p)?p:`${SUPABASE_URL}/functions/v1/tmdb-image?path=${encodeURIComponent(p)}&size=w342`)}}catch{}await Promise.allSettled(urls.slice(0,36).map(u=>new Promise(res=>{const im=new Image();im.onload=im.onerror=res;im.src=u})))}
async function warm(){if(warmStarted||!currentUser)return;warmStarted=true;await Promise.allSettled([loadUniverse(true),typeof loadCloudState==='function'?loadCloudState():null]);await Promise.race([preloadImages(),sleep(2200)]);document.body.classList.add('ct49w-preloaded');run()}
function run(){if(!currentUser)return;cleanNav();ensureWatchlistHome();libraryImages();filterDiscover();profileParity();decorateSeries()}
const prior=typeof render==='function'?render:null;if(prior&&!window.__ct49wRender){window.__ct49wRender=prior;render=function(){if(view==='import')view='settings';const r=window.__ct49wRender();setTimeout(run,0);setTimeout(run,180);return r}}
let q=false;new MutationObserver(()=>{if(q)return;q=true;requestAnimationFrame(()=>{q=false;run()})}).observe($('#app')||document.documentElement,{childList:true,subtree:true});
setTimeout(()=>void warm(),80);setTimeout(run,250);
})();
