(() => {
'use strict';
if(window.__ct50WebLoaded)return;window.__ct50WebLoaded=true;
const VERSION='0.5.0',$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const rowCache=new Map(),detailCache=new Map(),stateCache=new Map();
function normalize(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
async function loadRows(){try{const rows=await sbRpc('cinetracker_continue_items_v2',{})||[];rowCache.clear();for(const r of rows)if(r.tmdb_id)rowCache.set(Number(r.tmdb_id),r)}catch{}}
async function state(id){if(stateCache.has(id))return stateCache.get(id);const p=sbRpc('cinetracker_episode_state',{p_tmdb_id:id}).catch(()=>[]);stateCache.set(id,p);return p}
async function detail(id){if(detailCache.has(id))return detailCache.get(id);const p=(async()=>{const u=new URL(`${SUPABASE_URL}/functions/v1/tmdb-proxy`);u.searchParams.set('path',`/tv/${id}`);u.searchParams.set('language','pt-BR');const r=await fetch(u,{headers:typeof authHeaders==='function'?authHeaders():{}});if(!r.ok)throw new Error('TMDB '+r.status);return r.json()})();detailCache.set(id,p);return p}
function info(card){const raw=card.dataset.mediaId||'',m=raw.match(/^tmdb-(movie|tv)-(\d+)$/);let id=Number(card.dataset.tmdbId||card.dataset.id||card.dataset.ct29Id||card.dataset.ct30Id||0),type=String(card.dataset.apiType||card.dataset.type||'').toLowerCase();if(m){type=m[1];id=Number(m[2])}if(!type)type=/\bfilme\b/i.test(card.textContent||'')?'movie':'tv';return{id,type:type.includes('movie')?'movie':'tv'}}
async function progress(id){const r=rowCache.get(Number(id));let watched=Number(r?.watched_episodes||0),total=Number(r?.total_episodes||0),season=Number(r?.season_number||r?.current_season||r?.last_season||0),episode=Number(r?.episode_number||r?.current_episode||r?.last_episode||0);if(!season||!episode||!total){const [states,d]=await Promise.all([state(id),detail(id).catch(()=>null)]),ws=(states||[]).filter(x=>x.watched).sort((a,b)=>Number(a.season_number)-Number(b.season_number)||Number(a.episode_number)-Number(b.episode_number)),last=ws[ws.length-1];if(last){season=Number(last.season_number)||season;episode=Number(last.episode_number)||episode;watched=Math.max(watched,ws.length)}total=total||Number(d?.number_of_episodes||0)}if(!season)season=1;if(!episode)episode=watched?1:0;return `Temporada ${season} • Episódio ${episode} • ${watched}/${total||'?'} • Faltam ${total?Math.max(0,total-watched):'?'} episódios`}
const running=new WeakSet();function applySeriesProgress(){for(const c of $$('.card,.feature,.ct46w-card,.ct48-home-card,.ct47-card,.ct30-follow-card,.ct30-history-card,.ct43-history-card,[data-media-id],[data-tmdb-id]')){const i=info(c);if(i.type!=='tv'||!i.id||running.has(c))continue;running.add(c);const old=$$('.ct49w-series-progress,.ct50w-series-progress',c);old.slice(1).forEach(x=>x.remove());let el=old[0];if(!el){el=document.createElement('div');el.className='ct50w-series-progress';const host=$('.ct48-home-meta,.ct47-meta,.ct46w-meta,.media-meta,.ct30-follow-body,.ct30-history-body,.card-body',c)||c;host.insertAdjacentElement(host.matches('.card-body,.ct30-follow-body,.ct30-history-body')?'afterbegin':'afterend',el)}el.className='ct50w-series-progress';progress(i.id).then(t=>{if(el.textContent!==t)el.textContent=t}).finally(()=>running.delete(c))}}
function removeHomeCalendar(){if(typeof view==='undefined'||view!=='home')return;for(const el of $$('section,.panel,.ct41-calendar,.ct41-block,.calendar')){const t=normalize(el.textContent);if((t.includes('calendario')&&t.includes('lancamento'))||t.includes('calendario das series'))el.remove()}}
function nav(){const navs=$$('.nav,.mobile-nav');for(const n of navs){const cfg=$$('button',n).filter(b=>normalize(b.textContent).includes('configur'));if(cfg.length){const keep=cfg[0];keep.dataset.view='settings';keep.onclick=e=>{e.preventDefault();e.stopPropagation();window.view='settings';typeof render==='function'&&render();window.scrollTo(0,0)};cfg.slice(1).forEach(x=>x.remove())}for(const b of $$('button',n)){if(normalize(b.textContent)==='importar')b.remove();if(b.dataset.view){b.onclick=e=>{e.preventDefault();e.stopPropagation();window.view=b.dataset.view;typeof render==='function'&&render();window.scrollTo(0,0)}}}}
function settingsFooter(){if(typeof view==='undefined'||view!=='settings')return;const host=$('.content')||$('#app');if(!host)return;for(const x of $$('*',host)){if(x.children.length===0){const t=(x.textContent||'').trim();if(/^0\.\d+(?:\.\d+)?$/.test(t)&&/\b(?:Versão|Build)\b/i.test(x.parentElement?.textContent||''))x.textContent=VERSION;if(/CineTracker Web\s*(?:•|-)?\s*(?:vers[aã]o|build)?\s*0\./i.test(t)&&!x.classList.contains('ct-version-footer'))x.remove()}}let f=$('.ct-version-footer',host);if(!f){f=document.createElement('div');f.className='ct-version-footer';f.style.cssText='margin:28px 0 8px;text-align:center;color:#71808b;font-size:11px';host.appendChild(f)}const txt=`CineTracker Web • versão ${VERSION}`;if(f.textContent!==txt)f.textContent=txt}
function run(){if(!currentUser)return;nav();removeHomeCalendar();settingsFooter();applySeriesProgress()}
const style=document.createElement('style');style.textContent='.ct50w-series-progress{font-size:11px!important;line-height:1.45!important;color:#92a4b2!important;margin-top:6px!important;white-space:normal!important}';document.head.appendChild(style);
const prior=typeof render==='function'?render:null;if(prior&&!window.__ct50wRender){window.__ct50wRender=prior;render=function(){const r=window.__ct50wRender();setTimeout(run,0);setTimeout(run,120);return r}}
let q=false;new MutationObserver(()=>{if(q)return;q=true;setTimeout(()=>{q=false;run()},100)}).observe($('#app')||document.documentElement,{childList:true,subtree:true});
setTimeout(async()=>{await loadRows();run()},80);window.ct50WebRefresh=async()=>{stateCache.clear();await loadRows();run()};
})();