(() => {
'use strict';
if(window.__ct47WebLoaded)return;window.__ct47WebLoaded=true;
const VERSION='0.4.9',$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>typeof escapeHtml==='function'?escapeHtml(String(v??'')):String(v??'');
const img=p=>p?`${SUPABASE_URL}/functions/v1/tmdb-image?path=${encodeURIComponent(p)}&size=w342`:'';
const css=document.createElement('style');css.id='ct47w-sync-style';css.textContent=`
.ct47w-home-list{display:grid;grid-auto-flow:column;grid-auto-columns:minmax(260px,34%);gap:10px;overflow-x:auto;scroll-snap-type:x mandatory;scrollbar-width:none}.ct47w-home-list::-webkit-scrollbar{display:none}.ct47w-home-card{display:grid;grid-template-columns:92px minmax(0,1fr);min-height:128px;border:1px solid #1d3040;background:#11171c;border-radius:14px;overflow:hidden;scroll-snap-align:start}.ct47w-home-poster{background:#0b1721 center/cover no-repeat}.ct47w-home-body{padding:11px;min-width:0}.ct47w-home-title{font-size:14px;font-weight:700}.ct47w-home-meta{font-size:10px;color:#8b98a3;margin-top:6px}.ct47w-check{margin-top:10px;border:1px solid #375168;background:#0b131b;color:#dce6ee;border-radius:10px;padding:8px 10px;font-size:10px;white-space:nowrap}.ct47w-check:disabled{opacity:.55}.ct47w-check.done{background:#153a25;border-color:#39754d;color:#a7dfb5}
body.ct47w-discover .content .ct47w-force3{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:9px!important}.ct47w-force3>.card{min-width:0!important}.ct47w-force3>.card .poster,.ct47w-force3>.card .tmdb-poster{height:auto!important;min-height:0!important;aspect-ratio:2/3!important}.ct47w-force3>.card .card-body{padding:8px!important}.ct47w-force3>.card .card-actions,.ct47w-force3>.card .cast,.ct47w-force3>.card .availability{display:none!important}
@media(max-width:650px){.ct47w-home-list{grid-auto-columns:84%}body.ct47w-discover .content .ct47w-force3{gap:7px!important}.ct47w-force3>.card h3{font-size:10px!important}.ct47w-force3>.card .media-meta{font-size:8px!important}}
`;
document.head.appendChild(css);
let rowsCache=null,metaCache=new Map();
async function rows(){if(rowsCache)return rowsCache;try{rowsCache=await sbRpc('cinetracker_continue_items_v2',{})||[]}catch{rowsCache=await sbRpc('cinetracker_continue_items',{})||[]}return rowsCache}
function following(list){return (list||[]).filter(x=>x.status==='following'||(!['up_to_date','dusty','not_started'].includes(x.status)&&Number(x.watched_episodes||0)>0))}
async function detail(id){if(metaCache.has(id))return metaCache.get(id);const u=new URL(`${SUPABASE_URL}/functions/v1/tmdb-proxy`);u.searchParams.set('path',`/tv/${id}`);u.searchParams.set('language','pt-BR');const r=await fetch(u,{headers:authHeaders()});if(!r.ok)throw new Error('TMDB '+r.status);const d=await r.json();metaCache.set(id,d);return d}
async function nextEp(r){const d=await detail(Number(r.tmdb_id));let n=Number(r.watched_episodes||0);const ss=(d.seasons||[]).filter(s=>s.season_number>0).sort((a,b)=>a.season_number-b.season_number);for(const s of ss){const c=Number(s.episode_count||0);if(n>=c){n-=c;continue}return{season:Number(s.season_number),episode:n+1}}return null}
async function markNext(btn,r){btn.disabled=true;try{const ep=await nextEp(r);if(!ep)throw new Error('Nenhum próximo episódio disponível.');let title=`${r.title||'Série'} S${ep.season}E${ep.episode}`;try{const u=new URL(`${SUPABASE_URL}/functions/v1/tmdb-proxy`);u.searchParams.set('path',`/tv/${Number(r.tmdb_id)}/season/${ep.season}`);u.searchParams.set('language','pt-BR');const rr=await fetch(u,{headers:authHeaders()});if(rr.ok){const sd=await rr.json(),x=(sd.episodes||[]).find(e=>Number(e.episode_number)===ep.episode);if(x?.name)title=x.name}}catch{}await sbRpc('cinetracker_set_episode_watched',{p_tmdb_id:Number(r.tmdb_id),p_season:ep.season,p_episode:ep.episode,p_watched:true,p_title:title});btn.textContent='✓ Marcado';btn.classList.add('done');rowsCache=null;setTimeout(refresh,250)}catch{btn.textContent='Falha';setTimeout(()=>{btn.disabled=false;btn.textContent='✓ Próximo episódio'},1200)}}
function homeCard(r){return `<article class="ct47w-home-card"><div class="ct47w-home-poster"${r.poster_path?` style="background-image:url('${img(r.poster_path)}')"`:''}></div><div class="ct47w-home-body"><div class="ct47w-home-title">${esc(r.title||`TMDB #${r.tmdb_id}`)}</div><div class="ct47w-home-meta">${r.media_kind==='anime'?'ANIME':'SÉRIE'} · ${Number(r.watched_episodes||0)}/${r.total_episodes||'?'}</div><button class="ct47w-check" data-ct47w-check="${Number(r.tmdb_id)}">✓ Próximo episódio</button></div></article>`}
async function fixHome(){if(typeof view==='undefined'||view!=='home')return;const sec=$$('.section,section').find(s=>/Continuar assistindo/i.test(s.querySelector('h2')?.textContent||''));if(!sec)return;const list=following(await rows());sec.innerHTML=`<div class="section-title"><h2>Continuar assistindo</h2><span class="eyebrow">ACOMPANHANDO</span></div>${list.length?`<div class="ct47w-home-list">${list.map(homeCard).join('')}</div>`:'<div class="ct46w-empty">Nenhum título em andamento.</div>'}`;list.forEach(r=>{const b=sec.querySelector(`[data-ct47w-check="${Number(r.tmdb_id)}"]`);if(b)b.onclick=e=>{e.stopPropagation();markNext(b,r)}})}
async function fixAssist(){if(typeof view==='undefined'||view!=='assist')return;const list=following(await rows());for(const r of list){const card=$(`.ct46w-section[data-section="following"] .ct46w-card[data-id="${Number(r.tmdb_id)}"]`);if(!card||card.querySelector('.ct47w-check'))continue;const body=card.querySelector('.ct46w-body');if(!body)continue;const b=document.createElement('button');b.className='ct47w-check';b.textContent='✓ Próximo episódio';b.onclick=e=>{e.stopPropagation();markNext(b,r)};body.appendChild(b)}}
function fixDiscover(){const on=typeof view!=='undefined'&&view==='discover';document.body.classList.toggle('ct47w-discover',on);if(!on)return;const root=$('.content');if(!root)return;for(const el of $$('div,section',root)){const direct=[...el.children].filter(c=>c.classList?.contains('card'));if(direct.length>=2)el.classList.add('ct47w-force3')}}
function fixVersion(){if(typeof view==='undefined'||view!=='settings')return;const root=$('#app');if(!root)return;for(const el of $$('*',root)){if(el.children.length===0&&/CineTracker Web\s+0\.4\.\d+/i.test(el.textContent||''))el.textContent=(el.textContent||'').replace(/0\.4\.\d+/,'0.4.9')}}
async function refresh(){if(typeof view==='undefined')return;if(view==='home')await fixHome();else if(view==='assist')await fixAssist();fixDiscover();fixVersion()}
let q=false;new MutationObserver(()=>{if(q)return;q=true;requestAnimationFrame(()=>{q=false;refresh()})}).observe($('#app')||document.documentElement,{childList:true,subtree:true});setTimeout(refresh,80);setTimeout(refresh,350);setTimeout(refresh,1000);window.ct47WebRefresh=refresh;
})();