(() => {
  'use strict';
  const VERSION = '0.2.7';
  let section = 'trending';
  let calendarKind = 'tv';
  let ratingKind = 'movie';
  let calendarDate = new Date();
  let mineOnly = false;
  const cache = new Map();

  const style = document.createElement('style');
  style.id = 'ct-v027-layout';
  style.textContent = `
    .ct27-tabs{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 16px}.ct27-tabs button,.ct27-kind button,.ct27-filter{border:1px solid #1b3147;background:#07101a;color:#c9def4;border-radius:10px;padding:8px 11px;cursor:pointer}.ct27-tabs button.active,.ct27-kind button.active,.ct27-filter.active{background:#0a2a48;border-color:#2f83c9;color:#fff}
    .ct27-search{display:flex;gap:8px;margin-bottom:16px}.ct27-search input{flex:1;border:1px solid #1b3147;background:#07101a;color:#fff;border-radius:11px;padding:10px 12px;min-width:0}
    .ct27-head{display:flex;align-items:end;justify-content:space-between;gap:12px;margin:0 0 12px}.ct27-head h2{margin:0;font-size:18px}.ct27-note{font-size:12px;color:#86a3be}
    .ct27-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px}.ct27-card{border:1px solid #172b3d;background:#081019;border-radius:13px;overflow:hidden;min-width:0}.ct27-poster{aspect-ratio:16/9;background:#0d1823 center/cover no-repeat;position:relative}.ct27-type{position:absolute;left:8px;bottom:8px;background:#05090dcc;border:1px solid #24435e;border-radius:999px;padding:3px 7px;font-size:10px;color:#b9dbfa}.ct27-body{padding:9px}.ct27-body strong{font-size:12px;line-height:1.25;display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ct27-meta{font-size:10px;color:#86a3be;margin-top:4px;line-height:1.35}
    .ct27-toolbar{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap;margin-bottom:12px}.ct27-kind{display:flex;gap:6px;flex-wrap:wrap}.ct27-week-nav{display:flex;align-items:center;gap:6px}.ct27-week-nav button{border:1px solid #1b3147;background:#07101a;color:#e8f4ff;border-radius:9px;width:34px;height:34px;cursor:pointer}.ct27-week{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:6px;margin:0 0 18px}.ct27-day{border:1px solid #172b3d;background:#07101a;color:#dbeeff;border-radius:11px;padding:8px 5px;text-align:center;cursor:pointer;min-width:0}.ct27-day span{display:block}.ct27-day .dow{font-size:10px;color:#7f9bb4}.ct27-day .num{font-size:17px;font-weight:750;margin:2px 0}.ct27-day .mon{font-size:9px;color:#6c879f}.ct27-day.active{background:#0a2a48;border-color:#3897df}.ct27-day.today{box-shadow:inset 0 -2px 0 #4da3ff}.ct27-loading,.ct27-empty{padding:22px;border:1px solid #172b3d;border-radius:13px;background:#07101a;color:#86a3be}
    @media(max-width:1150px){.ct27-grid{grid-template-columns:repeat(4,minmax(0,1fr))}}@media(max-width:850px){.ct27-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.ct27-week{overflow-x:auto;grid-template-columns:repeat(7,74px);padding-bottom:4px}.ct27-search{flex-direction:column}}@media(max-width:430px){.ct27-grid{grid-template-columns:1fr 1fr}.ct27-body strong{font-size:11px}}
  `;
  document.head.appendChild(style);

  function isoDate(d){return new Date(d.getFullYear(),d.getMonth(),d.getDate()).toISOString().slice(0,10);}
  function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x;}
  function sameDay(a,b){return a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate();}
  function esc(v){return escapeHtml(String(v??''));}
  function escAttr(v){return esc(v).replace(/`/g,'&#96;');}

  async function tmdbPath(path,params={}){
    const key=path+'?'+new URLSearchParams(Object.entries(params).filter(([,v])=>v!==undefined&&v!=='').map(([k,v])=>[k,String(v)])).toString();
    const now=Date.now(),hit=cache.get(key);if(hit&&now-hit.t<600000)return hit.v;
    const u=new URL(`${SUPABASE_URL}/functions/v1/tmdb-proxy`);u.searchParams.set('path',path);Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!=='')u.searchParams.set(k,String(v));});
    const r=await fetch(u,{headers:authHeaders()});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||d.status_message||`TMDB ${r.status}`);cache.set(key,{t:now,v:d});return d;
  }

  function normalize(item,forcedType){const mediaType=forcedType||item.media_type||(item.title?'movie':'tv');const title=item.title||item.name||item.original_title||item.original_name||'Sem título';const date=item.release_date||item.first_air_date||'';return{...item,mediaType,title,date,posterUrl:item.backdrop_path?`https://image.tmdb.org/t/p/w780${item.backdrop_path}`:item.poster_path?`https://image.tmdb.org/t/p/w500${item.poster_path}`:null};}
  function card(item,extra=''){const m=normalize(item,item.mediaType);const image=m.posterUrl?` style="background-image:linear-gradient(to top,rgba(3,8,13,.88),rgba(3,8,13,.05)),url('${escAttr(m.posterUrl)}')"`:'';const label=m.mediaType==='movie'?'FILME':'SÉRIE';const score=Number(m.vote_average||0)>0?` • ★ ${Number(m.vote_average).toFixed(1)}`:'';return `<article class="ct27-card"><div class="ct27-poster"${image}><span class="ct27-type">${label}</span></div><div class="ct27-body"><strong title="${escAttr(m.title)}">${esc(m.title)}</strong><div class="ct27-meta">${extra||esc(m.date||'Data não informada')}${score}</div></div></article>`;}

  function discoverHtml(){return shell(`<header class="header"><div><div class="eyebrow">DESCOBRIR</div><h1 class="h1">Descubra o que assistir</h1><p class="subtitle">Tendências, próximos títulos, avaliações e seu calendário pessoal.</p></div></header><div class="ct27-tabs"><button data-ct27-section="trending" class="${section==='trending'?'active':''}">Em Alta</button><button data-ct27-section="anticipated" class="${section==='anticipated'?'active':''}">Mais Aguardados</button><button data-ct27-section="popular" class="${section==='popular'?'active':''}">Populares</button><button data-ct27-section="rated" class="${section==='rated'?'active':''}">Mais bem avaliados</button><button data-ct27-section="calendar" class="${section==='calendar'?'active':''}">Calendário</button></div><div class="ct27-search"><input id="ct27-query" placeholder="Pesquisar filme, série ou anime"><button id="ct27-search-btn" class="btn-primary" type="button">Buscar</button></div><section id="ct27-body"><div class="ct27-loading">Carregando descoberta…</div></section>`);}

  function weekHtml(){const today=new Date(),start=addDays(calendarDate,-3);let html='';for(let i=0;i<7;i++){const d=addDays(start,i),dow=d.toLocaleDateString('pt-BR',{weekday:'short'}).replace('.',''),mon=d.toLocaleDateString('pt-BR',{month:'short'}).replace('.','');html+=`<button class="ct27-day ${sameDay(d,calendarDate)?'active':''} ${sameDay(d,today)?'today':''}" data-ct27-date="${isoDate(d)}"><span class="dow">${esc(dow)}</span><span class="num">${d.getDate()}</span><span class="mon">${esc(mon)}</span></button>`;}return html;}

  function interestIds(kind){const ids=new Set();const add=item=>{if(!item)return;const type=item.apiType||(typeof mediaApiType==='function'?mediaApiType(item):item.type==='FILME'?'movie':'tv');if(type!==kind)return;const id=Number(item.tmdbId||item.id);if(Number.isFinite(id)&&id>0)ids.add(id);};if(typeof mediaRegistry!=='undefined'&&typeof watchlist!=='undefined'){for(const item of mediaRegistry.values())if(watchlist.has(item.id))add(item);}if(kind==='tv'&&typeof inProgressMedia!=='undefined')for(const item of inProgressMedia)add(item);return ids;}

  function calendarShell(){return `<div class="ct27-toolbar"><div class="ct27-kind"><button data-ct27-kind="tv" class="${calendarKind==='tv'?'active':''}">▣ Séries</button><button data-ct27-kind="movie" class="${calendarKind==='movie'?'active':''}">◉ Filmes</button><button id="ct27-mine" class="ct27-filter ${mineOnly?'active':''}" type="button">${mineOnly?'✓ ':''}Somente meus</button></div><div class="ct27-week-nav"><button id="ct27-prev" aria-label="Semana anterior">‹</button><button id="ct27-today" style="width:auto;padding:0 10px">Hoje</button><button id="ct27-next" aria-label="Próxima semana">›</button></div></div><div class="ct27-week">${weekHtml()}</div><div class="ct27-head"><div><h2>${calendarKind==='tv'?'Episódios e séries em lançamento':'Filmes em lançamento'}</h2><div class="ct27-note">${new Date(calendarDate).toLocaleDateString('pt-BR',{day:'2-digit',month:'long',year:'numeric'})}${mineOnly?' • filtrado pela sua biblioteca':''}</div></div></div><div id="ct27-calendar-results" class="ct27-grid"><div class="ct27-loading" style="grid-column:1/-1">Consultando calendário…</div></div>`;}

  async function loadCalendar(){const body=document.querySelector('#ct27-body');if(!body)return;body.innerHTML=calendarShell();bindCalendar();const target=document.querySelector('#ct27-calendar-results'),day=isoDate(calendarDate);try{let items=[];if(calendarKind==='movie'){const d=await tmdbPath('/discover/movie',{region:'BR','primary_release_date.gte':day,'primary_release_date.lte':day,sort_by:'popularity.desc',include_adult:false,page:1});items=(d.results||[]).slice(0,40).map(x=>normalize(x,'movie'));}else{const d=await tmdbPath('/discover/tv',{'air_date.gte':day,'air_date.lte':day,sort_by:'popularity.desc',include_adult:false,page:1});items=(d.results||[]).slice(0,30).map(x=>normalize(x,'tv'));const detailed=await Promise.allSettled(items.slice(0,18).map(async x=>{const detail=await tmdbPath(`/tv/${x.id}`);return{...x,nextEpisode:detail.next_episode_to_air};}));detailed.forEach((r,i)=>{if(r.status==='fulfilled')items[i]=r.value;});}
      if(mineOnly){const ids=interestIds(calendarKind);items=items.filter(x=>ids.has(Number(x.id)));}
      if(!items.length){target.innerHTML=`<div class="ct27-empty" style="grid-column:1/-1">${mineOnly?'Nenhum item da sua Watchlist/acompanhamento nesta data.':'Nenhum lançamento encontrado para esta data.'}</div>`;return;}
      target.innerHTML=items.map(x=>{let extra;if(calendarKind==='tv'){const ep=x.nextEpisode;extra=ep&&ep.air_date===day?`T${ep.season_number} • E${ep.episode_number} • ${esc(ep.name||'Novo episódio')}`:`Exibição • ${new Date(day+'T12:00:00').toLocaleDateString('pt-BR')}`;}else extra=`Estreia • ${new Date(day+'T12:00:00').toLocaleDateString('pt-BR')}`;return card(x,extra);}).join('');
    }catch(e){target.innerHTML=`<div class="ct27-empty" style="grid-column:1/-1">Não foi possível carregar o calendário agora. ${esc(e instanceof Error?e.message:'')}</div>`;}}

  function bindCalendar(){document.querySelectorAll('[data-ct27-kind]').forEach(b=>b.addEventListener('click',()=>{calendarKind=b.dataset.ct27Kind||'tv';void loadCalendar();}));document.querySelectorAll('[data-ct27-date]').forEach(b=>b.addEventListener('click',()=>{calendarDate=new Date(`${b.dataset.ct27Date}T12:00:00`);void loadCalendar();}));document.querySelector('#ct27-prev')?.addEventListener('click',()=>{calendarDate=addDays(calendarDate,-7);void loadCalendar();});document.querySelector('#ct27-next')?.addEventListener('click',()=>{calendarDate=addDays(calendarDate,7);void loadCalendar();});document.querySelector('#ct27-today')?.addEventListener('click',()=>{calendarDate=new Date();void loadCalendar();});document.querySelector('#ct27-mine')?.addEventListener('click',()=>{mineOnly=!mineOnly;void loadCalendar();});}

  async function loadRated(){const body=document.querySelector('#ct27-body');if(!body)return;body.innerHTML=`<div class="ct27-toolbar"><div class="ct27-kind"><button data-ct27-rating="movie" class="${ratingKind==='movie'?'active':''}">◉ Filmes</button><button data-ct27-rating="tv" class="${ratingKind==='tv'?'active':''}">▣ Séries</button></div></div><div class="ct27-head"><div><h2>Mais bem avaliados</h2><div class="ct27-note">${ratingKind==='tv'?'Séries inclui animações e animes catalogados como TV na TMDB.':'Ranking de filmes pela TMDB.'}</div></div></div><div id="ct27-rated-results" class="ct27-grid"><div class="ct27-loading" style="grid-column:1/-1">Carregando avaliações…</div></div>`;document.querySelectorAll('[data-ct27-rating]').forEach(b=>b.addEventListener('click',()=>{ratingKind=b.dataset.ct27Rating||'movie';void loadRated();}));const target=document.querySelector('#ct27-rated-results');try{const d=await tmdbPath(ratingKind==='movie'?'/movie/top_rated':'/tv/top_rated',{page:1,region:'BR'});const items=(d.results||[]).filter(x=>Number(x.vote_count||0)>=50).slice(0,20).map(x=>normalize(x,ratingKind));target.innerHTML=items.length?items.map(x=>card(x)).join(''):'<div class="ct27-empty" style="grid-column:1/-1">Nenhum título disponível.</div>';}catch(e){target.innerHTML=`<div class="ct27-empty" style="grid-column:1/-1">Falha ao carregar avaliações. ${esc(e instanceof Error?e.message:'')}</div>`;}}

  async function loadGrid(which){const body=document.querySelector('#ct27-body');if(!body)return;body.innerHTML='<div class="ct27-loading">Carregando títulos…</div>';try{let items=[],title='';if(which==='trending'){title='Em Alta';const d=await tmdbPath('/trending/all/week');items=(d.results||[]).filter(x=>x.media_type==='movie'||x.media_type==='tv').slice(0,20).map(x=>normalize(x));}else if(which==='popular'){title='Populares';const[m,t]=await Promise.all([tmdbPath('/movie/popular',{region:'BR'}),tmdbPath('/tv/popular')]);items=[...(m.results||[]).slice(0,10).map(x=>normalize(x,'movie')),...(t.results||[]).slice(0,10).map(x=>normalize(x,'tv'))].sort((a,b)=>(b.popularity||0)-(a.popularity||0));}else{title='Mais Aguardados';const from=isoDate(new Date()),to=isoDate(addDays(new Date(),90));const[m,t]=await Promise.all([tmdbPath('/discover/movie',{region:'BR','primary_release_date.gte':from,'primary_release_date.lte':to,sort_by:'popularity.desc',include_adult:false}),tmdbPath('/discover/tv',{'first_air_date.gte':from,'first_air_date.lte':to,sort_by:'popularity.desc',include_adult:false})]);items=[...(m.results||[]).slice(0,10).map(x=>normalize(x,'movie')),...(t.results||[]).slice(0,10).map(x=>normalize(x,'tv'))].sort((a,b)=>(b.popularity||0)-(a.popularity||0));}body.innerHTML=`<div class="ct27-head"><div><h2>${title}</h2><div class="ct27-note">Atualizado pela TMDB</div></div></div><div class="ct27-grid">${items.length?items.map(x=>card(x)).join(''):'<div class="ct27-empty" style="grid-column:1/-1">Nenhum título disponível.</div>'}</div>`;}catch(e){body.innerHTML=`<div class="ct27-empty">Falha ao carregar. ${esc(e instanceof Error?e.message:'')}</div>`;}}

  async function search(){const input=document.querySelector('#ct27-query'),body=document.querySelector('#ct27-body'),q=(input?.value||'').trim();if(!q||!body)return;body.innerHTML='<div class="ct27-loading">Pesquisando…</div>';try{const d=await tmdbPath('/search/multi',{query:q,include_adult:false,page:1});const items=(d.results||[]).filter(x=>x.media_type==='movie'||x.media_type==='tv').slice(0,20).map(x=>normalize(x));body.innerHTML=`<div class="ct27-head"><div><h2>Resultados para “${esc(q)}”</h2></div></div><div class="ct27-grid">${items.length?items.map(x=>card(x)).join(''):'<div class="ct27-empty" style="grid-column:1/-1">Nenhum resultado encontrado.</div>'}</div>`;}catch(e){body.innerHTML=`<div class="ct27-empty">Falha na pesquisa. ${esc(e instanceof Error?e.message:'')}</div>`;}}

  function bindDiscover(){document.querySelectorAll('[data-ct27-section]').forEach(b=>b.addEventListener('click',()=>{section=b.dataset.ct27Section||'trending';document.querySelectorAll('[data-ct27-section]').forEach(x=>x.classList.toggle('active',x===b));void load();}));document.querySelector('#ct27-search-btn')?.addEventListener('click',()=>void search());document.querySelector('#ct27-query')?.addEventListener('keydown',e=>{if(e.key==='Enter')void search();});}
  function load(){if(section==='calendar')return loadCalendar();if(section==='rated')return loadRated();return loadGrid(section);}

  if(typeof discover==='function')discover=function ctDiscover027(){return discoverHtml();};

  const previousRender=render;
  render=function ctRender027(){previousRender();document.querySelectorAll('.cloud-bar .small.muted').forEach(el=>{if(el.textContent?.includes('CineTracker Oficial'))el.textContent=`CineTracker Oficial v${VERSION}`;});if(typeof view!=='undefined'&&view==='discover'){bindDiscover();void load();}};
})();