iações…</p></div></div></section>`}}catch(_){}try{const d=await tmdbPromise;if(seq!==navSeq||!h?.isConnected)return;const p=d.poster_path?img(d.poster_path,'w500'):'',back=d.backdrop_path?img(d.backdrop_path,'w1280'):'',title=d.title||d.name||cached?.title||'Sem título',date=d.release_date||d.first_air_date||'',genres=(d.genres||[]).map(g=>g.name).join(' · '),cast=(d.credits?.cast||[]).slice(0,18);h.innerHTML=`${back?`<div class="backdrop" style="background-image:linear-gradient(180deg,#0000,#02080dcc),url('${back}')"></div>`:''}<section class="panel"><div class="detail-hero"><div class="detail-poster"${p?` style="background-image:url('${p}')"`:''}></div><div class="detail-copy"><div class="eyebrow">${tmdbKind==='movie'?'Filme':'Série'}</div><h1>${esc(title)}</h1><div class="meta">${esc(String(date).slice(0,4)||'—')} · ${esc(genres)}${d.vote_average?` · ★ ${Number(d.vote_average).toFixed(1)}`:''}</div><p>${esc(d.overview||'Sem sinopse disponível.')}</p><div class="actions"><button class="btn" data-detail-watchlist="${tmdbKind}:${id}">+ Watchlist</button><button class="btn" data-detail-seen="${tmdbKind}:${id}">✓ Marcar como visto</button></div></div></div></section><section class="panel"><div class="panel-head"><h2>Elenco</h2><small>${cast.length}</small></div><div class="ct251-xrail ct251-cardrail">${cast.map(a=>`<article class="card"><button data-person="${Number(a.id)}"><div class="poster"${a.profile_path?` style="background-image:url('${img(a.profile_path,'w185')}')"`:''}></div><div class="card-body"><b>${esc(a.name)}</b><small>${esc(a.character||'')}</small></div></button></article>`).join('')||'<div class="empty">Sem elenco disponível.</div>'}</div></section>${tmdbKind==='tv'?`<section class="panel"><div class="panel-head"><h2>Temporadas</h2><small>${d.number_of_seasons||0}</small></div><div class="ct251-xrail ct251-cardrail" data-seasons>${(d.seasons||[]).filter(s=>s.season_number>0).map(s=>`<article class="card"><button data-season="${id}:${s.season_number}"><div class="poster"${s.poster_path?` style="background-image:url('${img(s.poster_path,'w342')}')"`:''}></div><div class="card-body"><b>${esc(s.name)}</b><small>${s.episode_count||0} episódios</small></div></button></article>`).join('')}</div></section>`:''}` }catch(e){if(seq!==navSeq)return;if(h)h.innerHTML=fail(`Falha ao abrir detalhes: ${e?.message||e}`,kind==='movie'?'home':'discover')}}

/* Install source ownership immediately before boot(). */
renderHome=renderHome251;paintHome=paintHome251;
renderDiscover=renderDiscover251;
sportsPayload=sportsPayload251;sportsFiltered=sportsFiltered251;renderSports=renderSports251;paintSports=paintSports251;
renderProfile=renderProfile251;
renderDetail=renderDetail251;
window.__ctR251SourceBindings={home:renderHome===renderHome251,discover:renderDiscover===renderDiscover251,sports:renderSports===renderSports251,profile:renderProfile===renderProfile251,detail:renderDetail===renderDetail251};

/* r251-owned interactions only. */
document.addEventListener('click',e=>{
 const refresh=e.target?.closest?.('[data-ct251-refresh]');if(refresh){e.preventDefault();e.stopPropagation();ct251DiscoverNonce++;discoverCache.clear();void ct251LoadDiscoverContent();return}
 const dtab=e.target?.closest?.('[data-discover-tab]');if(dtab&&$('[data-discover]')){e.preventDefault();e.stopPropagation();discoverState.tab=String(dtab.dataset.discoverTab||'foryou');discoverCache.clear();void ct251LoadDiscoverContent();return}
 const dtype=e.target?.closest?.('[data-discover-type]');if(dtype&&$('[data-discover]')){e.preventDefault();e.stopPropagation();discoverState.type=String(dtype.dataset.discoverType||'all');void ct251LoadDiscoverContent();return}
 const stab=e.target?.closest?.('[data-sports-tab]');if(stab&&$('[data-sports]')){e.preventDefault();e.stopPropagation();sportsState.tab=String(stab.dataset.sportsTab||'next');paintSports251(sportsCache||{});return}
 const watch=e.target?.closest?.('[data-ct251-watch]');if(watch){const id=Number(watch.dataset.ct251Watch||0),card=watch.closest('[data-ct251-event]');if(!id||ct251SportBusy.has(id))return;e.preventDefault();e.stopPropagation();ct251SportBusy.add(id);watch.classList.remove('ct251-watch-pop');void watch.offsetWidth;watch.classList.add('ct251-watch-pop');const target=card?.dataset.watched!=='1';void rpc('cinetracker_sport_mark_watched_v1',{p_event_id:id,p_watched:target,p_duration_minutes:null,p_watched_at:new Date().toISOString()}).then(()=>sportsPayload251(true)).then(p=>paintSports251(p)).catch(err=>toast(`Esportes: ${err?.message||err}`)).finally(()=>{ct251SportBusy.delete(id);setTimeout(()=>watch.classList.remove('ct251-watch-pop'),450)});return}
 const fc=e.target?.closest?.('[data-ct251-f1-collapse]');if(fc){e.preventDefault();e.stopPropagation();const collapsed=!ct251F1Collapsed();ct251SetF1Collapsed(collapsed);const body=$('.ct251-f1body');if(body)body.hidden=collapsed;fc.textContent=collapsed?'Expandir':'Minimizar';fc.setAttribute('aria-expanded',String(!collapsed));return}
 const ft=e.target?.closest?.('[data-ct251-f1-tab]');if(ft){e.preventDefault();e.stopPropagation();ct251F1Tab=String(ft.dataset.ct251F1Tab||'overview');for(const b of $$('[data-ct251-f1-tab]'))b.classList.toggle('active',b===ft);void ct251PaintF1();return}
 const st=e.target?.closest?.('[data-ct251-stats-toggle]');if(st){e.preventDefault();e.stopPropagation();const grid=$('.ct251-profile-grid'),collapsed=!(grid?.hidden);if(grid)grid.hidden=collapsed;try{localStorage.setItem('ct:profile:stats:collapsed:r251',collapsed?'1':'0')}catch(_){}st.textContent=collapsed?'Expandir':'Minimizar';st.setAttribute('aria-expanded',String(!collapsed));return}
 const mark=e.target?.closest?.('[data-ct251-mark-episode]');if(mark){e.preventDefault();e.stopPropagation();const mediaId=Number(mark.dataset.ct251MarkEpisode),season=Number(mark.dataset.season),episode=Number(mark.dataset.episode);mark.classList.add('ct251-watch-pop');void rpc('cinetracker_mark_watch_v0994',{p_media_id:mediaId,p_item_type:'episode',p_season_number:season,p_episode_number:episode,p_title:mark.dataset.title||null,p_runtime_minutes:null,p_released_episodes:Number(mark.dataset.released)||null,p_watched_at:new Date().toISOString()}).then(()=>{homeCache=null;return renderHome(navSeq)}).catch(err=>toast(`Home: ${err?.message||err}`));return}
},true);

window.addEventListener('resize',()=>{document.documentElement.dataset.ct251Viewport=String(document.documentElement.clientWidth)});
})();
