"panel"><div class="panel-head"><h2>Da sua Watchlist</h2><small>Filme · Série · Anime</small></div><div class="ct251-xrail ct251-cardrail">${data.watch.map(ct251DiscoverCard).join('')||'<div class="empty">Nenhum item elegível na Watchlist.</div>'}</div></section><section class="panel"><div class="panel-head"><h2>100% Novos</h2><small>Filme · Série · Anime</small></div><div class="ct251-xrail ct251-cardrail">${data.fresh.map(ct251DiscoverCard).join('')||'<div class="empty">Nenhum título novo elegível agora.</div>'}</div></section></div>`;ct251MarkShown(data.all)}
async function ct251OtherDiscoverRows(tab){const base=await discoverRows(tab);return (Array.isArray(base)?base:[]).filter(x=>!CT251_WWE.test(ct251Text(x)))}
function ct251PaintOther(rows){const h=$('[data-discover-content]');if(!h)return;let a=rows||[];if(discoverState.type!=='all')a=a.filter(x=>mediaType(x)===discoverState.type);if(discoverState.tab==='calendar'){const groups=new Map();for(const x of a){const ds=String(x.calendar_date||x.release_date||x.first_air_date||'').slice(0,10)||'Sem data';if(!groups.has(ds))groups.set(ds,[]);groups.get(ds).push(x)}h.innerHTML=`<div class="page">${[...groups.entries()].map(([d,g])=>`<section class="panel"><div class="panel-head"><h2>${d==='Sem data'?d:new Date(`${d}T12:00:00`).toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'})}</h2><small>${g.length}</small></div><div class="ct251-xrail ct251-cardrail">${g.map(ct251DiscoverCard).join('')}</div></section>`).join('')||'<div class="empty">Nenhum lançamento da sua Watchlist neste período.</div>'}</div>`;return}h.innerHTML=`<div class="ct251-xrail ct251-cardrail">${a.slice(0,120).map(ct251DiscoverCard).join('')||'<div class="empty">Nenhum título elegível.</div>'}</div>`}
async function ct251LoadDiscoverContent(){const root=$('[data-discover]');if(!root)return;const seq=++ct251DiscoverGeneration,tab=String(discoverState.tab||'foryou'),type=String(discoverState.type||'all');root.setAttribute('aria-busy','true');for(const b of $$('[data-discover-tab]',root))b.classList.toggle('active',b.dataset.discoverTab===tab);for(const b of $$('[data-discover-type]',root))b.classList.toggle('active',b.dataset.discoverType===type);try{const data=tab==='foryou'?await ct251ForYou():await ct251OtherDiscoverRows(tab);if(seq!==ct251DiscoverGeneration||String(discoverState.tab)!==tab||String(discoverState.type)!==type){window.__ctR251DiscoverDropped=(window.__ctR251DiscoverDropped||0)+1;return}if(tab==='foryou')ct251PaintForYou(data);else ct251PaintOther(data)}catch(e){if(seq===ct251DiscoverGeneration){const h=$('[data-discover-content]');if(h)h.innerHTML=fail(`Falha ao carregar Descobrir: ${e?.message||e}`,'discover')}}finally{if(seq===ct251DiscoverGeneration)root.removeAttribute('aria-busy')}}
async function renderDiscover251(seq){setApp(shell('Descobrir','Recomendações, tendências, novidades e calendário.','discover',`<div class="page" data-discover><div class="tabs ct251-xrail">${[['foryou','Pra você'],['trending','Em alta'],['popular','Populares'],['new','Novidades'],['anticipated','Mais Aguardados'],['top','Mais bem avaliados'],['calendar','Calendário']].map(([k,l])=>`<button class="chip ${discoverState.tab===k?'active':''}" data-discover-tab="${k}">${l}</button>`).join('')}</div><div class="filters">${[['all','Todos'],['movie','Filmes'],['tv','Séries']].map(([k,l])=>`<button class="chip ${discoverState.type===k?'active':''}" data-discover-type="${k}">${l}</button>`).join('')}</div><div data-discover-content>${loading('Carregando títulos...')}</div></div>`));if(seq!==navSeq||route()!=='discover')return;await ct251LoadDiscoverContent()}

/* ---------- SPORTS + F1: source renderer ---------- */
function ct251SportDate(e){return ct251SafeDate(e?.starts_at||e?.start_time||e?.start_at||e?.datetime||e?.event_date||e?.date||e?.utc_date)}
function ct251SportWatched(e){return !!(e?.is_watched||e?.watched||e?.seen||e?.viewed||e?.sport_watched_at||e?.watched_at||ct251Num(e?.watch_count||e?.play_count)>0)}
function ct251SportFavorite(e){return !!(e?.has_favorite||e?.favorite||e?.is_favorite||e?.team_favorite||e?.home_favorite||e?.away_favorite)}
function ct251UniqueEvents(rows){const out=[],seen=new Set();for(const e of rows||[]){const key=String(e?.id??e?.event_id??`${e?.provider||''}|${e?.provider_event_id||''}|${e?.starts_at||''}|${e?.title||''}`);if(seen.has(key))continue;seen.add(key);out.push(e)}return out}
async function sportsPayload251(force=false){if(!force&&sportsCache?.__ct251)return sportsCache;const now=new Date(),from=new Date(now.getTime()-3*CT251_DAY),to=new Date(now.getTime()+45*CT251_DAY);const p=await rpc('cinetracker_sports_payload_v1',{p_from:from.toISOString(),p_to:to.toISOString()});sportsCache={...(p||{}),events:ct251UniqueEvents([...(p?.events||[]),...(p?.watch_history||[])]),__ct251:true};return sportsCache}
function sportsFiltered251(p){let a=Array.isArray(p?.events)?p.events:[],mode=String(sportsState.tab||'next'),now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime(),tomorrow=today+CT251_DAY;if(mode==='previous')a=a.filter(e=>{const d=ct251SportDate(e);return d&&d.getTime()<now.getTime()&&d.getTime()>=now.getTime()-72*3600000}).sort((a,b)=>ct251SportDate(b)-ct251SportDate(a));else if(mode==='favorites')a=a.filter(ct251SportFavorite).sort((a,b)=>ct251SportDate(a)-ct251SportDate(b));else if(mode==='watched')a=a.filter(ct251SportWatched).sort((a,b)=>ct251SportDate(b)-ct251SportDate(a));else a=a.filter(e=>{const d=ct251SportDate(e);return d&&d.getTime()>=now.getTime()&&d.getTime()<tomorrow&&d.getTime()>=today}).sort((a,b)=>ct251SportDate(a)-ct251SportDate(b));return a}
function ct251SportEvent(e){const d=ct251SportDate(e),id=ct251Num(e?.id??e?.event_id),watched=ct251SportWatched(e),match=e.home_name||e.away_name,score=e.home_score!=null||e.away_score!=null?`${esc(e.home_score??'–')} : ${esc(e.away_score??'–')}`:'×';return `<article class="event ct251-sport-event" data-ct251-event="${id}" data-watched="${watched?'1':'0'}"><div class="event-top"><div class="league"><span>🏆 ${esc(e.competition_name||e.sport_name||e.sport_slug||'Esporte')}</span></div><span class="status">${d?d.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}):'—'}</span></div>${match?`<div class="match"><div class="side"><b>${esc(e.home_name||'')}</b></div><div class="score">${score}</div><div class="side"><b>${esc(e.away_name||'')}</b></div></div>`:`<div class="event-title">${esc(e.title||e.name||'Evento')}</div>`}<div class="meta">${d?d.toLocaleString('pt-BR',{weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):''}</div><div class="actions"><button class="btn ct251-watch-btn" type="button" data-ct251-watch="${id}">${watched?'✓ Assistido — desmarcar':'✓ Marcar como assistido'}</button></div></article>`}
function ct251F1Collapsed(){try{return localStorage.getItem('ct:f1hub:collapsed:r251')==='1'}catch(_){return false}}
function ct251SetF1Collapsed(v){try{localStorage.setItem('ct:f1hub:collapsed:r251',v?'1':'0')}catch(_){} }
async function ct251F1Get(path){const r=await fetch(`https://api.jolpi.ca/ergast/f1/${path.replace(/^\/+/, '')}`,{headers:{accept:'application/json'}});if(!r.ok)throw new Error(`F1 ${r.status}`);return r.json()}
const ct251Races=o=>o?.MRData?.RaceTable?.Races||[];const ct251Standings=o=>o?.MRData?.StandingsTable?.StandingsLists?.[0]||{};
async function ct251LoadF1(){if(ct251F1DataCache.data&&Date.now()-ct251F1DataCache.at<300000)return ct251F1DataCache.data;const season=new Date().getFullYear(),p=await Promise.allSettled([ct251F1Get(`${season}.json`),ct251F1Get(`${season}/driverstandings.json`),ct251F1Get(`${season}/constructorstandings.json`),ct251F1Get(`${season}/last/results.json`)]);const schedule=ct251Races(p[0].status==='fulfilled'?p[0].value:{}),drivers=ct251Standings(p[1].status==='fulfilled'?p[1].value:{}).DriverStandings||[],constructors=ct251Standings(p[2].status==='fulfilled'?p[2].value:{}).ConstructorStandings||[],last=ct251Races(p[3].status==='fulfilled'?p[3].value:{})[0]||null,now=Date.now(),next=schedule.find(r=>new Date(`${r.date||''}T${r.time||'00:00:00Z'}`).getTime()>=now)||null;return (ct251F1DataCache={at:Date.now(),data:{season,schedule,drivers,constructors,last,next}}).data}
function ct251RaceTime(r){const d=ct251SafeDate(`${r?.date||''}T${r?.time||'00:00:00Z'}`);return d?new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'short',timeStyle:'short'}).format(d):'—'}
function ct251F1Content(d,tab){if(!d)return'<div class="empty">Dados da F1 indisponíveis.</div>';if(tab==='calendar')return `<div class="ct251-xrail ct251-f1-table">${d.schedule.map(r=>`<article><b>${esc(r.round)}. ${esc(r.raceName)}</b><span>${esc(r.Circuit?.circuitName||'')}</span><small>${esc(ct251RaceTime(r))}</small></article>`).join('')}</div>`;if(tab==='drivers')return `<div class="ct251-xrail ct251-f1-standings">${d.drivers.slice(0,20).map(x=>`<div><b>${esc(x.po