import {readFile} from 'node:fs/promises';import {resolve} from 'node:path';await import('./build-r496.mjs');
const [js,css,html,releaseRaw,rootPkgRaw,webPkgRaw]=await Promise.all([readFile(resolve('dist/app-v496.js'),'utf8'),readFile(resolve('dist/app-v496.css'),'utf8'),readFile(resolve('dist/index.html'),'utf8'),readFile(resolve('dist/release.json'),'utf8'),readFile(resolve('../../package.json'),'utf8'),readFile(resolve('package.json'),'utf8')]);
const ok=(v,m)=>{if(!v)throw new Error('r496 '+m)},release=JSON.parse(releaseRaw),rootPkg=JSON.parse(rootPkgRaw),webPkg=JSON.parse(webPkgRaw);
ok(rootPkg.version==='0.3.23'&&webPkg.version==='0.3.23','version');ok(release.version==='0.3.23'&&release.revision==='r496-official-0.3.23','release');ok(html.includes('app-v496.js')&&html.includes('app-v496.css'),'assets');
for(const bad of ['auth-page','cloud-bar','MENU DIÁRIO','--gold:#d6b55b'])ok(!html.includes(bad),'legacy html '+bad);
ok(js.includes("window.__ctR496Marker='fluid-home-native-movies+profile-split-no-monolith+foryou-snapshot+modern-blue-only'"),'marker');
ok(js.includes('ct496-movie-card')&&!js.includes("try{return ct274Row(y,{meta:ct274MovieMeta(y),action:ct274MovieWatchAction(y),attrs:ct274MovieAttrs(y)})catch"),'native movies');
ok(js.includes('cinetracker_home_series_v492')&&js.includes('cinetracker_home_series_v452'),'series bounded fallback');
const rp=js.indexOf('async function renderProfile491');const re=js.indexOf('/* CT_R491_CORE_END */',rp);const profile=js.slice(rp,re);
ok(profile.includes('cinetracker_profile_summary_v489')&&profile.includes('cinetracker_profile_quick_stats_v1')&&profile.includes('cinetracker_sports_stadium_summary_v296'),'profile split');ok(!profile.includes('cinetracker_profile_screen_v495'),'monolith removed');
ok(js.includes('ct496:foryou')&&js.includes('cinetracker_foryou_payload_v490'),'foryou snapshot');ok(css.includes('--gold:#58afe0!important')&&css.includes('.ct496-movie-card .poster')&&css.includes('aspect-ratio:2/3!important'),'visual');
const own=js.slice(js.lastIndexOf('/* CineTracker Web 0.3.23 r496'));for(const bad of ['window.location.reload(','router.refresh(','while(true)','setInterval(','new MutationObserver'])ok(!own.includes(bad),'forbidden '+bad);
console.log('WEB_R496_REGRESSION_OK');