import {readFile} from 'node:fs/promises';
import {resolve} from 'node:path';
await import('./build-r271-official.mjs');
const dist=resolve('dist'),js=await readFile(resolve(dist,'app-v271.js'),'utf8'),release=JSON.parse(await readFile(resolve(dist,'release.json'),'utf8'));
const must=x=>{if(!js.includes(x))throw new Error('R271 missing '+x)};
must("window.__ctR271='home-no-persistent-observer+history-idempotent'");
must('function ct271HistorySig(hist)');
must("if(ct270State.historySig===sig&&ct269State?.history){ct270ShowHistoryShell();return false}");
if(js.includes('new MutationObserver(ct270Schedule).observe(document.documentElement,{childList:true,subtree:true});'))throw new Error('R271 persistent observer regression');
if((js.match(/new MutationObserver\(/g)||[]).length>3)throw new Error('R271 unexpected observer growth');
if(release.home_persistent_observer!==false||release.home_history_idempotent!==true)throw new Error('R271 release freeze flags');
console.log('R271_STATIC_OK no persistent Home observer; canonical history idempotent');
