import {readFile} from 'node:fs/promises';
import {resolve} from 'node:path';
const dist=resolve('dist');
const [html,js,css,release,sw]=await Promise.all(['index.html','app-v270.js','app-v270.css','release.json','service-worker.js'].map(f=>readFile(resolve(dist,f),'utf8')));
const ok=(cond,msg)=>{if(!cond)throw new Error('R270 regression: '+msg)};
const has=(s,x,msg=x)=>ok(s.includes(x),msg);
has(js,"window.__ctWebBuild='1.0.61';window.__ctOfficialVersion='1.0.61';",'version identity');
has(js,"const REVISION='r270-official-1.0.61';",'revision identity');
has(js,"window.__ctR270='real-r5-history+dom-order-watch-host'",'r270 marker');
has(js,"window.__ctR270Home='r5-watch-history+direct-child-right-check'",'Home marker');
has(js,"window.__ctR269='video-history-r5+series-watch-inline'",'r269 corrected to r5');
has(js,"const p=await rpc('cinetracker_profile_home_payload_v0997_r5'",'history uses canonical r5');
ok(!js.includes("window.__ctR269='video-history-r3+series-watch-inline'"),'obsolete r3 marker removed');
has(js,'function ct270ShowHistoryShell()','history shell');
has(js,'function ct270AdoptCanonicalHistory(pack=window.homeCache)','canonical history adoption');
has(js,'pack.__ctHistoryAuthoritative!==true','fast cache cannot become history authority');
has(js,'function ct270WatchActions(view)','watch actions independent of stack');
has(js,'function ct270RowForAction(action,view)','DOM-order row association');
has(js,'row.compareDocumentPosition(action)','real DOM order');
has(js,"const props={position:'absolute',right:'10px'",'inline important watch geometry');
has(js,"ct270SetImportant(action,k,v)",'inline important application');
has(js,"new MutationObserver(ct270Schedule).observe(document.documentElement,{childList:true,subtree:true});",'single final reconciler');
has(js,'r270 owns persistent Home reconciliation; r268 observer retired','r268 observer retired');
has(js,'r270 owns persistent Home reconciliation; r269 observer retired','r269 observer retired');
has(css,'[data-home-view="series"] .media-row.ct270-watch-host>.ct270-inline-watch-action{position:absolute!important;right:10px!important','fallback CSS geometry');
for(const x of["window.__ctR267Discover='atomic-tabs+recursive-personal-exclusions'","window.__ctR267Detail='r169-rich-producer-local-x'","window.__ctR267Sports='r266-stable-preserved'"])has(js,x,'frozen '+x);
has(html,'app-v270.js','r270 JS asset');has(html,'app-v270.css','r270 CSS asset');ok(!html.includes('app-v269.js')&&!html.includes('app-v269.css'),'no r269 asset refs');
const meta=JSON.parse(release);ok(meta.version==='1.0.61'&&meta.revision==='r270-official-1.0.61','release identity');ok(meta.home_history_source==='cinetracker_profile_home_payload_v0997_r5'&&meta.home_history_restored&&meta.home_history_first,'history flags');ok(meta.home_series_watch_direct_child&&meta.home_series_watch_inline_right,'watch flags');ok(meta.android==='1.0.20/10062','Android frozen');
has(sw,"const CACHE='ct-web-1.0.61-r270';",'service worker cache');
console.log('R270_STATIC_OK r5-history dom-order-watch inline-important frozen-surfaces');
