import {readFile} from 'node:fs/promises';
import {resolve} from 'node:path';
await import('./build-r272-official.mjs');
const dist=resolve('dist'),js=await readFile(resolve(dist,'app-v272.js'),'utf8'),release=JSON.parse(await readFile(resolve(dist,'release.json'),'utf8'));
const ok=(c,m)=>{if(!c)throw new Error('R272 regression: '+m)};
const has=(x,m=x)=>ok(js.includes(x),m);
has("window.__ctR272='canonical-home-producer+r5-history+direct-watch'",'r272 marker');
has('function ct272HistoryReady(p,histE,histM)','producer history readiness');
has('function ct272HistoryStack(rows,kind,ready)','producer history renderer');
has('data-ct272-history="episodes"','series history produced');
has('data-ct272-history="movies"','movie history produced');
has("homeCache=await rpc('cinetracker_profile_home_payload_v0997_r5'",'watched action refreshes r5');
ok(!js.includes("homeCache=await rpc('cinetracker_home_live_v0997_r3'"),'watched action cannot overwrite Home with r3');
has('function ct266AttachWatch(el,kind,tmdb,s=0,e=0,title=\'\')','r266 direct watch producer preserved');
has("el.insertAdjacentHTML('beforeend',ct266WatchAction(kind,tmdb,s,e,title))",'watched glyph appended inside row');
ok(!js.includes('if(ct269PaintHomeBase)paintHome=function'),'r269 paint wrapper retired');
ok(!js.includes('if(ct269RenderHomeBase)renderHome=async function'),'r269 render wrapper retired');
ok(!js.includes('if(ct270PaintHomeBase)paintHome=function'),'r270 paint wrapper retired');
ok(!js.includes('if(ct270RenderHomeBase)renderHome=async function'),'r270 render wrapper retired');
ok(!js.includes('new MutationObserver(ct270Schedule).observe'),'r270 persistent observer absent');
ok(release.home_history_in_producer===true&&release.home_history_first===true&&release.home_fast_cache_never_empty_history===true&&release.home_mark_watched_refresh==='r5'&&release.home_post_render_repair===false,'release Home flags');
console.log('R272_STATIC_OK history-in-producer r5-only direct-watch post-repair-off');
