import {readFile} from 'node:fs/promises';
import {resolve} from 'node:path';
if(process.env.CT_R316_SKIP_BUILD!=='1')await import('./build-r316.mjs');
const [js,html,rRaw]=await Promise.all([readFile(resolve('dist/app-v316.js'),'utf8'),readFile(resolve('dist/index.html'),'utf8'),readFile(resolve('dist/release.json'),'utf8')]);
const r=JSON.parse(rRaw),ok=(v,m)=>{if(!v)throw new Error('R316_STATIC '+m)};
ok(r.version==='1.0.107'&&r.revision==='r316-official-1.0.107','identity');
ok(html.includes('app-v316.js')&&html.includes('app-v316.css'),'assets');
ok(js.includes("window.__ctR316='profile-r237-order+watchlist-open+f1-incomplete-schedule-truth'"),'runtime marker');
ok(js.indexOf('window.__ctR316EarlyCapture=true')<js.indexOf('window.__ctR315EarlyCapture=true'),'r316 capture must beat r315 blocker');
ok(js.includes('window.__ctR237ProfileOrder'),'r237 requested order authority missing');
ok(js.includes('data-ct316-watchlist'),'Watchlist click marker missing');
ok(js.includes("rpc('cinetracker_watchlist_full_v119'"),'full Watchlist source missing');
ok(js.includes('Agenda ainda não sincronizada'),'F1 incomplete schedule truth missing');
ok(js.includes('[data-ct255-f1tab="drivers"]')&&js.includes('[data-ct255-f1tab="teams"]'),'F1 hidden legacy tabs guard missing');
ok(r.profile_stats_order==='r237-requested-4col-two-wide-totals','release stat order');
ok(r.profile_watchlist_stats==='clickable-open-full-list','release Watchlist behavior');
ok(r.profile_stats_collapse==='main+sports-unified','unified collapse');
ok(r.f1_false_season_ended===false&&r.f1_tabs==='overview+calendar+standings+circuits','F1 contract');
ok(r.android==='1.0.20/10062','Android changed');
console.log('R316_STATIC_OK Profile order/buttons + F1 truth');
