import {readFile,access} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=dirname(fileURLToPath(import.meta.url)),dist=resolve(root,'dist');
const [runtime,js,release]=await Promise.all([readFile(resolve(root,'runtime-r236-current-video-scope.js'),'utf8'),readFile(resolve(dist,'app-v236.js'),'utf8'),readFile(resolve(dist,'release.json'),'utf8')]);
const must=(s,x,label)=>{if(!s.includes(x))throw new Error('r236 missing '+label)};
for(const [x,label] of [["window.__ctR236='current-video-scope-authority'",'authority'],["generic-aired-unwatched-hydration-no-title-hardcode",'generic Home'],["restore-approved-layout-stable-routes",'Discover restore'],["standard-card-assistido-only",'Sports single action'],["overview-calendar-next-drivers-constructors-last",'F1 nav']])must(runtime,x,label);
for(const forbidden of ['Stuart','Lioness','WWE Raw'])if(runtime.includes(forbidden))throw new Error('r236 hardcoded title '+forbidden);
for(const tab of ['Visão geral','Calendário','Próximo GP','Pilotos','Construtores','Último GP'])must(runtime,tab,'F1 tab '+tab);
for(const obsolete of ["['points','Pontuação']","['pit','Pit stops']","['quarters','Quartis']"])if(runtime.includes(obsolete))throw new Error('r236 keeps obsolete F1 tab '+obsolete);
must(runtime,"if(eventAction236(el))el.remove()",'Eventos removal');
must(runtime,"grid-auto-columns:minmax(128px,152px)",'approved base card geometry');
must(runtime,"el.classList.remove('ct127-discover-card')",'r235 Discover size neutralization');
must(runtime,"new MutationObserver(queue236)",'live reconciliation');
must(js,"window.__ctWebBuild='1.0.28';window.__ctOfficialVersion='1.0.28';",'bundle version');
must(js,"const REVISION='r236-official-1.0.28';",'bundle revision');
must(js,"window.__ctR236='current-video-scope-authority'",'bundle runtime');
must(release,'"version": "1.0.28"','release version');must(release,'"revision": "r236-official-1.0.28"','release revision');
await access(resolve(dist,'app-v236.css'));await access(resolve(dist,'service-worker.js'));
console.log('R236_STATIC_OK current-video-scope');