import {readFile} from 'node:fs/promises';
import {resolve} from 'node:path';
await import('./build-r302-official.mjs');
const dist=resolve('dist');
const [js,release,html,css]=await Promise.all(['app-v302.js','release.json','index.html','app-v302.css'].map(f=>readFile(resolve(dist,f),'utf8')));
const must=(s,x)=>{if(!s.includes(x))throw new Error('r302 test missing '+x)};
for(const x of['blocked302','watchKeys302','M302.blocked=blocked302','data-ct288-add',"window.__ctR302Stability='finite-hooks-no-global-dom-observer'","window.__ctR302Sports='filters-restored+365d-coverage+finite-repair'","window.__ctR302F1='no-drivers+clickable-calendar+complete-detail-modal'",'ensureSportsFilters302','applySportFilter302','removeDrivers302','enrichF1Modal302','365*86400000','buildForYou301'])must(js,x);
if(js.includes('obsQueued301')||js.includes("new MutationObserver(()=>{if(obsQueued301")||js.includes(".observe(app301,{subtree:true,childList:true})"))throw new Error('r302 regression: global r301 observer present');
const m=JSON.parse(release);if(m.discover_seen_excluded!==true||m.discover_watchlist_excluded!==true||m.discover_add_watchlist!==true||m.discover_for_you_fixed!==true||m.sports_profile_global_observer!==false||m.sports_filters_restored!==true||m.sports_next_days!==365||m.f1_drivers_tab!==false||m.f1_calendar_interactive!==true||m.f1_calendar_detail_complete!==true||m.android!=='1.0.20/10062')throw new Error('r302 metadata regression');
must(html,'app-v302.js');must(css,'.ct302-sport-filters');must(css,'.ct302-f1-extra');
console.log('R302_STATIC_OK Discover exclusions + canonical add + Pra Você + Sports filters/365d + no Pilotos + clickable complete F1 detail + no global observer');
