plugins { id 'com.android.application' }

android {
    namespace 'com.cinetracker.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.cinetracker.app'
        minSdk 26
        targetSdk 34
        versionCode 28
        versionName '0.0.28'
    }

    buildFeatures { buildConfig true }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.12.1'
}
