import { readFile } from 'node:fs/promises';
const read=p=>readFile(p,'utf8');
const html=await read('apps/web/index.html');
const files=['patch-v029.js','patch-v054.js','patch-v059-v089.js','patch-v060-v090.js','patch-v061-v091.js','patch-v063-v092.js','patch-v067-v095.js','patch-v068-v097.js','patch-v074-hotfix1-version.js','patch-v075-hotfix10-selective.js','patch-v076-hotfix10-actions.js','patch-v077-hotfix10-native-bridge.js','patch-v078-hotfix11-import-sync.js','patch-v079-hotfix11-compat.js','patch-v080-hotfix11-settings-bridge.js','patch-v082-hotfix12-picker-guard.js','patch-v083-hotfix13-bingers-semantics.js','patch-v084-hotfix14-real-device.js','service-worker.js'];
const src={};for(const f of files){src[f]=await read('apps/web/'+f);try{new Function(src[f])}catch(e){console.error(`ERRO - sintaxe ${f}: ${e.message}`);process.exit(1)}}
const android=await read('apps/android/app/src/main/java/com/cinetracker/app/MainActivity.java'),gradle=await read('apps/android/app/build.gradle'),buildWeb=await read('scripts/build-web.mjs'),stability=await read('scripts/apply-hotfix9-stability.mjs'),selectiveBuild=await read('scripts/apply-hotfix10-selective.mjs'),prepareAndroid=await read('scripts/prepare-android-hotfix2-web.mjs'),pkg=await read('package.json'),edge=await read('supabase/functions/ct-import-bingers-user/index.ts'),migration=await read('supabase/migrations/20260826130000_hotfix13_profile_stats_plays.sql'),semanticTest=await read('scripts/test-hotfix13-bingers-semantics.mjs');
const p29=src['patch-v029.js'],p54=src['patch-v054.js'],p59=src['patch-v059-v089.js'],p60=src['patch-v060-v090.js'],p92=src['patch-v063-v092.js'],p95=src['patch-v067-v095.js'],h14=src['patch-v084-hotfix14-real-device.js'],picker=src['patch-v082-hotfix12-picker-guard.js'],sync=src['patch-v078-hotfix11-import-sync.js'],sem=src['patch-v083-hotfix13-bingers-semantics.js'],sw=src['service-worker.js'],version=src['patch-v074-hotfix1-version.js'];
const order=['patch-v084-hotfix14-real-device.js','patch-v075-hotfix10-selective.js','patch-v076-hotfix10-actions.js','patch-v077-hotfix10-native-bridge.js','patch-v078-hotfix11-import-sync.js','patch-v079-hotfix11-compat.js','patch-v080-hotfix11-settings-bridge.js','patch-v082-hotfix12-picker-guard.js','patch-v083-hotfix13-bingers-semantics.js'];const pos=order.map(x=>selectiveBuild.indexOf(`'${x}'`));const ordered=pos.every((x,i)=>x>=0&&(i===0||x>pos[i-1]));
const checks=[
['CineTracker base',html.includes('CineTracker')],
['Núcleo v95 preserva detalhes/home/busca/histórico/backup',p29.includes('openMedia')&&p54.includes('Carrossel')&&p59.includes('/search/multi')&&p60.includes('refreshHome')&&p92.includes('openEpisode92')&&p92.includes('Exportar dados')],
['v95 preserva Pra Você e critérios',p95.includes('yearOf(x)>1990')&&p95.includes('scoreOf(x)>=7.8')],
['Auth/session P0 preservados',buildWeb.includes('ctFetchWithTimeout')&&buildWeb.includes('8000')&&buildWeb.includes('ctLooksLikeJwt')&&buildWeb.includes('cinetracker_p0_session_reset_hotfix7')&&buildWeb.includes('authRecoveryWithTimeout(restoreSession(), 6500')],
['HOTFIX9 ainda remove overlay v97',stability.includes('patch-v068-v097.js')&&pkg.indexOf('apply-hotfix9-stability.mjs')<pkg.indexOf('apply-hotfix10-selective.mjs')],
['HOTFIX14 usa arquivo único e remove capture-nav antigo',ordered&&selectiveBuild.includes("html=html.replace(/<script src=\"\\/patch-v081-hotfix12-nav-pre")&&selectiveBuild.includes('patch-v084-hotfix14-real-device.js')],
['HOTFIX14 verifica tela alvo em todas as abas',['history','profile','settings','discover','home'].every(x=>h14.includes(`t==='${x}'`))&&h14.includes('visible14(t)')&&h14.includes('force14(t)')],
['HOTFIX14 intercepta picker Android e restaura arquivos',h14.includes('pickImportFile')&&h14.includes('getImportFileBase64')&&h14.includes('ct14RestoreNativeFiles')&&h14.includes('window.__ct12ImportState')],
['Picker Web dual CSV preservado',sync.includes('id="ct11-library"')&&sync.includes('id="ct11-watches"')&&picker.includes('window.__ct12ImportState')&&picker.includes("canonical12(state.library,'library.csv')")&&picker.includes("canonical12(state.watches,'watches.csv')")],
['HOTFIX13 semântica Bingers preservada',sem.includes("normalize('NFKD')")&&sem.includes('movie_plays')&&sem.includes('episode_plays')&&sem.includes('watch_later_total')&&sem.includes('unmatched_watch_events')&&sem.includes('ratings.csv')&&sem.includes('lists.csv')],
['Fixture de agregados continua travada',semanticTest.includes('3078')&&semanticTest.includes('1312')&&semanticTest.includes('14904')&&semanticTest.includes('16216')&&semanticTest.includes('533')&&semanticTest.includes('227')],
['Backend preserva manual e plays',edge.includes('withoutConflictingManualOverrides')&&edge.includes('external_ids:{plays:p,first_watched_at:first,last_watched_at:last')&&edge.includes("state:'AddedToWatchlist'")&&edge.includes("state:'WatchLater'")&&edge.includes("state:'InProgress'")],
['RPC stats soma plays',migration.includes("external_ids->>'plays'")&&migration.includes('sum(plays)')],
['Web/cache HOTFIX14',pkg.includes('0.0.97-hotfix14-real-device')&&version.includes('0.0.97 HOTFIX 14')&&version.includes('__ctHotfix14Version')&&sw.includes('ct-web-0.0.97-hotfix14-real-device')],
['Service worker não cacheia shell HTML',!sw.includes('index.html')&&!sw.includes('navigate')],
['Android segue inline e sem fallback remoto',android.includes('loadDataWithBaseURL')&&android.includes('hotfix5/index.html')&&!android.includes('WebViewAssetLoader')&&!android.includes('webView.loadUrl(runtimeUrl')],
['Android não descarta resultado se callback WebView sumir',!android.includes('requestCode != FILE_CHOOSER_REQUEST || fileChooserCallback == null')&&android.includes('cacheImportFile(slot, uris.get(0))')&&android.includes('picker_slot')],
['Android persiste arquivos nativamente',android.includes('ct14-import-')&&android.includes('getImportFileBase64')&&android.includes('pickImportFile')&&android.includes('clearImportFiles')&&android.includes('ct14RestoreNativeFiles')],
['Android navegação prefere HOTFIX14',android.includes('if(window.ct14Navigate){window.ct14Navigate(t);return true;}')],
['Android bundle HOTFIX14 exige v084 e rejeita v081/v97',prepareAndroid.includes('hotfix14-real-device-v95-core-inline-authoritative')&&prepareAndroid.includes('patch-v084-hotfix14-real-device.js')&&prepareAndroid.includes('obsolete HOTFIX12 capture nav')&&prepareAndroid.includes('patch-v068-v097.js')],
['Android identidade HOTFIX14',gradle.includes('versionCode 992')&&gradle.includes("versionName '0.0.97 HOTFIX 14'")]
];
let failed=false;for(const [name,ok] of checks){console.log(`${ok?'OK':'ERRO'} - ${name}`);if(!ok)failed=true}if(failed)process.exit(1);