import { readFile } from 'node:fs/promises';
const html=await readFile('apps/web/index.html','utf8');
const files=['patch-v024.js','patch-v025.js','patch-v027.js','patch-v028.js','patch-v029.js','patch-v030.js','patch-v025-profile-sync.js','patch-v054.js','patch-v055-final.js','patch-v057-cache.js','service-worker.js'];
const src={};for(const f of files){src[f]=await readFile('apps/web/'+f,'utf8');try{new Function(src[f]);}catch(e){console.error('ERRO - sintaxe '+f+': '+e.message);process.exit(1)}}
const android=await readFile('apps/android/app/src/main/java/com/cinetracker/app/MainActivity.java','utf8');
const layout=await readFile('apps/android/app/src/main/res/layout/activity_main.xml','utf8');
const gradle=await readFile('apps/android/app/build.gradle','utf8');
const androidFinal=await readFile('apps/android/app/src/main/assets/ct68-final.js','utf8');
const androidProfile=await readFile('apps/android/app/src/main/assets/ct67-profile-history.js','utf8');
const android84=await readFile('apps/android/app/src/main/assets/ct70-home-084.js','utf8');
for(const [name,code] of [['ct67-profile-history.js',androidProfile],['ct68-final.js',androidFinal],['ct70-home-084.js',android84]]){try{new Function(code)}catch(e){console.error('ERRO - sintaxe '+name+': '+e.message);process.exit(1)}}
const p29=src['patch-v029.js'],p30=src['patch-v030.js'],profile=src['patch-v025-profile-sync.js'],p54=src['patch-v054.js'],p55=src['patch-v055-final.js'],p57=src['patch-v057-cache.js'],sw=src['service-worker.js'];
const checks=[['CineTracker',html.includes('CineTracker')],['Supabase',html.includes('supabase')],['TMDB proxy',html.includes('tmdb-proxy')],['Detalhes globais',p29.includes('openMedia')],['Capas Home/Biblioteca',p30.includes('posters()')&&p30.includes('ct30-library-grid')],['Histórico real',p30.includes('watch_history')&&p30.includes('Histórico')],['Perfil e estatísticas',p30.includes('cinetracker_profile_stats')&&p30.includes('Tempo total assistido')],['Web interface aprovada',p54.includes('Juntando poeira')&&p54.includes('100% novos para você')],['Web gráfico diário',p55.includes('rebuildProfileChart')&&p55.includes('data-ct55-day')],['Web histórico com capas',p55.includes('enrichHistory')&&p55.includes('ct55-cover')],['Web 0.5.7 IndexedDB',p57.includes('indexedDB')&&p57.includes('snapshotData')],['Web 0.5.7 Service Worker',sw.includes('staleWhileRevalidate')&&sw.includes('cacheFirst')],['Android produção',gradle.includes('https://mycinetracker.vercel.app')],['Android 0.0.84',gradle.includes('versionCode 84')&&gradle.includes("versionName '0.0.84'")&&android.includes('APP_VERSION = "0.0.84"')],['Android importação',android.includes('onShowFileChooser')],['Android storage',android.includes('setDomStorageEnabled(true)')],['Android perfil/histórico',android.includes('ct67-profile-history.js')&&androidProfile.includes('ct67-scroll')],['Android preload final',android.includes('ct68-final.js')&&androidFinal.includes('preload')],['Android módulo 0.0.84',android.includes('ct70-home-084.js')&&android84.includes('ct84Navigate')&&android84.includes('openDetail')],['Home e Assistir fundidos',!layout.includes('nav_library')&&android84.includes("target==='home'||target==='library'")],['Filtros Home',android84.includes('Juntando poeira')&&android84.includes('Acompanhando')&&android84.includes('Não iniciados')&&android84.includes('Em dia')&&android84.includes('Carrossel')&&android84.includes('Grade')],['Separação séries/filmes',android84.includes('Séries')&&android84.includes('Filmes')],['Detalhes Descobrir/Histórico',android84.includes("['discover','history']")&&android84.includes('resolveCard')]];
let failed=false;for(const[n,ok]of checks){console.log(`${ok?'OK':'ERRO'} - ${n}`);if(!ok)failed=true}if(failed)process.exit(1);
