import { readFile } from 'node:fs/promises';
const read=p=>readFile(p,'utf8');
const html=await read('apps/web/index.html');
const files=['patch-v029.js','patch-v054.js','patch-v059-v089.js','patch-v060-v090.js','patch-v061-v091.js','patch-v063-v092.js','patch-v067-v095.js','patch-v068-v097.js','patch-v074-hotfix1-version.js','patch-v075-hotfix10-selective.js','patch-v076-hotfix10-actions.js','patch-v077-hotfix10-native-bridge.js','patch-v078-hotfix11-import-sync.js','patch-v079-hotfix11-compat.js','patch-v080-hotfix11-settings-bridge.js','patch-v082-hotfix12-picker-guard.js','patch-v083-hotfix13-bingers-semantics.js','patch-v085-hotfix15-import-transport.js','patch-v087-hotfix16-import-resilience.js','service-worker.js'];
const src={};for(const f of files){src[f]=await read('apps/web/'+f);try{new Function(src[f])}catch(e){console.error(`ERRO - sintaxe ${f}: ${e.message}`);process.exit(1)}}
const android=await read('apps/android/app/src/main/java/com/cinetracker/app/MainActivity.java'),gradle=await read('apps/android/app/build.gradle'),buildWeb=await read('scripts/build-web.mjs'),stability=await read('scripts/apply-hotfix9-stability.mjs'),selectiveBuild=await read('scripts/apply-hotfix10-selective.mjs'),prepareAndroid=await read('scripts/prepare-android-hotfix2-web.mjs'),pkg=await read('package.json'),edge=await read('supabase/functions/ct-import-bingers-user/index.ts'),migration=await read('supabase/migrations/20260826130000_hotfix13_profile_stats_plays.sql'),semanticTest=await read('scripts/test-hotfix13-bingers-semantics.mjs');
const p29=src['patch-v029.js'],p54=src['patch-v054.js'],p59=src['patch-v059-v089.js'],p60=src['patch-v060-v090.js'],p92=src['patch-v063-v092.js'],p95=src['patch-v067-v095.js'],h15=src['patch-v085-hotfix15-import-transport.js'],h16=src['patch-v087-hotfix16-import-resilience.js'],picker=src['patch-v082-hotfix12-picker-guard.js'],sync=src['patch-v078-hotfix11-import-sync.js'],sem=src['patch-v083-hotfix13-bingers-semantics.js'],sw=src['service-worker.js'],version=src['patch-v074-hotfix1-version.js'];
const order=['patch-v085-hotfix15-import-transport.js','patch-v075-hotfix10-selective.js','patch-v076-hotfix10-actions.js','patch-v077-hotfix10-native-bridge.js','patch-v078-hotfix11-import-sync.js','patch-v079-hotfix11-compat.js','patch-v080-hotfix11-settings-bridge.js','patch-v082-hotfix12-picker-guard.js','patch-v083-hotfix13-bingers-semantics.js','patch-v087-hotfix16-import-resilience.js'];const pos=order.map(x=>selectiveBuild.indexOf(`'${x}'`));const ordered=pos.every((x,i)=>x>=0&&(i===0||x>pos[i-1]));
const optionsIndex=edge.indexOf("req.method === 'OPTIONS'"),authIndex=edge.indexOf('user = await uid(req)');
const checks=[
['CineTracker base',html.includes('CineTracker')],
['Núcleo v95 preserva detalhes/home/busca/histórico/backup',p29.includes('openMedia')&&p54.includes('Carrossel')&&p59.includes('/search/multi')&&p60.includes('refreshHome')&&p92.includes('openEpisode92')&&p92.includes('Exportar dados')],
['v95 preserva Pra Você e critérios',p95.includes('yearOf(x)>1990')&&p95.includes('scoreOf(x)>=7.8')],
['Auth/session P0 preservados',buildWeb.includes('ctFetchWithTimeout')&&buildWeb.includes('8000')&&buildWeb.includes('ctLooksLikeJwt')&&buildWeb.includes('cinetracker_p0_session_reset_hotfix7')&&buildWeb.includes('authRecoveryWithTimeout(restoreSession(), 6500')],
['HOTFIX9 ainda remove overlay v97',stability.includes('patch-v068-v097.js')&&pkg.indexOf('apply-hotfix9-stability.mjs')<pkg.indexOf('apply-hotfix10-selective.mjs')],
['HOTFIX16 usa layer resiliente e remove retry legado',ordered&&selectiveBuild.includes('patch-v087-hotfix16-import-resilience.js')&&!selectiveBuild.includes("'patch-v086-hotfix15-import-retry.js'")&&selectiveBuild.includes('patch-v084-hotfix14-real-device')&&selectiveBuild.includes('patch-v081-hotfix12-nav-pre')],
['HOTFIX15 transport ainda verifica tela alvo em todas as abas',['history','profile','settings','discover','home'].every(x=>h15.includes(`t==='${x}'`))&&h15.includes('visible15(t)')&&h15.includes('force15(t)')],
['HOTFIX15 transport mantém botões nativos explícitos no Android',h15.includes('ct15EnhanceNativePicker')&&h15.includes('data-ct15-native-pick')&&h15.includes('pickImportFile')&&h15.includes('ct15RestoreNativeFiles')&&h15.includes('window.__ct12ImportState')],
['HOTFIX15 transport não intercepta clique do input file antigo',!h15.includes("closest?.('#ct11-library,#ct11-watches,#ct11-package')")],
['Picker Web dual CSV preservado',sync.includes('id="ct11-library"')&&sync.includes('id="ct11-watches"')&&picker.includes('window.__ct12ImportState')&&picker.includes("canonical12(state.library,'library.csv')")&&picker.includes("canonical12(state.watches,'watches.csv')")],
['HOTFIX13 semântica Bingers preservada',sem.includes("normalize('NFKD')")&&sem.includes('movie_plays')&&sem.includes('episode_plays')&&sem.includes('watch_later_total')&&sem.includes('unmatched_watch_events')&&sem.includes('ratings.csv')&&sem.includes('lists.csv')],
['Fixture de agregados continua travada',semanticTest.includes('3078')&&semanticTest.includes('1312')&&semanticTest.includes('14904')&&semanticTest.includes('16216')&&semanticTest.includes('533')&&semanticTest.includes('227')],
['Backend CORS responde OPTIONS antes do JWT',optionsIndex>=0&&authIndex>=0&&optionsIndex<authIndex&&edge.includes('Access-Control-Allow-Origin')&&edge.includes('Access-Control-Allow-Headers')&&edge.includes('authorization, x-client-info, apikey, content-type')],
['Backend preserva manual e plays',edge.includes('withoutConflictingManualOverrides')&&edge.includes('first_watched_at: first')&&edge.includes("state: 'AddedToWatchlist'")&&edge.includes("state: 'WatchLater'")&&edge.includes("state: 'InProgress'")],
['Backend HOTFIX16 diferencia auth/transiente/permanente',edge.includes("'AUTH_EXPIRED'")&&edge.includes("'BACKEND_UNAVAILABLE'")&&edge.includes("'DATABASE_REJECTED'")&&edge.includes("'INVALID_DATA'")&&edge.includes('retryable:')],
['Backend HOTFIX16 begin é idempotente',edge.includes('client_run_id')&&edge.includes('resumed: true')&&edge.includes('priorBingersImports')],
['Backend HOTFIX16 cursor e replay são idempotentes',edge.includes("'CURSOR_MISMATCH'")&&edge.includes('replay: true')&&edge.includes('processing_cursor=eq.${expected}')],
['Backend HOTFIX16 não inventa datas e deduplica',edge.includes("'MISSING_WATCH_DATE'")&&edge.includes('Nenhuma data será inventada')&&edge.includes('dedupeBy(history')&&edge.includes('dedupeBy(progress')],
['Backend HOTFIX16 limpeza é escopada ao Bingers',edge.includes('source_import_id=in.(${inIds})')&&edge.includes('source=eq.bingers')&&!edge.includes("imports?profile_id=eq.${user}',{method:'DELETE'")],
['Backend HOTFIX16 finalização verifica total e histórico',edge.includes("'HISTORY_COUNT_MISMATCH'")&&edge.includes("'TOTAL_MISMATCH'")&&edge.includes('countExact(`watch_history?profile_id=eq.${user}&source=eq.bingers`)')],
['Frontend HOTFIX16 renova sessão e refaz headers',h16.includes('ctRefreshSession')&&h16.includes('response.status === 401')&&h16.includes('withFreshAuth16')&&h16.includes('refreshIfNearExpiry16')],
['Frontend HOTFIX16 begin pode ser repetido com run id',h16.includes("body.action === 'begin'")&&h16.includes('client_run_id')&&h16.includes('newRunId16')],
['Frontend HOTFIX16 retry cobre rede/timeout/5xx',h16.includes('AbortController')&&h16.includes('retryableStatus16')&&h16.includes('500, 502, 503, 504')],
['RPC stats soma plays',migration.includes("external_ids->>'plays'")&&migration.includes('sum(plays)')],
['Web/cache HOTFIX16',pkg.includes('0.0.97-hotfix16-import-resilience')&&version.includes('0.0.97 HOTFIX 16')&&version.includes('__ctHotfix16Version')&&sw.includes('ct-web-0.0.97-hotfix16-import-resilience')],
['Service worker não cacheia shell HTML',!sw.includes('index.html')&&!sw.includes('navigate')],
['Android segue inline e sem fallback remoto',android.includes('loadDataWithBaseURL')&&android.includes('hotfix5/index.html')&&!android.includes('WebViewAssetLoader')&&!android.includes('webView.loadUrl(runtimeUrl')],
['Android picker OEM-safe não filtra MIME',android.includes('intent.setType("*/*")')&&!android.includes('Intent.EXTRA_MIME_TYPES')],
['Android restaura Configurações após recriação',android.includes('hasPendingImportFlow()')&&android.includes("window.ct15Navigate&&window.ct15Navigate('settings')")&&android.includes('ct15RestoreNativeFiles')],
['Android não descarta resultado se callback WebView sumir',!android.includes('requestCode != FILE_CHOOSER_REQUEST || fileChooserCallback == null')&&android.includes('cacheImportFile(slot, uris.get(0))')&&android.includes('picker_slot')],
['Android persiste arquivos nativamente',android.includes('ct15-import-')&&android.includes('getImportFileBase64')&&android.includes('pickImportFile')&&android.includes('clearImportFiles')],
['Android navegação prefere HOTFIX15',android.includes('if(window.ct15Navigate){window.ct15Navigate(t);return true;}')],
['Android bundle atual ainda exige HOTFIX15 v085',prepareAndroid.includes('hotfix15-import-transport-v95-core-inline-authoritative')&&prepareAndroid.includes('patch-v085-hotfix15-import-transport.js')&&prepareAndroid.includes('patch-v084-hotfix14-real-device.js')&&prepareAndroid.includes('patch-v081-hotfix12-nav-pre.js')&&prepareAndroid.includes('patch-v068-v097.js')],
['Android identidade atual permanece HOTFIX15',gradle.includes('versionCode 993')&&gradle.includes("versionName '0.0.97 HOTFIX 15'")]
];
let failed=false;for(const [name,ok] of checks){console.log(`${ok?'OK':'ERRO'} - ${name}`);if(!ok)failed=true}if(failed)process.exit(1);