-- CineTracker Web 0.99.4
-- Home payload, canonical play counters, smart batch marking and post-release metrics.

create table if not exists public.watch_play_events_v0994 (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  media_id bigint not null references public.media(id) on delete cascade,
  item_type text not null check (item_type in ('movie','episode')),
  season_number integer,
  episode_number integer,
  played_at timestamptz not null default now(),
  runtime_minutes integer not null default 0 check (runtime_minutes >= 0),
  source text not null default 'manual',
  created_at timestamptz not null default now(),
  check (
    (item_type='movie' and season_number is null and episode_number is null)
    or
    (item_type='episode' and season_number is not null and episode_number is not null)
  )
);

alter table public.watch_play_events_v0994 enable row level security;

create index if not exists watch_play_events_v0994_profile_played_idx
  on public.watch_play_events_v0994(profile_id, played_at desc);
create index if not exists watch_play_events_v0994_media_idx
  on public.watch_play_events_v0994(profile_id, media_id);

-- watch_history already has one canonical imported row per movie/episode. Keep that invariant
-- for manual playback too, while watch_play_events_v0994 remains the immutable event stream.
create unique index if not exists watch_history_v0994_episode_key
  on public.watch_history(profile_id, media_id, season_number, episode_number)
  where item_type='episode' and media_id is not null;
create unique index if not exists watch_history_v0994_movie_key
  on public.watch_history(profile_id, media_id)
  where item_type='movie' and media_id is not null;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='watch_play_events_v0994' and policyname='watch_play_events_v0994_select_own') then
    create policy watch_play_events_v0994_select_own on public.watch_play_events_v0994
      for select to authenticated using (profile_id = auth.uid());
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='watch_play_events_v0994' and policyname='watch_play_events_v0994_insert_own') then
    create policy watch_play_events_v0994_insert_own on public.watch_play_events_v0994
      for insert to authenticated with check (profile_id = auth.uid());
  end if;
end $$;

-- Freeze the imported/canonical baseline before 0.99.4 starts updating watched_at for LRU.
update public.watch_history
set external_ids =
  case when external_ids ? 'baseline_plays_v0994' then external_ids else
    jsonb_set(
      jsonb_set(
        coalesce(external_ids,'{}'::jsonb),
        '{baseline_plays_v0994}',
        to_jsonb(case when coalesce(external_ids->>'plays','') ~ '^[0-9]+$' then greatest(1,(external_ids->>'plays')::int) else 1 end),
        true
      ),
      '{baseline_watched_at_v0994}',
      to_jsonb(watched_at),
      true
    )
  end;

-- Preserve the exact imported totals as the minute baseline. New 0.99.4 play events are added on top.
update public.profiles p
set settings = jsonb_set(
  coalesce(p.settings,'{}'::jsonb),
  '{v0994_metrics_baseline}',
  jsonb_build_object(
    'started_at', now(),
    'series_minutes', case
      when p.settings->'bingers_import'->>'phase'='completed' and coalesce(p.settings->'bingers_import'->>'series_minutes','') ~ '^[0-9]+$'
        then (p.settings->'bingers_import'->>'series_minutes')::bigint
      else 0 end,
    'movie_minutes', case
      when p.settings->'bingers_import'->>'phase'='completed' and coalesce(p.settings->'bingers_import'->>'movie_minutes','') ~ '^[0-9]+$'
        then (p.settings->'bingers_import'->>'movie_minutes')::bigint
      else 0 end,
    'total_minutes', case
      when p.settings->'bingers_import'->>'phase'='completed' and coalesce(p.settings->'bingers_import'->>'total_minutes','') ~ '^[0-9]+$'
        then (p.settings->'bingers_import'->>'total_minutes')::bigint
      else 0 end
  ),
  true
)
where not (coalesce(p.settings,'{}'::jsonb) ? 'v0994_metrics_baseline');

create or replace function public.cinetracker_profile_home_payload_v0994()
returns jsonb
language sql
stable
security invoker
set search_path = public
as $$
with hist as (
  select wh.media_id,
         max(wh.watched_at) as last_watched_at,
         count(distinct (wh.season_number,wh.episode_number)) filter (
           where wh.item_type='episode' and wh.season_number is not null and wh.episode_number is not null
         )::bigint as watched_episodes,
         bool_or(wh.item_type='movie') as movie_seen
  from public.watch_history wh
  where wh.profile_id=auth.uid() and wh.media_id is not null
  group by wh.media_id
), prog as (
  select ep.media_id,
         count(*) filter(where ep.watched)::bigint as watched_episodes,
         max(ep.watched_at) filter(where ep.watched) as last_watched_at
  from public.episode_progress ep
  where ep.profile_id=auth.uid()
  group by ep.media_id
), states as (
  select mo.media_id,
         bool_or(mo.state in ('AddedToWatchlist','WatchLater')) as is_watchlist,
         bool_or(mo.state='InProgress') as is_in_progress,
         bool_or(mo.state='UpToDate') as is_up_to_date,
         bool_or(mo.state='Completed') as is_completed,
         bool_or(mo.state='AlreadySeen') as is_already_seen,
         max(mo.updated_at) as state_updated_at
  from public.media_overrides mo
  where mo.profile_id=auth.uid()
  group by mo.media_id
), base as (
  select m.id as media_id,m.tmdb_id,m.media_type,m.media_kind,m.title,m.poster_path,m.release_year,
         coalesce(m.runtime_minutes,0)::int as runtime_minutes,
         coalesce(m.total_episodes,0)::int as total_episodes,
         greatest(coalesce(h.watched_episodes,0),coalesce(p.watched_episodes,0))::bigint as watched_episodes,
         greatest(h.last_watched_at,p.last_watched_at) as last_watched_at,
         coalesce(s.is_watchlist,false) as is_watchlist,
         coalesce(s.is_in_progress,false) as is_in_progress,
         coalesce(s.is_up_to_date,false) as is_up_to_date,
         coalesce(s.is_completed,false) as is_completed,
         (coalesce(h.movie_seen,false) or coalesce(s.is_already_seen,false)) as is_seen,
         s.state_updated_at,
         coalesce(nullif(m.raw_tmdb->>'vote_average','')::numeric,0) as vote_average,
         coalesce(m.raw_tmdb->>'overview','') as overview
  from public.media m
  left join hist h on h.media_id=m.id
  left join prog p on p.media_id=m.id
  left join states s on s.media_id=m.id
  where h.media_id is not null or p.media_id is not null or s.media_id is not null
), series_rows as (
  select b.*,
    case
      when b.is_completed then 'completed'
      when b.watched_episodes=0 and b.is_watchlist then 'not_started'
      when b.watched_episodes>0 and b.is_up_to_date then 'up_to_date'
      when b.watched_episodes>0 and b.last_watched_at >= now()-interval '30 days' then 'continue'
      when b.watched_episodes>0 then 'dust'
      else null
    end as home_bucket
  from base b where b.media_type='tv'
), movie_watch as (
  select * from base b where b.media_type='movie' and b.is_watchlist and not b.is_seen
), history_ep as (
  select wh.id,wh.media_id,m.tmdb_id,m.title as media_title,m.poster_path,wh.title,wh.watched_at,
         wh.season_number,wh.episode_number,
         case when coalesce(wh.external_ids->>'plays','') ~ '^[0-9]+$' then greatest(1,(wh.external_ids->>'plays')::int) else 1 end as plays
  from public.watch_history wh
  left join public.media m on m.id=wh.media_id
  where wh.profile_id=auth.uid() and wh.item_type='episode'
  order by wh.watched_at desc,wh.id desc
  limit 80
), history_mv as (
  select wh.id,wh.media_id,m.tmdb_id,m.title as media_title,m.poster_path,wh.title,wh.watched_at,
         case when coalesce(wh.external_ids->>'plays','') ~ '^[0-9]+$' then greatest(1,(wh.external_ids->>'plays')::int) else 1 end as plays
  from public.watch_history wh
  left join public.media m on m.id=wh.media_id
  where wh.profile_id=auth.uid() and wh.item_type='movie'
  order by wh.watched_at desc,wh.id desc
  limit 80
)
select jsonb_build_object(
  'series',coalesce((select jsonb_agg(jsonb_build_object(
      'media_id',s.media_id,'tmdb_id',s.tmdb_id,'media_type',s.media_type,'media_kind',s.media_kind,
      'title',s.title,'poster_path',s.poster_path,'release_year',s.release_year,'runtime_minutes',s.runtime_minutes,
      'total_episodes',s.total_episodes,'watched_episodes',s.watched_episodes,'last_watched_at',s.last_watched_at,
      'state_updated_at',s.state_updated_at,'home_bucket',s.home_bucket
    ) order by
      case s.home_bucket when 'continue' then 1 when 'dust' then 2 when 'up_to_date' then 3 when 'not_started' then 4 when 'completed' then 5 else 9 end,
      s.last_watched_at desc nulls last,s.media_id desc)
    from series_rows s where s.home_bucket is not null),'[]'::jsonb),
  'movie_watchlist',coalesce((select jsonb_agg(jsonb_build_object(
      'media_id',m.media_id,'tmdb_id',m.tmdb_id,'title',m.title,'poster_path',m.poster_path,'release_year',m.release_year,
      'runtime_minutes',m.runtime_minutes,'vote_average',m.vote_average,'overview',m.overview,'state_updated_at',m.state_updated_at
    ) order by m.state_updated_at desc nulls last,m.media_id desc) from movie_watch m),'[]'::jsonb),
  'seen_movie_tmdb_ids',coalesce((select jsonb_agg(distinct b.tmdb_id) from base b where b.media_type='movie' and b.is_seen and b.tmdb_id>0),'[]'::jsonb),
  'history_episodes',coalesce((select jsonb_agg(to_jsonb(h)) from history_ep h),'[]'::jsonb),
  'history_movies',coalesce((select jsonb_agg(to_jsonb(h)) from history_mv h),'[]'::jsonb)
);
$$;

create or replace function public.cinetracker_mark_watch_v0994(
  p_media_id bigint,
  p_item_type text,
  p_season_number integer default null,
  p_episode_number integer default null,
  p_title text default null,
  p_runtime_minutes integer default null,
  p_released_episodes integer default null,
  p_watched_at timestamptz default now()
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_profile uuid := auth.uid();
  v_row public.watch_history%rowtype;
  v_plays integer := 0;
  v_runtime integer := 0;
  v_watched bigint := 0;
  v_released integer := null;
  v_media public.media%rowtype;
  v_external jsonb;
begin
  if v_profile is null then raise exception 'AUTH_REQUIRED'; end if;
  if p_item_type not in ('movie','episode') then raise exception 'INVALID_ITEM_TYPE'; end if;
  if p_item_type='episode' and (p_season_number is null or p_episode_number is null) then raise exception 'EPISODE_COORDINATES_REQUIRED'; end if;

  select * into v_media from public.media where id=p_media_id;
  if not found then raise exception 'MEDIA_NOT_FOUND'; end if;

  if p_item_type='movie' then
    select * into v_row from public.watch_history
      where profile_id=v_profile and media_id=p_media_id and item_type='movie'
      order by id limit 1 for update;
  else
    select * into v_row from public.watch_history
      where profile_id=v_profile and media_id=p_media_id and item_type='episode'
        and season_number=p_season_number and episode_number=p_episode_number
      order by id limit 1 for update;
  end if;

  if found then
    v_plays := case when coalesce(v_row.external_ids->>'plays','') ~ '^[0-9]+$' then greatest(1,(v_row.external_ids->>'plays')::int) else 1 end;
    v_external := coalesce(v_row.external_ids,'{}'::jsonb);
    if not (v_external ? 'baseline_plays_v0994') then
      v_external := jsonb_set(v_external,'{baseline_plays_v0994}',to_jsonb(v_plays),true);
      v_external := jsonb_set(v_external,'{baseline_watched_at_v0994}',to_jsonb(v_row.watched_at),true);
    end if;
    v_plays := v_plays + 1;
    v_external := jsonb_set(v_external,'{plays}',to_jsonb(v_plays),true);
    v_external := jsonb_set(v_external,'{v0994_managed}','true'::jsonb,true);
    v_external := jsonb_set(v_external,'{last_play_at_v0994}',to_jsonb(p_watched_at),true);
    update public.watch_history
      set watched_at=p_watched_at,title=coalesce(p_title,title),source='manual',external_ids=v_external
      where id=v_row.id;
  else
    v_plays := 1;
    insert into public.watch_history(profile_id,media_id,item_type,season_number,episode_number,title,watched_at,source,external_ids)
    values(v_profile,p_media_id,p_item_type,
      case when p_item_type='episode' then p_season_number else null end,
      case when p_item_type='episode' then p_episode_number else null end,
      coalesce(p_title,v_media.title),p_watched_at,'manual',
      jsonb_build_object('plays',1,'baseline_plays_v0994',0,'v0994_managed',true,'last_play_at_v0994',p_watched_at)
    );
  end if;

  v_runtime := greatest(0,coalesce(nullif(p_runtime_minutes,0),nullif(v_media.runtime_minutes,0),case when p_item_type='episode' then 45 else 120 end));
  insert into public.watch_play_events_v0994(profile_id,media_id,item_type,season_number,episode_number,played_at,runtime_minutes,source)
  values(v_profile,p_media_id,p_item_type,
    case when p_item_type='episode' then p_season_number else null end,
    case when p_item_type='episode' then p_episode_number else null end,
    p_watched_at,v_runtime,'manual');

  if p_item_type='episode' then
    insert into public.episode_progress(profile_id,media_id,season_number,episode_number,watched,watched_at,origin,updated_at)
    values(v_profile,p_media_id,p_season_number,p_episode_number,true,p_watched_at,'manual',p_watched_at)
    on conflict(profile_id,media_id,season_number,episode_number)
    do update set watched=true,watched_at=excluded.watched_at,origin='manual',updated_at=excluded.updated_at;

    select count(*)::bigint into v_watched from public.episode_progress
      where profile_id=v_profile and media_id=p_media_id and watched=true;
    v_released := nullif(greatest(coalesce(p_released_episodes,0),0),0);

    if v_released is not null and v_watched >= v_released then
      delete from public.media_overrides where profile_id=v_profile and media_id=p_media_id and state='InProgress' and origin in ('system','import');
      insert into public.media_overrides(profile_id,media_id,state,origin,updated_at)
      values(v_profile,p_media_id,'UpToDate','system',p_watched_at)
      on conflict(profile_id,media_id,state) do update set updated_at=excluded.updated_at
        where public.media_overrides.origin in ('system','import');
    else
      delete from public.media_overrides where profile_id=v_profile and media_id=p_media_id and state='UpToDate' and origin in ('system','import');
      insert into public.media_overrides(profile_id,media_id,state,origin,updated_at)
      values(v_profile,p_media_id,'InProgress','system',p_watched_at)
      on conflict(profile_id,media_id,state) do update set updated_at=excluded.updated_at
        where public.media_overrides.origin in ('system','import');
    end if;
  else
    insert into public.media_overrides(profile_id,media_id,state,origin,watched_at,updated_at)
    values(v_profile,p_media_id,'AlreadySeen','manual',p_watched_at,p_watched_at)
    on conflict(profile_id,media_id,state)
    do update set origin='manual',watched_at=excluded.watched_at,updated_at=excluded.updated_at;
    delete from public.media_overrides where profile_id=v_profile and media_id=p_media_id and state in ('AddedToWatchlist','WatchLater');
  end if;

  return jsonb_build_object(
    'media_id',p_media_id,'item_type',p_item_type,'season_number',p_season_number,'episode_number',p_episode_number,
    'plays',v_plays,'watched_episodes',v_watched,'released_episodes',v_released,'watched_at',p_watched_at
  );
end;
$$;

create or replace function public.cinetracker_mark_episodes_batch_v0994(
  p_media_id bigint,
  p_episodes jsonb,
  p_released_episodes integer default null,
  p_default_runtime_minutes integer default null,
  p_watched_at timestamptz default now()
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_profile uuid := auth.uid();
  v_ep jsonb;
  v_count integer := 0;
  v_skipped integer := 0;
  v_exists boolean;
  v_increment boolean;
  v_season integer;
  v_episode integer;
  v_title text;
  v_runtime integer;
begin
  if v_profile is null then raise exception 'AUTH_REQUIRED'; end if;
  if jsonb_typeof(p_episodes) <> 'array' then raise exception 'EPISODES_ARRAY_REQUIRED'; end if;

  for v_ep in select value from jsonb_array_elements(p_episodes)
  loop
    v_season := nullif(v_ep->>'season','')::integer;
    v_episode := nullif(v_ep->>'episode','')::integer;
    v_title := nullif(v_ep->>'title','');
    v_runtime := coalesce(nullif(v_ep->>'runtime_minutes','')::integer,p_default_runtime_minutes);
    v_increment := coalesce((v_ep->>'increment_if_seen')::boolean,false);
    if v_season is null or v_episode is null then continue; end if;

    select exists(select 1 from public.watch_history wh where wh.profile_id=v_profile and wh.media_id=p_media_id
      and wh.item_type='episode' and wh.season_number=v_season and wh.episode_number=v_episode) into v_exists;

    if v_exists and not v_increment then
      v_skipped := v_skipped + 1;
      continue;
    end if;

    perform public.cinetracker_mark_watch_v0994(
      p_media_id,'episode',v_season,v_episode,v_title,v_runtime,p_released_episodes,
      p_watched_at + make_interval(secs => v_count)
    );
    v_count := v_count + 1;
  end loop;

  return jsonb_build_object('marked',v_count,'skipped_existing',v_skipped,'media_id',p_media_id);
end;
$$;

-- Profile totals keep the verified imported minute baseline and add every new 0.99.4 event.
create or replace function public.cinetracker_profile_stats()
returns table(episodes_watched bigint,movies_watched bigint,series_watched bigint,series_minutes bigint,movie_minutes bigint,total_minutes bigint)
language sql
stable
security invoker
set search_path=public
as $$
with cfg as (
  select settings from public.profiles where id=auth.uid()
), wh_ep as (
  select wh.media_id,
    case when coalesce(wh.external_ids->>'plays','') ~ '^[0-9]+$' then greatest(1,(wh.external_ids->>'plays')::int) else 1 end::bigint as plays
  from public.watch_history wh where wh.profile_id=auth.uid() and wh.item_type='episode'
), ep_extra as (
  select ep.media_id from public.episode_progress ep
  where ep.profile_id=auth.uid() and ep.watched=true
    and not exists(select 1 from public.watch_history wh where wh.profile_id=ep.profile_id and wh.media_id=ep.media_id and wh.item_type='episode' and wh.season_number=ep.season_number and wh.episode_number=ep.episode_number)
), wh_mv as (
  select wh.media_id,
    case when coalesce(wh.external_ids->>'plays','') ~ '^[0-9]+$' then greatest(1,(wh.external_ids->>'plays')::int) else 1 end::bigint as plays
  from public.watch_history wh join public.media m on m.id=wh.media_id
  where wh.profile_id=auth.uid() and wh.item_type='movie' and m.media_type='movie'
), mv_extra as (
  select distinct mo.media_id from public.media_overrides mo join public.media m on m.id=mo.media_id
  where mo.profile_id=auth.uid() and m.media_type='movie' and mo.state in ('AlreadySeen','Completed')
    and not exists(select 1 from public.watch_history wh where wh.profile_id=mo.profile_id and wh.media_id=mo.media_id and wh.item_type='movie')
), ev as (
  select
    count(*) filter(where item_type='episode')::bigint as ep_events,
    count(*) filter(where item_type='movie')::bigint as mv_events,
    coalesce(sum(runtime_minutes) filter(where item_type='episode'),0)::bigint as ep_minutes,
    coalesce(sum(runtime_minutes) filter(where item_type='movie'),0)::bigint as mv_minutes
  from public.watch_play_events_v0994 where profile_id=auth.uid()
), totals as (
  select
    (coalesce((select sum(plays) from wh_ep),0)+coalesce((select count(*) from ep_extra),0))::bigint as ep_plays,
    (coalesce((select sum(plays) from wh_mv),0)+coalesce((select count(*) from mv_extra),0))::bigint as mv_plays,
    (select count(*) from (select media_id from wh_ep union select media_id from ep_extra) x)::bigint as series_count
), base as (
  select
    coalesce(nullif(cfg.settings->'v0994_metrics_baseline'->>'series_minutes','')::bigint,
             nullif(cfg.settings->'bingers_import'->>'series_minutes','')::bigint,0)::bigint as series_minutes,
    coalesce(nullif(cfg.settings->'v0994_metrics_baseline'->>'movie_minutes','')::bigint,
             nullif(cfg.settings->'bingers_import'->>'movie_minutes','')::bigint,0)::bigint as movie_minutes
  from cfg
)
select t.ep_plays,t.mv_plays,t.series_count,
       (b.series_minutes+ev.ep_minutes)::bigint,
       (b.movie_minutes+ev.mv_minutes)::bigint,
       (b.series_minutes+b.movie_minutes+ev.ep_minutes+ev.mv_minutes)::bigint
from totals t cross join ev cross join base b;
$$;

create or replace function public.cinetracker_consumption_daily(p_limit_days integer default 19)
returns table(day date,items bigint,plays bigint)
language sql
stable
security invoker
set search_path=public
as $$
with baseline as (
  select
    ((coalesce(wh.external_ids->>'baseline_watched_at_v0994','')::timestamptz) at time zone 'America/Sao_Paulo')::date as day,
    1::bigint as items,
    case when coalesce(wh.external_ids->>'baseline_plays_v0994','') ~ '^[0-9]+$' then greatest(0,(wh.external_ids->>'baseline_plays_v0994')::int)::bigint else 0 end as plays
  from public.watch_history wh
  where wh.profile_id=auth.uid() and wh.external_ids ? 'baseline_watched_at_v0994'
), fresh as (
  select (e.played_at at time zone 'America/Sao_Paulo')::date as day,count(*)::bigint as items,count(*)::bigint as plays
  from public.watch_play_events_v0994 e where e.profile_id=auth.uid() group by 1
), daily as (
  select day,sum(items)::bigint as items,sum(plays)::bigint as plays from (
    select day,items,plays from baseline where plays>0
    union all select day,items,plays from fresh
  ) x where day is not null group by day
), recent as (
  select * from daily order by day desc limit greatest(1,least(coalesce(p_limit_days,19),90))
)
select day,items,plays from recent order by day;
$$;

create or replace function public.cinetracker_watch_last_7_days()
returns table(day date,episodes bigint)
language sql
stable
security invoker
set search_path=public
as $$
with days as (select generate_series(current_date-6,current_date,interval '1 day')::date as day),
base as (
  select ((coalesce(wh.external_ids->>'baseline_watched_at_v0994','')::timestamptz) at time zone 'America/Sao_Paulo')::date as day,
    sum(case when coalesce(wh.external_ids->>'baseline_plays_v0994','') ~ '^[0-9]+$' then greatest(0,(wh.external_ids->>'baseline_plays_v0994')::int) else 0 end)::bigint as episodes
  from public.watch_history wh
  where wh.profile_id=auth.uid() and wh.item_type='episode' and wh.external_ids ? 'baseline_watched_at_v0994'
  group by 1
), fresh as (
  select (played_at at time zone 'America/Sao_Paulo')::date as day,count(*)::bigint as episodes
  from public.watch_play_events_v0994 where profile_id=auth.uid() and item_type='episode' group by 1
), agg as (
  select day,sum(episodes)::bigint episodes from (select * from base union all select * from fresh) x group by day
)
select d.day,coalesce(a.episodes,0) from days d left join agg a using(day) order by d.day;
$$;

create or replace function public.cinetracker_watch_daily_timeline(p_days_back integer default 15,p_days_forward integer default 3)
returns jsonb
language sql
stable
security invoker
set search_path=public
as $$
with bounds as (select (current_date-greatest(0,p_days_back))::date d0,(current_date+greatest(0,p_days_forward))::date d1),
days as (select generate_series((select d0 from bounds),(select d1 from bounds),interval '1 day')::date d),
base as (
  select ((coalesce(wh.external_ids->>'baseline_watched_at_v0994','')::timestamptz) at time zone 'America/Sao_Paulo')::date d,
    sum(case when wh.item_type='episode' and coalesce(wh.external_ids->>'baseline_plays_v0994','') ~ '^[0-9]+$' then greatest(0,(wh.external_ids->>'baseline_plays_v0994')::int) else 0 end)::int episodes,
    sum(case when coalesce(wh.external_ids->>'baseline_plays_v0994','') ~ '^[0-9]+$' then greatest(0,(wh.external_ids->>'baseline_plays_v0994')::int) else 0 end)::int total
  from public.watch_history wh where wh.profile_id=auth.uid() and wh.external_ids ? 'baseline_watched_at_v0994' group by 1
), fresh as (
  select (played_at at time zone 'America/Sao_Paulo')::date d,count(*) filter(where item_type='episode')::int episodes,count(*)::int total
  from public.watch_play_events_v0994 where profile_id=auth.uid() group by 1
), agg as (
  select d,sum(episodes)::int episodes,sum(total)::int total from (select * from base union all select * from fresh) x group by d
)
select jsonb_build_object('today',current_date,'days',jsonb_agg(jsonb_build_object('date',days.d,'episodes',coalesce(agg.episodes,0),'total',coalesce(agg.total,0)) order by days.d))
from days left join agg using(d);
$$;

grant execute on function public.cinetracker_profile_home_payload_v0994() to authenticated;
grant execute on function public.cinetracker_mark_watch_v0994(bigint,text,integer,integer,text,integer,integer,timestamptz) to authenticated;
grant execute on function public.cinetracker_mark_episodes_batch_v0994(bigint,jsonb,integer,integer,timestamptz) to authenticated;
grant select,insert on public.watch_play_events_v0994 to authenticated;
