create table if not exists public.recommendation_memory_v113 (
  id bigint generated by default as identity primary key,
  profile_id uuid not null,
  tmdb_id bigint not null check (tmdb_id > 0),
  media_type text not null check (media_type in ('movie','tv')),
  slot text not null check (slot in ('fresh:movie','fresh:series','fresh:anime','watchlist:movie','watchlist:series','watchlist:anime')),
  action text not null check (action in ('shown','swapped')),
  shown_at timestamptz not null default now()
);
alter table public.recommendation_memory_v113 enable row level security;
grant select, insert on public.recommendation_memory_v113 to authenticated;
grant usage, select on sequence public.recommendation_memory_v113_id_seq to authenticated;
drop policy if exists recommendation_memory_v113_select_own on public.recommendation_memory_v113;
create policy recommendation_memory_v113_select_own on public.recommendation_memory_v113 for select to authenticated using ((select auth.uid()) = profile_id);
drop policy if exists recommendation_memory_v113_insert_own on public.recommendation_memory_v113;
create policy recommendation_memory_v113_insert_own on public.recommendation_memory_v113 for insert to authenticated with check ((select auth.uid()) = profile_id);
create index if not exists recommendation_memory_v113_profile_slot_time_idx on public.recommendation_memory_v113(profile_id, slot, shown_at desc);
create index if not exists recommendation_memory_v113_profile_slot_tmdb_idx on public.recommendation_memory_v113(profile_id, slot, tmdb_id);
create or replace function public.cinetracker_recommendation_memory_v113() returns jsonb language sql stable set search_path='public' as $function$
 select coalesce(jsonb_agg(jsonb_build_object('tmdb_id',r.tmdb_id,'media_type',r.media_type,'slot',r.slot,'action',r.action,'shown_at',r.shown_at) order by r.shown_at desc),'[]'::jsonb) from public.recommendation_memory_v113 r where r.profile_id=auth.uid();
$function$;
create or replace function public.cinetracker_recommendation_record_v113(p_tmdb_id bigint,p_media_type text,p_slot text,p_action text default 'shown') returns jsonb language plpgsql set search_path='public' as $function$
declare v_uid uuid:=auth.uid(); v_row public.recommendation_memory_v113;
begin
 if v_uid is null then raise exception 'not_authenticated'; end if;
 if p_tmdb_id is null or p_tmdb_id<=0 then raise exception 'invalid_tmdb_id'; end if;
 if p_media_type not in ('movie','tv') then raise exception 'invalid_media_type'; end if;
 if p_slot not in ('fresh:movie','fresh:series','fresh:anime','watchlist:movie','watchlist:series','watchlist:anime') then raise exception 'invalid_slot'; end if;
 if p_action not in ('shown','swapped') then raise exception 'invalid_action'; end if;
 if p_action='shown' and exists(select 1 from public.recommendation_memory_v113 r where r.profile_id=v_uid and r.tmdb_id=p_tmdb_id and r.slot=p_slot and r.action='shown' and r.shown_at>now()-interval '20 seconds') then
  select * into v_row from public.recommendation_memory_v113 r where r.profile_id=v_uid and r.tmdb_id=p_tmdb_id and r.slot=p_slot and r.action='shown' order by r.shown_at desc limit 1;
 else
  insert into public.recommendation_memory_v113(profile_id,tmdb_id,media_type,slot,action) values(v_uid,p_tmdb_id,p_media_type,p_slot,p_action) returning * into v_row;
 end if;
 return jsonb_build_object('id',v_row.id,'tmdb_id',v_row.tmdb_id,'media_type',v_row.media_type,'slot',v_row.slot,'action',v_row.action,'shown_at',v_row.shown_at);
end;$function$;
grant execute on function public.cinetracker_recommendation_memory_v113() to authenticated;
grant execute on function public.cinetracker_recommendation_record_v113(bigint,text,text,text) to authenticated;
