create table if not exists public.favorite_actors (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  tmdb_person_id integer not null check (tmdb_person_id > 0),
  actor_name text not null,
  profile_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint favorite_actors_user_person_key unique (user_id, tmdb_person_id)
);

alter table public.favorite_actors enable row level security;

drop policy if exists favorite_actors_select_own on public.favorite_actors;
create policy favorite_actors_select_own on public.favorite_actors
for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists favorite_actors_insert_own on public.favorite_actors;
create policy favorite_actors_insert_own on public.favorite_actors
for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists favorite_actors_update_own on public.favorite_actors;
create policy favorite_actors_update_own on public.favorite_actors
for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists favorite_actors_delete_own on public.favorite_actors;
create policy favorite_actors_delete_own on public.favorite_actors
for delete to authenticated
using ((select auth.uid()) = user_id);

grant select, insert, update, delete on table public.favorite_actors to authenticated;
grant usage, select on sequence public.favorite_actors_id_seq to authenticated;

create index if not exists favorite_actors_user_created_idx on public.favorite_actors(user_id, created_at desc);
